### ISSUE TITLE
Pass default values into GooeyParser

### ISSUE THREAD

**Issue by chris1610** [chriskiehl/Gooey#100]
I have basic structure that looks like this:

``` python
@Gooey(program_name="Create Quarterly Marketing Report")
def parse_args(default_args):
    """ Use GooeyParser to build up the arguments we will use in our script
    """
    parser = GooeyParser(description='Create Quarterly Marketing Report')
    parser.add_argument('data_directory',
                        action='store',
                        default=default_args.get('data_directory'),
                        widget='DirChooser',
                        help="Source directory that contains Excel files")
    args = parser.parse_args()
    return args

if __name__ == '__main__':
    # See if there are any prior results stored
    if os.path.isfile("gui_args.json"):
        with open("gui_args.json") as data_file:
            stored_args = json.load(data_file)
    conf = parse_args(stored_args)
```

It all seems to work but I keep getting an error like this:

```
 conf = parse_args(stored_args)
TypeError: <lambda>() takes no arguments (1 given)
```

I think there's a lambda function that is getting tripped up when I try to pass in my defaults. If there some other way I could handle this?

Basically what I am trying to do is save the entered values from the previous run and use them as defaults for the next run. With the basic argparse, I can do it but when trying to use gooey I get those errors.

**Comment by chriskiehl** [comment]
I'm not immediately sure where that error is originating. 

A work around is simply to move that initialization code into your main method. 


    @Gooey(program_name="Create Quarterly Marketing Report")
    def parse_args():
        """ Use GooeyParser to build up the arguments we will use in our script
        """
  
        defaults = {}
        if os.path.isfile("gui_args.json"):
            with open("gui_args.json") as data_file:
                defaults = json.load(data_file)
  
        parser = ArgumentParser(description='Create Quarterly Marketing Report')
        parser.add_argument('data_directory',
                            action='store',
                            default=defaults.get('data_directory', ''),
                            help="Source directory that contains Excel files")
        args = parser.parse_args()
        return args
  
    if __name__ == '__main__':
        parse_args()
  
  if __name__ == '__main__':
      parse_args()

**Comment by chris1610** [comment]
Ahh. Good recommendation. I should have thought of that.

If you feel the desire to chase down this "issue", here is a simple standalone program that gives me the same error:

``` python
from gooey import Gooey, GooeyParser


@Gooey()
def parse_args(default_name):
    parser = GooeyParser()
    parser.add_argument('data_directory',
                        action='store',
                        default=default_name,
                        widget='DirChooser')
    return parser.parse_args()

if __name__ == '__main__':
    conf = parse_args("/sample")
    print "Done"


```

**Comment by chriskiehl** [comment]
Years of debugging later, and... this is now fixed on the [release branch](https://github.com/chriskiehl/Gooey/commit/14e912acb8c74861decb1d31bf9c916a40885299)! 🎉 🎉
