### ISSUE TITLE
Image Customisation

### ISSUE THREAD

**Issue by mattloose** [chriskiehl/Gooey#101]
Hi,

Is there any plan to introduce custom icons? It would be great to be able to replace the terminal image with something more appropriate to each program.

Really nice tools!

Thanks,

Matt

**Comment by chriskiehl** [comment]
Hey, I somehow totally missed this issue. 

Having multiple icons sets or themes was always something I wanted from the beginning. However, I lack the artistic skills to come up with additional icons. I've had a Call for Artists at the top of the github README for a little over a year at this point, but alas, no takers so far.  :( 

If you've got a set of icons or images that you want to use, you could drop them into the `images/` directory in Gooey and overwrite the existing media. Outside of that, there's not really any established machinery in the code for supplying custom image paths.

**Comment by DanielAndreasen** [comment]
Would it be better to maybe have an option for the developer to provide a different set of icons?
E.g. I use Gooey for some astronomy software, and making some stars as an icon will not be very popular (I guess). But if I can implement it as an option when calling Gooey, everything would be fixed.

**Comment by chriskiehl** [comment]
@DanielAndreasen, I've added a few features to make supplying your own images a little easier. 

The `@Gooey` decorator now accepts a `image_dir` parameter with which you can supply a directory containing your custom images. 

I went with an approach kinda along the lines of a Django admin. Namely, the defaults are always loaded, but you can overwrite specific images by supplying a new path. So, you don't need to supply _all_ images, just those that you want to overwrite. They're implicitly loaded based on filename. So, just putting an image in your images directory called `config_icon.png` would be pulled in and used in place of the default `config_icon.png`. 

example use:

	@Gooey(image_dir='/path/to/my/image/dir') 
	def main():
	   ...

Available icon names: 

* program_icon.ico
* success_icon.png
* running_icon.png
* loading_icon.gif
* config_icon.png
* error_icon.png

**Comment by DanielAndreasen** [comment]
It is not surprising that this works too :smile:

**Comment by chriskiehl** [comment]
Yay!
