### ISSUE TITLE
Compatibility with configargparse

### ISSUE THREAD

**Issue by mattloose** [chriskiehl/Gooey#102]
Is Gooey compatible with configargparse?

It doesn't appear to be but just checking,

thanks,

Matt

**Comment by chriskiehl** [comment]
I don't know much about ConfigArgparse. Is it using argparse underneath the hood? If so, then probably -- gooey is built primarily off the `_actions` collection inside of `argparse`. However, if it _isn't_ backed by argparse, then, nay: not compatible. 

Pull request are always welcome if you want to write a `configargparse_to_json` module!
