### ISSUE TITLE
add multiple add_mutually_exclusive_group behaves incorrectly

### ISSUE THREAD

**Issue by codingsnippets** [chriskiehl/Gooey#103]
right now when you add  multiple add_mutually_exclusive_group , they will show as the same one.

**Comment by smoskwa** [comment]
I also came across that recently

Somewhat related, the name of the mutually exclusive group is hardcoded to 'Set Verbosity Level'

https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/widgets/components.py#L185

**Comment by chriskiehl** [comment]
Ugh.. amateur hour on this project, I tell you. 

Will fix hard coded nonsense shortly.

**Comment by chriskiehl** [comment]
@codingsnippets @smoskwa 

Fixed!
