### ISSUE TITLE
Status window not updated in real time, only at the end of execution

### ISSUE THREAD

**Issue by joaquins** [chriskiehl/Gooey#105]
Using Gooey 0.8.11.1 - win32

When running a script that has several print statements during the execution, all of them are displayed in the status window at the end of the execution, not in real time.

During the execution the status window remains totally empty, and no feedback of any kind is shown.

**Comment by chriskiehl** [comment]
Fixed! 

It was missing the the `PYTHONUNBUFFERED` flag. Fix is in the repo and PyPi. 

Thanks for the bug! :)

**Comment by joaquins** [comment]
Thanks a lot for your quick fix.

Great project, keep on it! ;)

**Comment by lrq3000** [comment]
I had the same issue, another way to fix that was to force flush() stdout (`sys.stdout.flush()`), and this correctly updated the status window. But this fix is better, I'll try that out!

**Comment by chriskiehl** [comment]
@lrq3000 

Another hack you could try (if you're on windows (and assuming `PYTHONUNBUFFERED` doesn't work for some reason)) is to reopen stdout with no buffering

```python 
 nonbuffered_stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  sys.stdout = nonbuffered_stdout
```

**Comment by lrq3000** [comment]
@chriskiehl wow, nice hack, thank's for the trick, this can be very useful! :)
