### ISSUE TITLE
Feature request: Interpret add_argument_group as different section

### ISSUE THREAD

**Issue by joaquins** [chriskiehl/Gooey#108]
I'm working in a command line script with lots of arguments and arguments groups.

Now the arguments inside add_argument_group are displayed exactly the same as the others.

A nice to have feature would be to have them separated (displaying the 'title'). Maybe a similar approach as the currently used by subparsers could be helpful.

**Comment by chriskiehl** [comment]
Working on it.

**Comment by chriskiehl** [comment]
Argument groups are now first class citizens! 

NOTE! For backward compatibility reasons, Gooey will re-write the default "Positional Arguments" group to "Required Arguments." However, you can turn this legacy option off by passing `use_legacy_titles=False` to the `Gooey` decorator.
