### ISSUE TITLE
Feature request: Option to remember last used arguments

### ISSUE THREAD

**Issue by joaquins** [chriskiehl/Gooey#109]
In frequently used command line scripts with large arguments, is useful to reuse the latest used arguments.

I'm implementing this feature outside Gooey by saving a JSON file with the contents of the args.parse() result.

This JSON is also loaded before the argparse definitions and used for setting the 'default' values.

This feature inside gooey would be even easier to implement, following a similar approach as the current "dump_build_config" feature.

**Comment by chriskiehl** [comment]
Not a bad idea for a feature. I can see a `save_input` style flag being useful. 

Added to the TODO!

**Comment by chriskiehl** [comment]
Feature added in ac71408 by @joaquins.
