### ISSUE TITLE
Checkbox widgets are displayed at the bottom of the window

### ISSUE THREAD

**Issue by joaquins** [chriskiehl/Gooey#110]
When using store_true arguments, the Checkbox widget is created at the very bottom of the 
configuration window, not following the order of creation as the other widgets.

**Comment by joaquins** [comment]
Umm, taking a look at component_builder.py, it seems that this is made on purpose: checkbox_args are separated from the rest of the optional_args and added at the end...

Is there a reason for this? 

Thanks

**Comment by chriskiehl** [comment]
Yup. Pretty simple reason: I thought it was ugly to mix 'em. 

However, this is now configurable! Mingling widget types are now covered. It's controlled via the `group_by_type` flag on the Gooey decorator. 

```python

@Gooey(dump_build_config=True, program_name="Widget Demo", group_by_type=False)
def main():
  my_cool_parser = ArgumentParser(description=desc)
  ... 
  # your options here 
```
