### ISSUE TITLE
Pyinstaller, Windows, not a valid Win32 application

### ISSUE THREAD

**Issue by micmica** [chriskiehl/Gooey#111]
Hello, here is my problem,
dist folder is created and my script.exe works fine atfer a lot of hidden imports, hooks and so on..
And now when I copy dist folder to the Virtual Machine I get this error:
 ...build\script\out00-PYZ.pyz\ctypes line 356 in __init__
 Error 193 1% not a valid Win32 application.
And that path doesn't even exist on VM, isn't dist folder enough to distribute to the users?
Any advice for this?

**Comment by chriskiehl** [comment]
Hey @micmica, 

I've had success following the instructions provided by @Roshgar in Issue #58. However, I haven't had time to pin down thorough set of PyInstaller steps/instructions for general consumption. I'm going to close this for now since there's already exisitng PyInstaller issues.
