### ISSUE TITLE
Widgets not correctly used in sub_parsers

### ISSUE THREAD

**Issue by enricobacis** [chriskiehl/Gooey#112]
When using a widget in a subparser, this is not correctly used. For example the code:

    @Gooey
    def main():
        parser = GooeyParser(description="example")
        parser.add_argument("dir", help="directory", widget="DirChooser")
        args = parser.parse_args()

correctly use the `DirChooser` widget for the `dir` value:

<img width="611" alt="screen shot 2015-10-08 at 10 10 13" src="https://cloud.githubusercontent.com/assets/1180682/10360909/eaa6747e-6da4-11e5-9730-0e22a72e754e.png">

While the code:

    @Gooey
    def main():
        parser = GooeyParser(description='example')
        subs = parser.add_subparsers()
        sub = subs.add_parser("sub")
        sub.add_argument("dir", help="directory", widget="DirChooser")
        args = parser.parse_args()

does not use the widget:

<img width="611" alt="screen shot 2015-10-08 at 10 12 38" src="https://cloud.githubusercontent.com/assets/1180682/10360969/4a405558-6da5-11e5-8461-726144677b3f.png">

**Comment by chriskiehl** [comment]
Merged you pull request. Thanks for the fix!
