### ISSUE TITLE
Run as CLI

### ISSUE THREAD

**Issue by DanielAndreasen** [chriskiehl/Gooey#117]
This might sound against the whole project, but is there a way to use my new GUI application as a CLI?  
I really like to use CLIs, but the power of having a GUI is appealing too. When I run my CLI (which now have the Gooey decorator) with inputs at the command prompt, the GUI opens up.

Maybe the GUI should only open up, if no arguments are parsed. Or if it runs with a `-c` flag for command, the GUI will not start up.

Btw, I love this project, keep up the good work! :+1:

**Comment by smoskwa** [comment]
I manage this using setuptools:

```python
setup(
  # other stuff
  entry_points={
      'console_scripts': ['foo = foo:start_cli',],
      'gui_scripts': ['foo-gui = foo:start_gui',],
   }
)
```

Then in your python code, instead of decorating your main with `@gooey` you use something like this:

```python
def start_cli():
  # argparse stuff goes here

start_gui = Gooey(start_cli)
```

Its not quite that simple if you want to work in some extra GooeyParser features like the FileChooser widget.. but no great challenges to be overcome

**Comment by chriskiehl** [comment]
This functionality is actually already present, but undocumented. Gooey accepts a command line flag to bypass its GUI features and run the script normally. 

Pass `--ignore-gooey` to your script when you start it and it'll function as a normal CLI.   

Here's the bit where it routes around gooey: https://github.com/chriskiehl/Gooey/blob/master/gooey/python_bindings/gooey_decorator.py#L77

**Comment by DanielAndreasen** [comment]
That's clever and works like a charm! Thanks a lot :)

**Comment by raphaelsetin** [comment]
My comment on [this other issue](https://github.com/chriskiehl/Gooey/issues/296#issuecomment-2067802948) may be of help if you want to run just in a CLI mode without using extra flags, and also with the ability to customize the CLI handler isolated from Gooey.
