### ISSUE TITLE
Support Qt

### ISSUE THREAD

**Issue by dougthor42** [chriskiehl/Gooey#12]
Adding Qt support would greatly increase your userbase :-).

**Comment by hadmack** [comment]
+1 would love to see a PySide version.  Of course this gets a little sticky since the popular Anaconda includes PyQt rather than PySide so licensing issues will arise.

**Comment by gdementen** [comment]
It seems like this might happen after all :). See discussion at #65 .

**Comment by chriskiehl** [comment]
It _is_ happening. Albeit... _slowly.._

But happening!
