### ISSUE TITLE
non asci error messages

### ISSUE THREAD

**Issue by bmu** [chriskiehl/Gooey#125]
Seems that when a script throws an error message with non asci characters in it gooey fails (at least on windows) to show an error message in the gui (it happened because I started a script from a file path with german umlauts and the traceback is shown in the gooey error message). Instead the traceback is shown in the console.

As far as I can see from the gooey traceback (I cannot copy the traceback, besause it is blocked in the dos console) the problem is in [Controller.error_dialog](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/controller.py#L112). 
Maybe this could be handled there before the error message is send to `wx.MessageDialog`

**Comment by chriskiehl** [comment]
Will fix!

**Comment by bmu** [comment]
ok. thanks. nice.

**Comment by chriskiehl** [comment]
Do you have a minimal example that can recreate the problem?

**Comment by bmu** [comment]
Sorry, but I can't reproduce this error myself today! It works with my script!
So I'll close the issue.
