### ISSUE TITLE
Gooey with pythonw

### ISSUE THREAD

**Issue by bmu** [chriskiehl/Gooey#126]
Would be nice to allow a user to just double click on a script and open the script with `pythonw` so without any dos console on windows.

However it seems that Gooey is in a endless loop, when started with a double click and `pythonw`.

**Comment by chriskiehl** [comment]
This [works on my machine](http://programmingexcuses.com/) : ) 

Can you provide an example where it is _not_ working? Try the demo code below (Remove the .txt extension). It should fire right up on double click. 


[widget_demo2.pyw.txt](https://github.com/chriskiehl/Gooey/files/29304/widget_demo2.pyw.txt)

**Comment by bmu** [comment]
same with this script :-(

seems to be in an endless loop. I fill in some details, click "Start" an the widget says,
the code is running. At the same time a new widget pops up, with the "Settings" again.

**Comment by chriskiehl** [comment]
Please supply a code sample that reproduces the issue
