### ISSUE TITLE
FileSaver issue on Mac OS X

### ISSUE THREAD

**Issue by marshmit** [chriskiehl/Gooey#132]
Hi,

first of all - thank you for sharing such a great tool with us, have been using it for 1-2 weeks now and it is great.

However, I noticed a bug on Mac OS X when trying to use the FileSaver ( throws index out of range exception on OK).
Looking a little bit into it, this what I think is the problem:
In the widget_pack.py BaseFileChooser.get_path function, the dlg.GetPaths() returns an empty list (works fine on Ubuntu). It seems on Mac OS X only the dlg.GetPath() method returns the correct thing (I'm not familiar with wxWidgets, so not sure what is intended here, but it might be a wxWidgets bug?).
Anyway if wrote a quick fix for me checking whether getPaths() was empty and then returning getPath(). I guess checking whether  we are in a FileSaver might be the better way - but right now I couldn't figure out how to check for that quickly right now ...

``` python
def get_path(self, dlg):
    if isinstance(dlg, wx.DirDialog) or isinstance(dlg, CalendarDlg):#here should be a check if filesavedialog?
      return maybe_quote(dlg.GetPath())
    else:      
      paths = dlg.GetPaths()      
      if len(paths) == 0:#happens with FileSaver on Mac OS X
          return maybe_quote(dlg.GetPath())
      return maybe_quote(paths[0]) if len(paths) < 2 else ' '.join(map(maybe_quote, paths))
```

Oh and one more thing - you could mention the FileSaver in the readme - took me a while till I learned about it ;)

Cheers
Marwin

**Comment by chriskiehl** [comment]
Hey @marshmit, 

Thanks for the bug report! Wx can be frustratingly peculiar with how some of its widgets behave across the various platforms. 

I'll make sure this is fixed in the next commit!

**Comment by chriskiehl** [comment]
Fixed! 

`pip install -U gooey` to get the latest working version
