### ISSUE TITLE
Metavar for add_parser

### ISSUE THREAD

**Issue by jslirola** [chriskiehl/Gooey#134]
Is there some way to show an equivalent "metavar" for add_parser?

`another_parser = subs.add_parser('My_option', help='My Option')`

![issue_uppercase](https://cloud.githubusercontent.com/assets/6697559/11767759/ee66662c-a1b7-11e5-8762-85f6ded668c7.png)

Maybe showing the attribute help instead the name but i don't know how to do it. I read the documentation of argparse without luck.

Related with #133

**Comment by chriskiehl** [comment]
@jslirola Done (finally)! 

As mentioned in the other issue, you can customize the appearance of the action by supplying a `prog` argument when you declare your subparser. 

```python 

parser = GooeyParser(description=settings_msg)
parser.add_argument('--verbose', help='be verbose', dest='verbose',
                      action='store_true', default=False)
subs = parser.add_subparsers(help='commands', dest='command')
# note the extra `prog` argument here
curl_parser = subs.add_parser('curl', prog='My Curl Program', help='curl is a tool to transfer data from or to a server')
```
