### ISSUE TITLE
Gooey with Click https://github.com/mitsuhiko/click ?

### ISSUE THREAD

**Issue by pombredanne** [chriskiehl/Gooey#135]
How hard would it be to have Gooey work with Click https://github.com/mitsuhiko/click a popular CLI framework by @mitsuhiko maker of Flask among other super goodies?

Note that Click uses neither `argparse` nor `optparse` but should provide introspection capabilities.

**Comment by chriskiehl** [comment]
@pombredanne That the first I've ever heard of Click. The composable decorator approach it takes is pretty interesting. According to the docs, its internals are actually a [fork of optparse](http://click.pocoo.org/5/why/#why-not-argparse), which in turn has similar conventions to argparse (e.g. types, dests, metavars, etc..), so.. I imagine it wouldn't be too difficult.

**Comment by pombredanne** [comment]
@chriskiehl I use it in a few project after having used optparse, argparse, baker, docopt, cliff and several other and I find it working better for me. 

For instance here: https://github.com/nexB/scancode-toolkit/blob/a967fc768f8f9c39e066982eb5015fcf3b2952d5/src/scancode/cli.py#L235

I am not all alone there: https://github.com/search?l=python&q=import+click+command&ref=searchresults&type=Code&utf8=%E2%9C%93

I cannot say I blindly use any code from pocoo and @mitsuhiko but code from this provenance definitely has been working for me and is usually not too shaby... and way better than anything I can write :)

Now, what would be the best approach? I do not thing parsing the Python sources would make sense with Click. If so where would you plug that in?

**Comment by chriskiehl** [comment]
Gooey doesn't really parse anything. It uses good ol' fashion introspection. 

Being that the internals are forked from optparse, I'd wager that the method would be quite the same as the one for argparse: monkey patch its `parse_args()` equivalent, and then pump its attributes over to Gooey. 

However, having only skimmed the docs, that would be my best uninformed guess at a starting point.

**Comment by pombredanne** [comment]
@chriskiehl commented 17 hours ago
> Gooey doesn't really parse anything. It uses good ol' fashion introspection. 

I thought that you were parsing source code based on this: https://github.com/chriskiehl/Gooey/blob/3c71869acab9b6541f004202cc61e48750366c4c/gooey/python_bindings/source_parser.py#L19

**Comment by chriskiehl** [comment]
Ha! Yeah, I neglected to say _anymore_ : ) It doesn't parse anything... _anymore_. Gooey originally grew out of me messing around with the ast, so there is certainly some vestigial parsing code in there. But now it just patches the `parse_args` call and gets everything that way. 

I have a branch sitting locally that finally cleans up all the cruft, but.. alas.. time.

**Comment by yoavram** [comment]
:+1:

**Comment by chakkasm** [comment]
I am also using Click package and appreciate any update on this..any roadmap??

**Comment by mgaitan** [comment]
IMHO the best way to go is making gooey supports https://github.com/wooey/clinto spec to build interfaces, and build extra parsers on that project.

**Comment by pombredanne** [comment]
@mgaitan do wooey and gooey use the same input from clinto?

**Comment by mgaitan** [comment]
@pombredanne not currently. would be a great idea IMHO

**Comment by bittner** [comment]
Note that there is [QUICK](https://github.com/szsdk/quick) for `click`, a project inspired by Gooey.

**Comment by chriskiehl** [comment]
Closing. No plans to implement at the moment. 

Community patches are always welcome, though!

**Comment by raphaelsetin** [comment]
My comment on [this other issue](https://github.com/chriskiehl/Gooey/issues/296#issuecomment-2067802948) may be of help if you want to run a CLI mode without having to pass extra flags, and also with the ability to customize the CLI handler isolated from Gooey.

My use case was to define a GUI function using Gooey and a CLI function using Click; both were defined in separate functions. I know it's not the most convenient way of handling this, but it's the only way of customizing the CLI mode isolated from the GUI mode.
