### ISSUE TITLE
sorting subcommands 

### ISSUE THREAD

**Issue by umeshghosh** [chriskiehl/Gooey#140]
I don't see any option to sort subcommands in the actions menu. Currently the functions are ordered randomly:

https://cloud.githubusercontent.com/assets/1408720/7950189/4411b824-0965-11e5-905a-3a2b5df0efb3.jpg

**Comment by chriskiehl** [comment]
Fixed!

You were right on the randomness. Those fields on the left were populated from a dictionary, which has no respect for ordering. Now fixed.

Thanks for the report!
