### ISSUE TITLE
Problems with dependencies

### ISSUE THREAD

**Issue by DanielAndreasen** [chriskiehl/Gooey#143]
Hi again,

I try to install Gooey, but have problems with some dependencies. With pip I actually manage to install the package, but when I launch a script it complains about `wxPython`. After finally finding a solution on the official web page (`sudo pip install --upgrade --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix`), it then complains about a package called `animate`.

Is there an easier way to install it? Maybe a requirement file?

**Comment by bilderbuchi** [comment]
are you on Python 2 or 3?

**Comment by DanielAndreasen** [comment]
Python 2.7.10

**Comment by chriskiehl** [comment]
Looks like you're trying to install the wrong version for starters. `wxPython_Phoenix` is the unfinished, mostly-stalled, not stable next release of WxPython.

These are the instructions I usually follow when setting up Wx on linux. They've worked for me on both Ubuntu and Mint http://wiki.wxpython.org/InstallingOnUbuntuOrDebian

**Comment by JessiePBhalerao** [comment]
I have both wxpython-3.0.2.0 and wx installed on Mac OS X via:
brew install wxpython
pip install wx

I can't get past this error when importing Gooey:
```Traceback (most recent call last):
  File "utility.py", line 17, in <module>
    from gooey import Gooey, GooeyParser
  File "/Users/jbhalerao/TRIAL/lib/python2.7/site-packages/gooey/__init__.py", line 2, in <module>
    from gooey.python_bindings.gooey_decorator import Gooey
  File "/Users/jbhalerao/TRIAL/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 14, in <module>
    from gooey.gui import application
  File "/Users/jbhalerao/TRIAL/lib/python2.7/site-packages/gooey/gui/application.py", line 8, in <module>
    from gooey.gui.controller import Controller
  File "/Users/jbhalerao/TRIAL/lib/python2.7/site-packages/gooey/gui/controller.py", line 3, in <module>
    from gooey.gui.windows.base_window import BaseWindow
  File "/Users/jbhalerao/TRIAL/lib/python2.7/site-packages/gooey/gui/windows/base_window.py", line 14, in <module>
    from gooey.gui.windows import footer, header, layouts
  File "/Users/jbhalerao/TRIAL/lib/python2.7/site-packages/gooey/gui/windows/footer.py", line 8, in <module>
    import wx.animate
ImportError: No module named animate```

Any suggestions?

**Comment by JessiePBhalerao** [comment]
Answering my own question here for the benefit of others.  When using wxpython in a virtualenv, these instructions worked to get _wxpython_ and _wx_ working:  http://www.thebrokendesk.com/post/using-wx-python-in-a-virtual-environment/

The only change I made was to use `PYTHON=/usr/local/bin/python2.7` in the bash script suggested rather than ipython.

**Comment by kdaily** [comment]
I'm unable to get past this error as well, and the link that @JessiePBhalerao posted is broken.

I'm doing this on Fedora, got wx from the package repo:

```
dnf info wxPython
Last metadata expiration check: 2:23:22 ago on Tue Feb 28 06:58:59 2017.
Installed Packages
Name        : wxPython
Arch        : x86_64
Epoch       : 0
Version     : 3.0.2.0
Release     : 8.fc23
Size        : 42 M
Repo        : @System
From repo   : updates
Summary     : GUI toolkit for the Python programming language
URL         : http://www.wxpython.org/
```

I also did this using `pip` with the same error.

This was tested both inside and outside of a `virtualenv` with the same results.

**Comment by JessiePBhalerao** [comment]
It's been a while, so I don't remember the details of the problem, so I found this cached version of instructions linked above:  http://webcache.googleusercontent.com/search?q=cache:LnPLcLNUr4EJ:www.thebrokendesk.com/post/using-wx-python-in-a-virtual-environment/+&cd=5&hl=en&ct=clnk&gl=us

**Comment by SorcHorc** [comment]
I had issues with wxPython due to having Anaconda installed. It's working now and I am posting here to hopefully save others time. 

Issue I had:
import wx
ImportError: No module named wx

Solution: 
Go to your Anaconda2/Lib/site-packages and copy the 'wx-<version>-msw' folder.
Go to Python27/Lib/site-packages and paste the 'wx-<version>-msw' folder there.
Open the 'wx-<version>-msw' folder and move the 'wx' folder out into Python27/Lib/site-packages.
