### ISSUE TITLE
cannot debug when using Gooey

### ISSUE THREAD

**Issue by shelper** [chriskiehl/Gooey#144]
I am using pycharm community version 5.x
i have a very simple program like below:
```python
from gooey import Gooey, GooeyParser

@Gooey(dump_build_config=False, program_name="Tech Report Tool")
def main():
    report_logfile = r"\\us-rp-rdmatsci\MATSCI-F\TechReports\TechReports.xlsx"

    desc = "upload or update the report file in PDF format"
    arg_parser = GooeyParser(description=desc)
    arg_parser.add_argument("ReportID", help="please input your report ID in format yy-Cxx")
    arg_parser.add_argument("File", help="Report pdf file upload/update", widget="FileSaver")
    # i can step through above lines
    args = arg_parser.parse_args()
    # after this line, i got the GUI window, then the program cannot stop at any break point for below lines
    ...
    
if __name__ == '__main__':
    main()
```

I was surprised no issue filed for this, or people just dont use debug in pycharm by using `import pdb`??

**Comment by chriskiehl** [comment]
Gooey runs your code in a totally separate process -- like, it `Popen`s it, so your break points aren't being hit in the thread that pycharm is watching. 

I'd suggest that you don't try to debug with the Gooey decorator on. It's simply a fancy way of passing command line args to your app. Work out the bugs, then add Gooey -- unless of course the source of bugs _is_ Gooey, in which case open a new issue detailing where it is breaking : )
