### ISSUE TITLE
Problem passing in default arguments

### ISSUE THREAD

**Issue by joelauerbach** [chriskiehl/Gooey#145]
I'm trying to set up my input arguments as follows: 

 parser.add_argument('History_Loc',
                        action='store',
                        default='/Users/me/Desktop/History.csv',
                        widget='FileChooser',
                        help="Path to current History file")

It accepts the exact file path in the default field above when I select it from the FileChooser widget, but not when I leave the default as is, nor when I type it in manually. In the latter two cases, I get the following error:

IOError: File Users/me/Desktop/History.csv does not exist

What's going wrong? Again, in all three cases the file path is exactly the same, it just only works when I select it using the widget.

**Comment by chriskiehl** [comment]
:+1: for figuring it out : )
