### ISSUE TITLE
choises do not work in 0.9.2

### ISSUE THREAD

**Issue by DanielAndreasen** [chriskiehl/Gooey#151]
Hi,

I just updated `Gooey` and now I don't get a dropdown menu the places where I have `choices`. It worked without problems in 0.8.15.2 which was my previous version.
Since it seems there is only one version available with pip, I can't downgrade either.

Can you help with this?

**Comment by chriskiehl** [comment]
Fudge, I'll check it out tonight.

**Comment by chriskiehl** [comment]
Fixed! 

`pip install -U gooey` to grab the latest. Thanks for the report!

**Comment by DanielAndreasen** [comment]
Seems to work. Thanks for the fix :+1:
