### ISSUE TITLE
Progress bar on OS X is tiny

### ISSUE THREAD

**Issue by terhorst** [chriskiehl/Gooey#153]
![image](https://cloud.githubusercontent.com/assets/18204/13056723/f023b884-d3cb-11e5-8ed2-13c1a71c7f92.png)

**Comment by chriskiehl** [comment]
lol! 

Well... that is indeed a little on the tiny side. I'll investigate. 

Thanks for the report!

**Comment by jjconti** [comment]
That's true. The same happens to me.

**Comment by chriskiehl** [comment]
Fixed! 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/1408720/35478197-89f4b012-038b-11e8-8dd9-059a414919f8.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1408720/35478205-b6738fa0-038b-11e8-880e-ca299ae46167.png">
