### ISSUE TITLE
Group two DropDown

### ISSUE THREAD

**Issue by jslirola** [chriskiehl/Gooey#155]
Is it possible to do? I have a dropdown with a lot of choices, it have a specific format like "X-Y" (X and Y are numbers).

I thought split it in two, but i can't reduce the width of each. My idea:

`[ X ] - [ Y ]`

**Comment by chriskiehl** [comment]
Hey @jslirola ,

I've got no idea what you're asking me here. If you're still interested in the feature, re-open this with a little more detailed description -- maybe a mockup or two.
