### ISSUE TITLE
Gooey freezes when subparsers used

### ISSUE THREAD

**Issue by joelauerbach** [chriskiehl/Gooey#156]
Gooey works fine with subparsers/column layout on my local computer, but several coworkers I've distributed my app to have found that the first subparser behaves normally, but selecting any other option causes the input fields to become un-selectable. It also causes the other subparser options to become un-selectable. Any idea how to fix this?

**Comment by chriskiehl** [comment]
Hey, thanks for the report and apologies for the trouble! 

My off-the-cuff guess is that there's something interacting with the main GUI thread in a way that makes WX unhappy. Could you post the platform your on, gooey version, and a small code sample that reproduces the problem? 

I'm completely and totally buried under work right now, so a fix may be slow, but I'll try to investigate it.

**Comment by joelauerbach** [comment]
We're both running OS X El Capitan on early 2015 Macbook Airs. Glad you asked about gooey version - I'm running 0.8.16 (works) and she's running 0.9.2 (doesn't work). I'd upgrade to the latest version myself, but don't want to lose the working version if possible.

Here's some code that reproduces:

`from __future__ import print_function
from gooey import Gooey, GooeyParser
import module_a
import module_b
import module_c

@Gooey(program_name="Main")
def parse_args():
    parser = GooeyParser()

    subparsers = parser.add_subparsers(help='options', dest='subparser_name')

    a_fields = subparsers.add_parser('a')
    a_fields.add_argument('Links',
                        action='store',
                        default='',
                        widget='FileChooser',
                        help='')

    b_fields = subparsers.add_parser('b')
    b_fields.add_argument('Request_Date',
                        action='store',
                        default='',
                        help='')

    c_fields = subparsers.add_parser('c')
    c_fields.add_argument('Combined_File',
                        action='store',
                        default='',
                        widget='FileChooser',
                        help='')

    args = parser.parse_args()
    return args

if __name__ == '__main__':

    conf = parse_args()

    if conf.subparser_name == 'a':
        module_a.function_a(conf) 
    elif conf.subparser_name == 'b':
        module_b.function_b(conf)
    elif conf.subparser_name == 'c':
        module_c.function_c(conf)
`

`from __future__ import print_function

def function_a(conf):
	print('Ran A')`

`from __future__ import print_function

def function_b(conf):
    print('Ran B')`

`from __future__ import print_function

def function_c(conf):
    print('Ran C')`

Thanks a ton in advance. Great work you've done here - it's made our lives much much easier.

**Comment by chriskiehl** [comment]
Thanks for the extra details. I made version 0.8.16 visible on [PyPi](https://pypi.python.org/pypi/Gooey/) again in case you want to have then downgrade to that version while the fix is being worked on.

Apologies again for the brokenness!

**Comment by joelauerbach** [comment]
Thanks, Chris! Version 0.8.16 works for my colleague.

Incidentally, one other issue I've noticed is that the order that subparsers appear in the column list is very erratic - it doesn't seem to follow either the order that they're defined in the code, alphabetical order, or any other pattern that I can observe (or control). Version 0.9.2 I believe displayed in the order defined in the code.

**Comment by chriskiehl** [comment]
Finally closing this issue. 

Subparser behavior should be behaving well on all platforms these days ^_^
