### ISSUE TITLE
GooeyParser widget FileChoser doesn't work with unicode filenames

### ISSUE THREAD

**Issue by pocin** [chriskiehl/Gooey#157]
I can select the filename conatining unicode characters, but when I confirm it, the path doesnt show up in the final box.

**Comment by chriskiehl** [comment]
Please provide OS, gooey version, and a sample filename that produces the problem

**Comment by pocin** [comment]
Sorry for initial lack of info.
gooey=0.9.2.2
Ubuntu 15.10
sample filename = "Cina - Expedice_vše_8260_01.08.2015_31.01.2016.xlsx"
Python 2.7.10

If there is anything more I could do, just let me know. Thanks!

**Comment by chriskiehl** [comment]
Fixed! 

Version `0.9.2.3` now has better unicode handling. Thanks for the report!
