### ISSUE TITLE
RESOLVED: app does not run after following instructions for pyinstall

### ISSUE THREAD

**Issue by tetrismegistus** [chriskiehl/Gooey#159]
I followed the instructions at http://chriskiehl.com/article/packaging-gooey-with-pyinstaller/
 to configure my app with pyinstall, but launching the exe produces the following error (timeAndTotals is the script name):

> Fatal Error!
> timeAndTotals returned -1

I have attached the build.spec, the sourcecode for my app, and the output of pyinstall.

Thank you so much for your help, and Gooey!   

[timeAndTotals.zip](https://github.com/chriskiehl/Gooey/files/234451/timeAndTotals.zip)

**Comment by zodman** [comment]
try replacing console=False to console=True in the spec file

**Comment by tetrismegistus** [comment]
That solved it!  Thank you!
