### ISSUE TITLE
Add option to generate Python source code

### ISSUE THREAD

**Issue by Azeirah** [chriskiehl/Gooey#16]
This would greatly increase its usefulness, since now the generated Application is limited to what gooey does with the argparse code.

If it were to output the source code, a developer could then finetune it to his specific needs. I would personally use it as a boilerplate GUI for scripts I write.

**Comment by chriskiehl** [comment]
@Azeirah
@LudoVio 

The main `Gooey` decorator now accepts a param called `dump_build_config`. This will output all of the json used to power Gooey. 

Alternatively, there's also a method in the `gooey` package to do the same

    $ python -m gooey --create-build-config path/to/a/python/file.py

I'm closing this issue as I think `json` is a better fit for what Gooey is than raw python code. If you need something beyond the interface that Gooey provides, then I'd wager the handful of `GridSizers` and `TextCtrls` that would make up a Gooey source dump wouldn't really help all that much in the grand scheme of things. Plus! JSON makes it easy to roll friendly interfaces for non-python programs.

**Comment by Julian-O** [comment]
For the record: [This comment](https://github.com/chriskiehl/Gooey/issues/16#issuecomment-60506197) incorrectly attributed a quote by @LudoVio to me.

(It isn't a problem, but I was confused about my contribution to this thread, and want to prevent myself from being confused again by leaving this note.)

**Comment by chriskiehl** [comment]
@Julian-O Doh! Sorry!
