### ISSUE TITLE
Issue with Required Cols

### ISSUE THREAD

**Issue by phipsitn** [chriskiehl/Gooey#161]
i'm using your tool for a simple GUI for a 3 required argument CLI tool.  The first 2 arguments are FileChooser and the last is DirChooser.  Currently it puts the first 2 FileChooser's side-by-side, even if required_cols = 1.  I've tried setting group_by to false, optional cols to 1 also.  No luck.
![gooey_issue](https://cloud.githubusercontent.com/assets/20193977/16430084/d6f321b6-3d47-11e6-9ab5-2a9b6c50d805.jpg)

**Comment by chriskiehl** [comment]
Howdy! Could you give some more details? Which version of Gooey are you running, platform, code to reproduce, etc.. 

Thanks!

**Comment by phipsitn** [comment]
Thanks for getting back so quickly, here is the data you requested.

Gooey                     0.9.2.3                   <pip>

Windows 7, 64bit

@Gooey(program_name="Delta Tool", group_by_type=False)
def main():
    parser = GooeyParser(description="Takes 2 Formatted Excel Files and
Shows and Saves Delta Results")
    parser.add_argument('-i1','--input_excel_file1', metavar="Input Excel
File 1", action='store', help="Select location of First Excel File",
widget='FileChooser', required=True)
    parser.add_argument('-i2','--input_excel_file2', metavar="Input Excel
File 2", action='store', help="Select location of Second Excel File",
widget='FileChooser', required=True)
    parser.add_argument('-o','--output_directory', metavar="Output
Directory", action='store', help="Select Directory where you want Results
Saved", widget='DirChooser', required=True)
    args = parser.parse_args()

etc.

I really like this tool, you've done a great job on it.

**Comment by chriskiehl** [comment]
Alright, this is fixed in Master. PyPi is suddenly (and frustratingly!) giving me problems, so I'm currently unable to push the changes out there. So, you'll have to grab the latest from the repo rather than `pip install`ing, unfortunately.  

I'll have to figure out the PyPi stuff later.

**Comment by phipsitn** [comment]
Worked perfectly.  Thanks for the quick response, hopefully PyPi will stop causing you issues.

**Comment by phipsitn** [comment]
Worked Perfectly. Thanks. Hopefully the PyPi issues will work themselves out.

Get Outlook for iOS




On Tue, Jun 28, 2016 at 6:21 PM -0400, "Chris" <notifications@github.com> wrote:












Alright, this is fixed in Master. PyPi is suddenly (and frustratingly!) giving me problems, so I'm currently unable to push the changes out there. So, you'll have to grab the latest from the repo rather than pip installing, unfortunately.  



I'll have to figure out the PyPi stuff later.
