### ISSUE TITLE
Text overlaps image on Windows

### ISSUE THREAD

**Issue by edporteous** [chriskiehl/Gooey#166]
On the running screen, I have text overlapping the icons. When I resize the window the icon snaps to the right. Both the header and footer sections are affected.

I'm using Windows 7, wxpython 2.8.12.1 (msw-unicode), Python 2.7.8

![image](https://cloud.githubusercontent.com/assets/1362990/17514208/3217fb3c-5e29-11e6-919a-9b11465baf00.png)

**Comment by chriskiehl** [comment]
Interesting. I haven't encountered that before. It's like the `wx.Layout()` method isn't functioning properly. 

WX 2.8.12.1 is a few versions behind. Have you tried updating to the latest?

**Comment by edporteous** [comment]
Thanks, that was it. I upgraded to 3.0 and it works.

**Comment by chriskiehl** [comment]
Awesome! 👍
