### ISSUE TITLE
How can I use FileChooser to choose a directory?

### ISSUE THREAD

**Issue by jjconti** [chriskiehl/Gooey#171]
I have a parameter that is a directory. I tried to use FileChooser for it but the UI doesn't allow me to choose directories, only files. If I click on a directory and the click Open it opens the directory instead of choosing it. If I select a file and click Open, it choose it.

I'm using MscOS.

<img width="824" alt="captura de pantalla 2016-10-29 a las 11 20 24" src="https://cloud.githubusercontent.com/assets/53265/19830395/8cea763c-9dcd-11e6-8b61-760a166eed56.png">

**Comment by chriskiehl** [comment]
Ahoy! 

The docs have fallen a bit out of date. There's actually a `DirChooser` widget you can use. 

```python 
my_cool_parser.add_argument("DirectoryChooser", help='Choose a directory', widget="DirChooser")
```

That'll let you pick a directory rather than a file. There's also a `MultiDirChooser` if you'd like to select multiple directories.

**Comment by jjconti** [comment]
Great! Thanks!

**Comment by GilJ** [comment]
@chriskiehl What if I want to select either a file or a folder?

**Comment by chriskiehl** [comment]
@GilJ best option right now would be to use a Mutually Exclusive Group where one is a `FileChooser` and one is a `FileChooser`
