### ISSUE TITLE
Feature Request: Widget to select multiple items from list

### ISSUE THREAD

**Issue by rgzn** [chriskiehl/Gooey#176]
I would like to request a new widget similar to the DropDown widget, but where an arbitrary number of items could be selected.  Multiple options can be passed in  a single argument to argparser via:

`parser.add_argument('--foo', nargs='*')`

This widget would use that feature, and allow the user to select the available arguments from a list.

**Comment by chriskiehl** [comment]
I dig this idea. Large update is in the works. This is now on the list!

**Comment by aatwork** [comment]
Is there already an update which covers nargs?
Also if used together with choices?

**Comment by chriskiehl** [comment]
Added in 229e8b54!
