### ISSUE TITLE
Question: Method to format command line string from GUI arguments? 

### ISSUE THREAD

**Issue by rgzn** [chriskiehl/Gooey#179]
I was wondering if there is a convenient way to convert the argparser arguments back into a standard string that could be entered in the command line, ie "-a arg1 -b arg2 -c arg3".

In the examples, the subparser.py example uses Gooey as an interface to capture input to external CLI commands (like curl), but does not illustrate how to pass that input on to the external command. 

I'm currently doing this via converting the arguments namespace into a dict and then processing the values/keys into a string, but I was wondering if there's a better way?

**Comment by chriskiehl** [comment]
yep, yep. All that info will be in `sys.argv`

So, for instance, to rebuild the command line string with which your program is called, you can just `join` everything in `argv` 

```python
def main():
    command = ' '.join(sys.argv) 
    print(command) 
    ... 
    # rest of program
```

Example `sys.argv` output: 

```
['path/to/your/file.py', '-t', '123', '-g', '234', '-h', '345', '-j', 'qwerqwer', '--', 'one', 'two', 'three']
```

**Comment by rgzn** [comment]
Thanks!
