### ISSUE TITLE
mutiple subparsers un-selectable

### ISSUE THREAD

**Issue by etiaxie** [chriskiehl/Gooey#188]
my gooey version is 0.9.2.3 and just run GooeyExamples-subparsers_demo.py

the first gui looks fine:
![image](https://cloud.githubusercontent.com/assets/10825713/24129585/a579e2c0-0e1e-11e7-8e42-b2291cb6e8ac.png)
but when i chose other subparsers, the widgets will be mass together 
![image](https://cloud.githubusercontent.com/assets/10825713/24129631/e363718c-0e1e-11e7-8a5d-d81e1d3941f2.png)
it will be ok when i change the GUI size

**Comment by etiaxie** [comment]
up

**Comment by chriskiehl** [comment]
I believe this was a threading issue. Should be fixed as part of 1.0 (1511fb1). 

Feel free to re-open this if you're still seeing the issue.
