### ISSUE TITLE
Does Gooey support Python 3.6 for Windows?

### ISSUE THREAD

**Issue by constructor-igor** [chriskiehl/Gooey#189]
According to page https://www.wxpython.org/download.php, wxPython doesn't support Python 3.6.
Please, could you help me to understand if Gooey can work with Python 3.6 x64 Windows.
thank you,
Igor.

**Comment by chriskiehl** [comment]
Nope. The current WxWidgets version of Gooey is stuck on Python 2.x. However, a Python 3 compatible version (via Qt) is currently in development.
