### ISSUE TITLE
Matplotlib window integration

### ISSUE THREAD

**Issue by kapil-iitk** [chriskiehl/Gooey#190]
Is it possible to integrate the matplotlib plot window in the GUI?
Further, is it possible to arrange the GUI for big program (require around 30+ input parameters and 20+ output parameters)?
Thanks.

**Comment by chriskiehl** [comment]
First item: Nay. Not at the moment.  

Second item: I'm not totally sure I follow what you're after. Do you mean by grouping them, or some other kind of arrangement? 

If it's grouping, there is the subprocesser mode which lets you group input controls under their respective parent (https://cloud.githubusercontent.com/assets/1408720/7927433/f06a36cc-08ad-11e5-843e-9322df96d4d6.png).

**Comment by kapil-iitk** [comment]
Hello, Thank you for your reply. 
Can you please share more information/documentation/example on grouping?

**Comment by chriskiehl** [comment]
Gooey's second layout is triggered when the client code is using subparsers (https://docs.python.org/2/library/argparse.html#sub-commands). It's mostly for tools which have multiple paths each with their own options (git is a good example). However, if you could structure your arguments in such a fashion is may be of some use. 

Other than that, there's not really a way to group arbitrary arguments together (currently!).

**Comment by chriskiehl** [comment]
argparse groups are now first class citizens in Gooey. You can group to your heart's content!
