### ISSUE TITLE
FileChooser with non-existing files

### ISSUE THREAD

**Issue by muxketeer** [chriskiehl/Gooey#195]
I'm using the FileChooser widget to specify an output file.  As such, the file doesn't exist at the time that I specify it via the FileChooser Widget.  When I try to specify a file that doesn't exists, the GUI indicates it can't accept the path given because the file chosen "doesn't exist."
Can the FileChooser be expanded to allow for specifying a File which doesn't currently exist but will be created later by the execution of the underlying script?

**Comment by chriskiehl** [comment]
I think what you're after is the `FileSaver` widget. That'll let you specify a file that is yet to be created.

**Comment by muxketeer** [comment]
Works, thanks!  I'll look closer at widget_demo.py next time.
Great framework! Cheers!

**Comment by chriskiehl** [comment]
Glad you like it! 👍
