### ISSUE TITLE
Feature request: Substitute command-line arguments for Gooey defaults

### ISSUE THREAD

**Issue by jschultz** [chriskiehl/Gooey#200]
I've been trying to work out a simple way to combine command-line and GUI, and it struck me that it would be nice if arguments specified on the command-line could automagically appear as default values in the resulting GUI.

I tried reverse engineering, (and found the very useful but apparently undocumented '--ignore-gooey' option!) but it seems I'm a long way down the learning curve and thought it better to ask the experts who may be able to implement this in 10 minutes, explain why it is not a good idea, or else offer some pointers and I'll work on it myself.

What do people think?

**Comment by jjconti** [comment]
Thanks for this! `--ignore-gooey`

**Comment by zertrin** [comment]
Actually this is something that, as a first time user, I was kind of expecting to work already. I strongly support this feature request!

**Comment by chriskiehl** [comment]
Merged into release.
