### ISSUE TITLE
No module named wx.animate

### ISSUE THREAD

**Issue by andela-mekwenugo** [chriskiehl/Gooey#205]
https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/windows/footer.py#L8

**Comment by Fredr1kh** [comment]
Answer found in #143

"Go to Python27/Lib/site-packages and paste the 'wx--msw' folder there.
Open the 'wx--msw' folder and move the 'wx' folder out into Python27/Lib/site-packages"
