### ISSUE TITLE
How disable Gooey using python script not intectively

### ISSUE THREAD

**Issue by enricofer** [chriskiehl/Gooey#207]
I wrote a little batch utility in python and I made it interactive with gooey.
I am happy with it and I found it very user friendly, but is there a way to programmatically disable gooey interface and come back to command script behaviour making it not interactive? Or at least prepopulate gui slots with command parameters?

**Comment by chriskiehl** [comment]
For disabling gooey, you can pass `--ignore-gooey` as a commandline arg when calling your file. For pre-filling items in Gooey, you can specify defaults in your argparse code 

```parser.add_argument("-f', '--foo', default="foobar") ```

And they'll show in the form fields when Gooey loads. 

Additionally, there is a open pull request that allows you to pre-fill defaults using command line args, but I haven't carved out time to review it yet.
