### ISSUE TITLE
Progress Bar, add support for carriage return style progression

### ISSUE THREAD

**Issue by Fredr1kh** [chriskiehl/Gooey#213]
I'm printing in the terminal, and I'm working with lists that should be printed without a pause.

I tried reworking the example1 progress bar to use carriage return, so it overwrites the current line it's on.
Below is a minimum working example for what to achieve, comment out the parsing of args, and it runs in terminal.

    from __future__ import unicode_literals
    from __future__ import print_function
    import sys
    from time import sleep
    from gooey import Gooey, GooeyParser
   
    @Gooey(progress_regex=r"^progress: (\d+)%$")
    def main():
        parser = GooeyParser(prog="example_progress_bar_1")
        _ = parser.parse_args(sys.argv[1:])
   
       for i in range(100):
           print("progress: {}%".format(i+1), end="\r")
           sys.stdout.flush()
           sleep(0.1)
    
    
    if __name__ == "__main__":
        sys.exit(main())

**Comment by chriskiehl** [comment]
Closing. Rewriting text inside of the Gooey terminal is not something I immediately plan on supporting
