### ISSUE TITLE
Mutually Exclusive Group always in Optional Arguments section.

### ISSUE THREAD

**Issue by UtkarshKunwar** [chriskiehl/Gooey#215]
Adding the optional argument `required=True` for `add_mutually_exclusive_group()` does not move the RadioGroup to the Required Arguments section and remains in the Optional Argument section. The ArgParse documentation says [here](https://docs.python.org/2/library/argparse.html#mutual-exclusion) that the argument is supported.

I'm trying something like -
```
    mysubparser = subparser.add_parser('test', help='just for testing')

    mysubparser.add_argument('-t', '--text', dest='Text', help='Enter some text.', required=True)

    mutual_parser = mysubparser.add_mutually_exclusive_group(required=True)
    mutual_parser.add_argument('-a', '--A', dest='A choice', action='store_true', help='Choice A')
    mutual_parser.add_argument('-b', '--B', dest='B choice', action='store_true', help='Choice B')

    args = vars(parser.parse_args())
```

Which gives me this as a result.
![this](https://user-images.githubusercontent.com/14164924/28414271-84bb9b1a-6d68-11e7-87d8-562f0d22bf73.png)

Any ideas on what to do to move it to the Required Arguments sections?

**Comment by chriskiehl** [comment]
Bug. Will fix.

**Comment by chriskiehl** [comment]
This has finally been fixed! 

Mutually exclusive groups can now be in any section and use any widget type as an input.
