### ISSUE TITLE
What is the recommended way to support a --nogui option? 

### ISSUE THREAD

**Issue by karlpeterhugo** [chriskiehl/Gooey#218]
Hi, great stuff!

I may be blind but after some searching it still is not obvious to me how to have one python script that can be called in either gui or nogui mode. Is there a recommendation?

**Comment by chriskiehl** [comment]
You can pass `--ignore-gooey` as an argument to your script. 

e.g. 

```python your_cool_script.py --ignore-gooey [rest of your cmd line args]```
