### ISSUE TITLE
FileChooser widget can't provide a file that doesn't exist

### ISSUE THREAD

**Issue by sboden** [chriskiehl/Gooey#221]
I use GooeyParser in a python script. I have a -i and -o, options for an inputfile and an output file.

I put a FileChooser widget on both -i and -o. I can select an inputfile without problems (a file that exists). But option -o is supposed to be either an existing file or a new file: existing files I can choose, but I cannot e.g. go to a directory and type in the name of a new file.

**Comment by chriskiehl** [comment]
You're looking for the `FileSaver` widget. That'll allow you to specify a file that doesn't yet exist
