### ISSUE TITLE
Listbox widget does not work if used inside a group

### ISSUE THREAD

**Issue by aatwork** [chriskiehl/Gooey#224]
Hello!

using the latest version 0.9.5, I think I have encountered a new bug with the new Listbox feature.

`from gooey import Gooey, GooeyParser

@Gooey
def main():
    parser = GooeyParser()
    parser.add_argument('--works_main',
                        choices=["a", "b"],
                        nargs="*",
                        widget='Listbox')

    group = parser.add_argument_group('a name')

    group.add_argument('--works',
                       choices=["a", "b"],
                       nargs='*',
                       )
    group.add_argument('--does_not_work',
                       choices=["a", "b"],
                       nargs='*',
                       widget='Listbox'
                       )

    return parser.parse_args()

if __name__ == '__main__':
    main()
`

error message:

>   File "C:\Python27\lib\argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'widget'

**Comment by chriskiehl** [comment]
Oh, hrm.. that actually looks like it's been a bug since the very beginning 😱. While there was a Gooey wrapper for `MutuallyExclusiveGroup`s, I didn't have one for the basic `ArgumentGroup` type. 

Fixed in 8cc6d1d

Latest build is now on PyPi
