### ISSUE TITLE
how to make running log output immediately?

### ISSUE THREAD

**Issue by etiaxie** [chriskiehl/Gooey#225]
the tool run a long time before I can see the long output, it seems like the log reach a buffer limit and the will output the log. I wonder to know how to set can make the log output immediately

**Comment by chriskiehl** [comment]
Sounds like Python is running in buffered mode. Try starting with the `-u` flag or append the following at the start of your script. 

```
nonbuffered_stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
sys.stdout = nonbuffered_stdout
```
