### ISSUE TITLE
Modifying the size of the ListBox

### ISSUE THREAD

**Issue by JauntyJJS** [chriskiehl/Gooey#226]
Is there a way to change the size of the ListBox in parser.add_argument after choosing widget="ListBox" ?

Currently to change the size, I have to go to the widget_pack.py in the widget folder and change the size parameters at line 190 -194
` 
    self.widget = wx.ListBox(
      parent=parent,
      choices=choices,
      size=(Mychoice,My choice),
      style=wx.LB_MULTIPLE
    )

**Comment by chriskiehl** [comment]
Merging with issue https://github.com/chriskiehl/Gooey/issues/164
