### ISSUE TITLE
FileChooser does not allow to save a file

### ISSUE THREAD

**Issue by leo-recover** [chriskiehl/Gooey#227]
I'm not sure this is an issue. My script accepts an argument which is a path to a file to be generated. I'd like to use a widget like FileChooser to select the path and name of the file to be created. It seems like there is no way to it now, apart from writing there the full path by hand.

**Comment by chriskiehl** [comment]
Checkout the FileSaver widget. That'll let you specify a file path that doesn't yet exist on the system.

**Comment by leo-recover** [comment]
Perfect!! Thanks 😉

**Comment by dawnlh** [comment]
Can gooey use the default parameter specified in parser augment as the default file saving name? It will be convenient.

<img width="2113" height="852" alt="Image" src="https://github.com/user-attachments/assets/047da4df-66cf-4ebb-918f-bd481190068d" />
