### ISSUE TITLE
Listbox in subparser freezes GUI

### ISSUE THREAD

**Issue by agentr13** [chriskiehl/Gooey#229]
### **System Info:**
Mac OS X Sierra
Python 3.5.2
Gooey 0.9.5.2
wxWidgets 4.0.0b1

### **Issue:**
If a subparser contains a Listbox argument, once you click on the action for that subparser, attempting to go to another Action/Subparser freezes the interface. If the Listbox is on the first subparser/action, then you simply can't leave it. 

Here's an example parser that exhibits the behavior:
```from gooey import Gooey, GooeyParser

@Gooey
def parser():
    core_parser = GooeyParser()
    subs = core_parser.add_subparsers(help='commands', dest='command')

    sub1 = subs.add_parser('sub1', help='sub1 parser')
    sub1.add_argument('Sub1 Arg1', type=str, help='Sub1 Arg1')


    sub2 = subs.add_parser('sub2', help='sub2 parser')
    sub2.add_argument('My Listbox', choices=['Choice 1', 'Choice 2', 'Choice 3'], nargs='+', widget="Listbox")

    core_parser.parse_args()


if __name__ == '__main__':
    parser()
```

And here's a GIF of what's happening in action:
![gooey_error](https://user-images.githubusercontent.com/6316648/32630270-aeac8be0-c561-11e7-880c-414e6ff27eeb.gif)

Notice how the GUI stays fully responsive while interacting with the widgets within the subparser. It's only once you try to switch to a different Action that it freezes.

**Comment by chriskiehl** [comment]
Fixed!

`pip install -U gooey` to grab the latest code! ^_^
