### ISSUE TITLE
after pyinstaller to an exe tool, always pop up a cmd window when double-click the tool

### ISSUE THREAD

**Issue by etiaxie** [chriskiehl/Gooey#235]
how can make the tool not to show the cmd-line window
my pyinstaller cmd is “pyinstaller -F xxx.spec”

**Comment by etiaxie** [comment]
my spec:
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

options = [('u', None, 'OPTION'), ('u', None, 'OPTION'), ('u', None, 'OPTION')]

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          options,
          gooey_languages, # Add them in to collected files
          gooey_images, # Same here.
          name='main_actions_cloud2',
          debug=False,
          strip=None,
          upx=True,
          windowed=True,
          icon=os.path.join(gooey_root, 'images', 'lugi.ico'))

**Comment by xavierskip** [comment]
`pyinstaller -F -w xxx.py`
 or change your xxx.spec
`windowed=True` < `console=False`

**Comment by etiaxie** [comment]
i changed windowed=True to console=False and build again,the exe will raise error when run it

**Comment by xavierskip** [comment]
do you watch any error or warning in the  console?
otherwise you can try turn upx=False.

**Comment by chriskiehl** [comment]
Closing. There's an open Pyinstaller issue (#58) with tons of details. I'd move any discussion to that topic

**Comment by yashinshekh** [comment]
use --noconsole
