### ISSUE TITLE
Does wxPython supports installation via pip (for python 2.7) now?

### ISSUE THREAD

**Issue by crowjdh** [chriskiehl/Gooey#242]
I don't like installing dependencies into my computer, so I always install them into virtualenv.

So I tried to install Gooey inside virtualenv (using framework python 2.7) like below and it shows proper window. Does this means that wxPython now supports python 2.7?

```bash
$ PATH_TO_STANDALONE_VENV/virtualenv.py venv
$ source venv/bin/activate
(venv)$ pip install gooey
...
(venv)$ vim app.py
```
```python
import argparse
from gooey import Gooey, GooeyParser

@Gooey()
def main():
  parser = GooeyParser(description='Process some integers.')

  parser.add_argument(
    'required_field',
    metavar='Some Field',
    help='Enter some text!')

  parser.add_argument(
    '-f', '--foo',
    metavar='Some Flag',
    action='store_true',
    help='I turn things on and off')

  args = parser.parse_args()
  print 'Hooray!'

if __name__ == '__main__':
  main()
```

```vim
:wq
```
```bash
(venv)$ PATH_TO_FRAMEWORK_PYTHON2.7/python app.py
```

I'm not sure if it's just my computer or not.(I'm using MacOS 10.13.2)
If there's anyone who can confirm this, **removing this section in README.md would make things clear**.
> NOTE: Python 2 users must manually install WxPython! Unfortunately, this cannot be done as part of the pip installation and should be manually downloaded from the wxPython website.

**Comment by chriskiehl** [comment]
It's tough to say. I'm actually surprised you were able to get it running inside of a virtualenv on OSX. I tired it awhile ago and couldn't get the dang thing to run -- something about needing access to the screen. I fiddled with it for awhile, but eventually gave up and installed globally so I could work on things. 

So, my answer: not currently sure. However, it's still wonky enough across the various python versions/platforms/setups that I'm not sure I should remove it from the README just yet. 

I'm trying to get some traction on [this wiki page](https://github.com/chriskiehl/Gooey/wiki/Troubleshooting-WxPython-Installation) though ^_^ If you felt like documenting your setup and anything special you needed to do to get it working, that'd be super neato of ya!

**Comment by crowjdh** [comment]
I'm not sure I've done any special workaround or not, but as far as I remember, I've done nothing special after reinstalling MacOS on my Mac while ago.

Is it ok for me to create wiki page for what I've done(with some disclaimer)? I'm kind of worried about putting (possibly wrong) information into wiki page.

**Comment by chriskiehl** [comment]
Gah, apparently I totally missed you last reply here. My apologies!

I'm going to go ahead and close this one. As of wxpython 4.0 installing into a virtualenv on both 2.7 and 3 is well supported.

**Comment by crowjdh** [comment]
Great news :)
