### ISSUE TITLE
Tests are tied directly to yer machine, ya dolt! 

### ISSUE THREAD

**Issue by chriskiehl** [chriskiehl/Gooey#247]
As pointed out by @bilderbuchi here: https://github.com/chriskiehl/Gooey/blob/b19fe8826dfae85c013506b4d49bbaee478e2006/gooey/tests/gooey_config__autostart.json#L11

**Comment by bilderbuchi** [comment]
Well, I wouldn't have put it like that. :-P

**Comment by chriskiehl** [comment]
Fixed in https://github.com/chriskiehl/Gooey/commit/8f91e53469cd8f180ae54d7a19e32015768ee75f
