### ISSUE TITLE
Start new row for widgets like checkboxes

### ISSUE THREAD

**Issue by rerwin21** [chriskiehl/Gooey#255]
I'd like to start a new row after 3 or 4 checkboxes, but it keeps adding to the same row (see screenshot). Is there an option to specify to accomplish this?

 - [ Windows] OS
 - [ 3.6] Python Version 
 - [1.0] Gooey Version 
 - [Check box widgets extend  window with now scroll bar. How do I insert a new line?] Thorough description of problem 
     - [ Ability to start a new row of checkboxes after, say 4 boxes] Expected Behavior 
     - [ Keeps adding new boxes to same row] Actual Behavior 

```
@Gooey(program_name="Create Report")
def parse_args():
    ''' Use GooeyParser to build up the arguments we will use in our script
        Save the arguments in a default json file so that we can retrieve them
         every time we run the script.
    '''
    
    
    gooey_options={'show_border': True,
                   'columns': 1-10 }

    parser = GooeyParser(description='Allocations Report')
    parser.add_argument('Data_directory',
                        metavar='Data folder',
                        action='store',
                        default=stored_args.get('data_directory'),
                        widget='DirChooser',
                        help="Source directory that contains Excel files")
    search_group = parser.add_argument_group("SQL Options",
                                             gooey_options=gooey_options)
    search_group.add_argument('up_down', 
                              metavar='Download or upload support table? ',
                              choices=['Download', 'Upload']) 
    tables = parser.add_argument_group('Supporting Tables',                                
                                       gooey_options=gooey_options)
    tables.add_argument('BESP',
                        metavar='BESP',
                        widget='CheckBox',
                        action='store_true')
    tables.add_argument('POB',
                        metavar='POB',
                        widget='CheckBox',
                        action='store_true')
    tables.add_argument('GL',
                        metavar='GL',
                        widget='CheckBox',
                        action='store_true')
    tables.add_argument('Distributor',
                        metavar='Distributor',
                        widget='CheckBox',
                        action='store_true')
    tables.add_argument('Prod_type',
                        metavar='Product Type',
                        widget='CheckBox',
                        action='store_true')
    tables.add_argument('Serviceprovider',
                        metavar='Serviceprovider',
                        widget='CheckBox',
                        action='store_true')
    args = parser.parse_args()
    return args
```

 - [ ] Screenshot: 
<img width="449" alt="gooey_layout" src="https://user-images.githubusercontent.com/4753200/36110466-87f0d748-0fd7-11e8-9add-05f3cfcb9fa3.PNG">
 

 

Thanks! ^_^

**Comment by chriskiehl** [comment]
Hey @rerwin21, 

Firstly, thanks for the detailed issue! 

The problem here is half on me, half on you ^_^ The `gooey_options` part of your code is passing a negative number into the `columns` section. 

```python 
@Gooey(program_name="Create Report")
def parse_args():
    ''' Use GooeyParser to build up the arguments we will use in our script
        Save the arguments in a default json file so that we can retrieve them
         every time we run the script.
    '''
    
    
    gooey_options={'show_border': True,
                   'columns': 1-10 }   # <------- This guy
```

That's evaluating to `1` _minus_ `10`, or `-9`. If you swap that to a positive number you'll be back in business. 

![image](https://user-images.githubusercontent.com/1408720/36131719-1621d36e-1028-11e8-908f-dd68a13c2532.png)

It's on my TODO to write some validation code that'll make `gooey_options` friendlier to use (e.g. throwing a helpful error if a negative number shows up in the `columns` field).

**Comment by chriskiehl** [comment]
BTW, I _think_ you'll need to change all of your `tables` arguments to the `--Thing` style, and then set `required=True` to get the behavior you seem to be after. As it current is, I think argparse will just barf unless you click every single checkbox. They're currently being treated as positional, and thus, it can't actually tell them apart.
