### ISSUE TITLE
Any way to create a link?

### ISSUE THREAD

**Issue by Zarxrax** [chriskiehl/Gooey#268]
I'm not sure if I'm overlooking some functionality here, but I need the user to select from a list of language codes, though it might not be obvious what each of those codes mean. Therefore, I need some way of communicating this to the user.

Is there some way that I can either:
- Add a description to dropdown list items?
- Add a link to a webpage that explains all of the language codes?
- Have a button or other widget that can open a link to a webpage?

**Comment by chriskiehl** [comment]
All argparse inputs take an optional `help` argument. 

e.g. 

```python
parser.add_argument("--languages", help="Choose the appropriate language code. checkout tinyurl.com/1234for more info")
```
The url won't behave like a hyperlink in the browser, but they'll be able to copy/paste it.
