### ISSUE TITLE
Stray debug print statement

### ISSUE THREAD

**Issue by chris1610** [chriskiehl/Gooey#282]
Hello There, Future Issue Creator! 

If you've found a bug, make sure to include the following:

 - [ ] OS
 - [ ] Python Version 
 - [1.0 ] Gooey Version 
 - [* ] Thorough description of problem 
     - [ ] Expected Behavior 
     - [ ] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 
In Gooey 1.0, I noticed that the actual command string keeps printing to the console. I did not see this in older version.

I think the culprit is a stray print statement - https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/containers/application.py#L103

If that print statement is meant to be there, then it would be nice to turn it off with a config option.

Thanks! ^_^

**Comment by chriskiehl** [comment]
Doh! Thanks for linking to the offending line. It has been removed! https://github.com/chriskiehl/Gooey/commit/9c774ad8d6641d451142e8c59171125f307838ae

1.0.2 release will include the change. 

Thanks!
