### ISSUE TITLE
[Question] Multiple Parsers?

### ISSUE THREAD

**Issue by manugarri** [chriskiehl/Gooey#287]
Hi, I was wondering if something like the following use case can be handled currently by Gooey.

I am looking to build a GUI with a file selector that allows a user to load a file (a csv), then based on the columns on that csv, i would like to add another argument *for each of the columns, depending on their data types*. So dropdowns if they are text, text input if they are numbers, etc.

Is that possible currently? AFAK dynamic updates wouldnt work,because they modify the input on one single parameter based on another, would that be correct?

Thanks for your help :)

**Comment by chriskiehl** [comment]
Howdy, 

Nah, that's not something Gooey can handle at the moment. It's an interesting idea (something I've wanted myself a few times), but not in scope for the project at the moment. : (
