### ISSUE TITLE
Extending a Gooey app

### ISSUE THREAD

**Issue by jni** [chriskiehl/Gooey#292]
I'm considering Gooey for a few upcoming projects. It's a great way to get up and running, but I'm wondering whether I will hit a wall when I want to e.g. add a preview window during processing, or allow processing in stages, or really anything else that requires actually fiddling with wx code. Is there a way to take the GUI created by Gooey and modify/extend it?

Thanks for a great project!

**Comment by chriskiehl** [comment]
Howdy! 

Hmm.. no. Not really. There isn't a super good jumping off point for taking what Gooey builds and running with it. The processing in stages thing (if you mean the next input depends on the previous output) could _prooobably_ be ham-fisted in with vanilla Gooey via the experimental [Dynamic Values](https://github.com/chriskiehl/gooey#using-dynamic-values) stuff. Or you could fork Gooey and use the entire _thing_ as a jumping off point, but then you'd be subject to my terrible code ^_^

**Comment by jni** [comment]
@chriskiehl that was a bit abrupt but fair enough! :joy: 

Rather than forking I think I might just pick and choose useful bits of it. Suppose I want to make a decorator to a function that generates a pop-up GUI to pass parameters to the function. Where do you recommend I start in your code base? I specifically like your two-column layout and the header banner. Here's my only attempt at a GUI prior to this:

https://jni.github.io/skan/gui.html

Gets the job done, but it's not a pretty as what you do. =)
