### ISSUE TITLE
Executable Fails to Run on Other Machines - Failed to Execute Script

### ISSUE THREAD

**Issue by DustyArmstrong** [chriskiehl/Gooey#295]
Hello, 

Firstly, love Gooey, it's really helped me create something worthwhile here. Just completed my project, everything ran great building out of Atom. Everything works as expected, with no issues at all. 

Unfortunately, using the tutorial for building the executable hasn't worked out. While the executable runs on my own machine where the project resides, trying to run it on any other machine fails with the error "failed to execute script". 

I used the provided "build.spec" file, and made the necessary changes to point it to my app. It ran with a lot of dll errors (I think these can be safely ignored based on my research). It runs fine on my machine when I run the executable. I did notice, within that build.spec file, there is this line: 

`pathex=['c:\\Python27\\Scripts']`

Should that be changed? 

Any help would be appreciated, having the standalone executable was a big reason why I invested a lot of time into the app. 

 - [Windows 10] OS
 - [3.6.5] Python Version 
 - [Latest commit 109f497] Gooey Version

**Comment by DustyArmstrong** [comment]
Hello again, 

I have now fixed the issue by following some further advice in some of the other threads, I must have missed it. 

My issue was resolved by changing the line "Console = False" to "Console = True" in the build.spec file. Further to this, the executable still failed, however looking at the output it showed the images directory was missing. For any future developers who find their exe fails, make sure the images directory is set properly, and that the image folder exists. 

This can now be closed.

**Comment by chriskiehl** [comment]
Hey @DustyArmstrong, glad you got it figured out! Packaging is a "thar be dragons" kind of topic, unfortunately. 

You'd be a hero to many if you documented your problem + fixes in the [wiki](https://github.com/chriskiehl/Gooey/wiki/Packaging-Gooey)! ^_^
