### ISSUE TITLE
UI glitch under Ubuntu 16.04

### ISSUE THREAD

**Issue by gsemet** [chriskiehl/Gooey#297]
Hello !

I have some glitch on Ubuntu 16.04 (Unity X11):
![gooey-glitch](https://user-images.githubusercontent.com/133498/41348790-14b9959e-6f0e-11e8-9d80-69fc7c35ef00.png)

Do you want what I can do to fix the button ? And maybe a slightly bigger scrollbar on the right?

Thanks

**Comment by chriskiehl** [comment]
Fixed via 62643ae
