### ISSUE TITLE
installed gooey 1.0.0 using pip3, file docopt_to_json.py is not python 3 compliant

### ISSUE THREAD

**Issue by shimpe** [chriskiehl/Gooey#298]
in C:\Python36\Lib\site-packages\gooey\python_bindings\docopt_to_json.py, the main function contains a 

> print a

statement, which throws a syntax error.

**Comment by chriskiehl** [comment]
Whoop -- thanks for pointing that out! That was a totally old, unused file. It's been removed here: https://github.com/chriskiehl/Gooey/commit/53fd007bd9babe3ab310805afe1c23e4d9d6ea59 

This'll be part of the next release.
