### ISSUE TITLE
Pillow 4.3.0 requirement

### ISSUE THREAD

**Issue by KnutZuidema** [chriskiehl/Gooey#300]
Hello,

this is not exactly a bug, but Gooey has a requirement for pillow==4.3.0.
I was wondering if this is necessary, since I would like to use a newer version of pillow.

**Comment by bilderbuchi** [comment]
this has already been fixed in master (#244), but I don't think a new release has been published yet.

**Comment by KnutZuidema** [comment]
Oh, I didn't check for that. I'll just try to install it from the repo then. Thanks. 




On Wed, Jun 27, 2018 at 3:48 PM +0200, "Christoph Buchner" <notifications@github.com> wrote:












this has already been fixed in master (#244), but I don't think a new release has been published yet.
