### ISSUE TITLE
No program name in taskbar

### ISSUE THREAD

**Issue by mathieucht** [chriskiehl/Gooey#303]
Hello there,

Since I updated my Gooey version, I can no longer see the program's name at the top of the window and in the taskbar:

![image](https://user-images.githubusercontent.com/39558435/42091858-384ce880-7ba7-11e8-9499-e6b19e42f449.png)

![image](https://user-images.githubusercontent.com/39558435/42091878-4b6d263c-7ba7-11e8-8dec-91990580896d.png)

I use Python 2.7.14 (64 Bit) on Windows 10 with the latest Gooey (1.0.0). 

Thanks in advance for the help!

**Comment by aatwork** [comment]
any update regarding this issue?

**Comment by chriskiehl** [comment]
The has been fixed here: https://github.com/chriskiehl/Gooey/commit/451ec748a29d963fbc7d75597a4ff7b4308d705a 

Will be in next release. 

Thanks for the detailed report!
