### ISSUE TITLE
flyover or hover enhancement

### ISSUE THREAD

**Issue by PyOctoCat** [chriskiehl/Gooey#306]
No issues to report yet. I would like to see two options. 1) Have option to have default be no gooey unless option is provided, but this looks like it's being worked on.

2) Would be to add a description field that could provide more context in a flyover the field. Still pretty new to Python, any tips on how to get started with this if no one else is working on it?

-David

**Comment by chriskiehl** [comment]
No plans to implement this baring a sudden surge in interest.
