### ISSUE TITLE
allow tuples as choices

### ISSUE THREAD

**Issue by sanzoghenzo** [chriskiehl/Gooey#312]
If I have a tuple in the "choices" argument of an ArgumentParser argument, Python throws this:
```
    ...
    choices=[default] + self._meta['choices'],
TypeError: can only concatenate list (not "tuple") to list
```

[this is the affected line of code](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/components/widgets/dropdown.py#L16), changing it to `... + list(self.meta['choices'])` should be enough.
 
BTW, Thanks for this great project!

**Comment by chriskiehl** [comment]
Fixed! Thanks for linking to the exact spot where things were breaking. 

FYI, I ended up patching a little upstream of that location. This was, at its core, a bug in my jsonification stuff which allowed the unexpected tuple type to flow that deeply into the system.  

Anyway, you can check it out on this branch https://github.com/chriskiehl/Gooey/commit/edf96bfe619b36b376535aed0c758ddeba5a613f

I'll merge it into mainline shortly.
