### ISSUE TITLE
Optional Restart Button Upon Completion

### ISSUE THREAD

**Issue by WillAyd** [chriskiehl/Gooey#313]
Going back to #20 the complete execution of a program always lists a restart button, but there are a lot of applications I build where it is highly unlikely the user would want to perform the exact same action again.

Ideally it would be nice to make this optional. Looking through the code I didn't jump out to me where this should go. It could be another argument to the decorator that dictates what gets output from `showComplete`, though there may be more effective ways of going about this

**Comment by chriskiehl** [comment]
Nice idea! 

This has been implemented here: https://github.com/chriskiehl/Gooey/commit/2b1d5f453c9db37541835e3a96e2980d7fa93824 

It'll be in the next release. 

Thanks!

**Comment by WillAyd** [comment]
Very cool - thanks @chriskiehl
