### ISSUE TITLE
README has links to anchor Showing Progress, but it's not there....

### ISSUE THREAD

**Issue by furicle** [chriskiehl/Gooey#314]
The README mentions in several places a 'Showing Progress' section on how to update the progress bar, but that section is not in the current document.

**Comment by furicle** [comment]
`git log -S'Showing Progress'` seems to show that anchor was added in January, but the content was never created.

**Comment by furicle** [comment]
Oh wait - I see   
   [ ] progress bar management
in the TODO file.  So I guess this is a known issue.

**Comment by chriskiehl** [comment]
Whoop -- progress bars have actually been a part of Gooey for a long time, but there's been a documentation gap. 

I've updated the README fill out that linked section. Check it out: https://github.com/chriskiehl/Gooey#showing-progress
