### ISSUE TITLE
`action=count` is order dependent in Gooey, but the shell alone script is not. 

### ISSUE THREAD

**Issue by Magnati** [chriskiehl/Gooey#316]
- OS: Ubtuntu Bionic Beaver
 - Python Version: 3.6
 - Gooey Version: 1.0.0  
 
The argument.parameter `action=count` is in Gooey order dependent, but the shell alone script is not. 

That means for the rather genuine argument `verbosity` which is often set with a certain amount of `v` the order `"-v, "--verbose"` would work for `add_argument` in Gooey, while `"--verbose", "-v" `does not!

In the shell alone script the order is arbitrary, and Gooey should work in both orders too, am I right?  

Here is an example code. Just start the script with an arbitrary parameter to execute the error throwing version (`python test.py e`) or without to try the working version (`python test.py`).

```python
import sys
from gooey import Gooey, GooeyParser
from message import display_message

def get_arguments(parser):
	parser.add_argument(
		"-v",
		"--verbose",
		dest="verbosity",
		action="count",
		default=3,
		help="set verbose output; raise verbosity level with -vv, -vvv, -vvvv from lv 1-3",
	)
	return parser

def get_arguments_error(parser):
	parser.add_argument(
		"--verbose",
		"-v",
		dest="verbosity",
		action="count",
		default=3,
		help="set verbose output; raise verbosity level with -vv, -vvv, -vvvv from lv 1-3",
	)
	return parser

@Gooey(program_name="Order Error Count Demo")
def main():
	desc = "Example application to show that Gooey abbility" \
	 	+ " to handle the action 'count'\nis dependent on the order" \
		+ " of '-' and '--' argument."
	parser = GooeyParser(description = desc)
	if len(sys.argv) > 1:
		parser = get_arguments_error(parser)
	else:
		parser = get_arguments(parser)

	args = parser.parse_args()

if __name__ == '__main__':
	print("Just start the script with an arbitrary parameter "\
		+ "to execute the error throwing version.")
	main()
```

**Comment by chriskiehl** [comment]
Fixed! 

Thanks for the detailed and runnable example! 

It'll be part of the next release. In the meantime, you can access the fix here if ya want: https://github.com/chriskiehl/Gooey/commit/d37508da77a24b2a876436fc33cf767a56d17ce5

**Comment by Magnati** [comment]
Great to hear!
