### ISSUE TITLE
Gooey not importnig

### ISSUE THREAD

**Issue by TristanRollond** [chriskiehl/Gooey#318]
- Windows 10
 - 3.6.3
 - ??
 - I have supposedly added gooey, after having added it through CMD
     - For gooey to import
     - Error: Traceback (most recent call last):
  File "C:/Users/180099/Documents/Raspberry PI Club/Python/Code Examples/Gooey.py", line 2, in <module>
    import Gooey
  File "C:/Users/180099/Documents/Raspberry PI Club/Python/Code Examples\Gooey.py", line 4, in <module>
    @Gooey      #<--- all it takes! :)
TypeError: 'module' object is not callable
 - from gooey import Gooey
@Gooey
 - If you notice the capitalization in the error, that was just a test, sorry 

Thanks! ^_^

**Comment by chriskiehl** [comment]
I'm not totally sure if this is a question, issue, or just talking about a typo you had 😕 

Closing, as there doesn't seem to be anything actionable, but feel free to re-open with additional details!
