### ISSUE TITLE
Tree module (packaging gooey with pyinstaller)

### ISSUE THREAD

**Issue by ChrisVolz** [chriskiehl/Gooey#319]
Hello,

I have a simple question regarding packaging gooey with pyinstaller.

In the presented example the data structure "Tree(,prefix)" is used. In which python module do I find this Tree-module?

Best regards
Chris

**Comment by ChrisVolz** [comment]
Sorry for the commet. I noticed that the "Tree" class is part of the pyinstaller. Everything ok, please close or delete this issue ;)

**Comment by chriskiehl** [comment]
Glad you figured it out. Closing  : )
