### ISSUE TITLE
"TypeError: ComboBox()" with integer choices

### ISSUE THREAD

**Issue by Aikhjarto** [chriskiehl/Gooey#321]
If a parameter for selecting integer numbers (works well with argparse) is used, gooey crashes with a TypeError:
```
TypeError: ComboBox(): arguments did not match any overloaded call:
  overload 1: 'parent' is not a valid keyword argument
  overload 2: argument 'choices' has unexpected type 'list'
```

 -  OS: Windows 10
 -  Python Version 3.6.5
 -  Gooey Version: 1.0.2 as well as current master branch
 
### Minimal Crashing Example
```python
import gooey

@gooey.Gooey
def main():
    parser=gooey.GooeyParser()
    parser.add_argument('--test', default=0, type=int, choices=[0,1,2,3,4])
    args=parser.parse_args()
    print(args)
    
if __name__=='__main__':
    main()
```

**Comment by chriskiehl** [comment]
Huh, weird. I guess I never realized `wx.ComboBox` only accepted strings. 

Thanks for the report and the code sample! It's been fixed here: https://github.com/chriskiehl/Gooey/commit/f109f397af5a3e4d5ef4450f27632fba36949192 

It'll be part of the next release!

**Comment by Aikhjarto** [comment]
Your fix does not entirely work.
If the default value is not zero, the following error occurs:
```
  File "(...long_path...)\gooey\gui\components\widgets\dropdown.
py", line 29, in setValue
    index = self._meta['choices'].index(value) + 1
ValueError: 1 is not in list
```
