### ISSUE TITLE
wxpython >=4.0.2 NewId depricated

### ISSUE THREAD

**Issue by eskemojoe007** [chriskiehl/Gooey#323]
Hello There, Future Issue Creator! 

If you've found a bug, make sure to include the following:

 - [Windows 10 64 Bit] OS
 - [ 3.6.5] Python Version 
 - [ 1.0.1] Gooey Version 
 - `requirements.txt` states that any `wxpython` beyond `4.0.0b1` is acceptable, but wxpython `4.0.2` depricated `wx.NewID()` which is used in many places.  I get many deprectation warnings when running in `4.0.3` or `4.0.2`:

```
C:\Users\user\.virtualenvs\dialer_database-fp33vZHS\lib\site-packages\gooey\gui\events.py:14: DeprecationWarning: NewId() is deprecated
  WINDOW_RESTART  = wx.NewId()

C:\Users\user\.virtualenvs\dialer_database-fp33vZHS\lib\site-packages\gooey\gui\events.py:15: DeprecationWarning: NewId() is deprecated
  WINDOW_EDIT     = wx.NewId()

C:\Users\user\.virtualenvs\dialer_database-fp33vZHS\lib\site-packages\gooey\gui\events.py:17: DeprecationWarning: NewId() is deprecated
  WINDOW_CHANGE   = wx.NewId()
```

Either requirements.txt needs to be locked down or all references to `wx.NewId()` need to be replaced with `wx.NewIdRef()`.  https://groups.google.com/forum/#!topic/wxpython-users/r7Q5pFge2KE

**Comment by chriskiehl** [comment]
Resolved by https://github.com/chriskiehl/Gooey/pull/324
