### ISSUE TITLE
Cant Delete argument text using backspace or Del or anything.

### ISSUE THREAD

**Issue by tamjid10** [chriskiehl/Gooey#327]
Hello There, Future Issue Creator! 

If you've found a bug, make sure to include the following:

 - [ linux mint 19] OS
 - [ 3.6 ] Python Version 
 - [ latest] Gooey Version 
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior : i should be able to delete the text in the arguments text bar  using back space.
     - [ ] Actual Behavior : but i cant delete any text using backspace.
 -

 - [ ] Screenshot (if visual quirk) 

![screenshot from 2018-09-27 12-04-02](https://user-images.githubusercontent.com/25399804/46126202-1e83ec80-c24e-11e8-99e3-1e24de40a200.png)

 - [ ] Anything else you may think will be helpful 

Thanks! ^_^

**Comment by chriskiehl** [comment]
Please fill out the issue template in its entirety. Code sample is missing.
