### ISSUE TITLE
Some Feature Request

### ISSUE THREAD

**Issue by joylin1984** [chriskiehl/Gooey#330]
## Some Feature Request：
*  Widget : FileChooser/MultiFileChooser/FileSaver Add filter, e.g. `'*.xlsx, ; *.txt'`.
*  parser.add_subparsers  :  Add an alias，like `dest` in `add_argument`. This parameter is displayed by default in GUI. Useful for non-English GUIs.
*  Custom font in GUI ：For  parser.name/parser.help font in GUI.The default font is sometimes unattractive for non-English gui.
* ABOUT Dialog : Add `about` button in the lower left of the main window. In ABOUT dialog can contain pictures and text objects.

**Comment by chriskiehl** [comment]
Re: About - About Dialogs have been added and will be in the 1.0.2 release! 
Re: Subparser Alias - `parser.add_parser` takes a `prog` argument and will display it instead of the default text if it is present. e.g. `add_parser('curl', prog='Curl is a tool to transfer data to or from a server')`. Is that what you're after 

I dig your other ideas. They're on the list!

**Comment by joylin1984** [comment]
> Re: About - About Dialogs have been added and will be in the 1.0.2 release!
> Re: Subparser Alias - `parser.add_parser` takes a `prog` argument and will display it instead of the default text if it is present. e.g. `add_parser('curl', prog='Curl is a tool to transfer data to or from a server')`. Is that what you're after?
> 
> I dig your other ideas. They're on the list!

Thanks ！
Subparser Alias - In fact, I just want to customize Tab Name or Actions Name in GUI.

![2018-10-21_124232](https://user-images.githubusercontent.com/13713368/47263234-e1023e80-d52f-11e8-9de7-8690b7af5716.png)
![2018-10-21_124328](https://user-images.githubusercontent.com/13713368/47263235-e1023e80-d52f-11e8-9665-9e7b6270920f.png)

**Comment by chriskiehl** [comment]
Yep, you can do that currently with the `prog` argument. 

```
curl_parser = subs.add_parser('curl', prog="カール", help='curl is a tool to transfer data from or to a server')
```

![image](https://user-images.githubusercontent.com/1408720/49682184-ad8a5d80-fa64-11e8-9b61-064b096a44dc.png)

**Comment by chriskiehl** [comment]
Closing this an opening the remaining task under a new issue so it can be better tracked.
