### ISSUE TITLE
Feature Request : Work With tqdm

### ISSUE THREAD

**Issue by 3dp** [chriskiehl/Gooey#333]
I'm struggling to get Gooey to output tqdm in a nice, neat way.  I can hack it so each update spits out a new line.  The Gooey Progress bar is too limiting for what I'm doing (and doesn't work with tqdm).

**Comment by chriskiehl** [comment]
I don't know what that is.

**Comment by fake-name** [comment]
TQDM is a very handy cli progress bar library: https://pypi.org/project/tqdm/

Principally, it does a number of neat things: 

- Nested progress bars
- Decent time remaining estimates
- Refresh rate limiting
- Various stateful (xxx of yyy progress), and stateless (activity/pulse mode)

I think the most interesting feature here would be supporting nested progress bars. I quite often have CLI tooling that gets broken into a large list of tasks, each with a sub-task. TQDM lets you draw multiple progress bars, which works really well for this sort of task (think processing a directory of files. You have the overall progress by number of files, and the actual progress within each file).

I'd suspect that you'd have to integrate with a specific progress bar library to support all the options they provide.
