### ISSUE TITLE
Listbox How-To?

### ISSUE THREAD

**Issue by 3dp** [chriskiehl/Gooey#334]
I'm trying to get Listbox to work.  I expected a list/dictionary of the multiple values in the list box.  Instead, I'm getting
`error: unrecognized arguments: "item1" "item2" "item3"`

Gooey 1.0.1

**Comment by chriskiehl** [comment]
Please fill out the issue template : )

**Comment by 3dp** [comment]
Figured it out (which is usually what happens - I post something up, then figure it out).

The resolution is to include `nargs='*'`.  Works perfectly.
