### ISSUE TITLE
Tags missing in github repo

### ISSUE THREAD

**Issue by htgoebel** [chriskiehl/Gooey#335]
Hi,

the github repository does not contain any tags from release versions. This makes it very hard to e.g. vew differences between releases.

Please add the tags, even if  the date would be "incorrect". See
https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git. If yo like, you could back-date the ags setting `GIT_COMMITTER_DATE`, see https://stackoverflow.com/questions/21738647

Thanks.

**Comment by chriskiehl** [comment]
howdy @htgoebel,

Yeah, this is a good call out. I've historically been pretty fast-and-loose with the management of this project. Its popularity, and the responsibility that comes with it, has taken awhile to sink in. 

Moving forward, there will be full official releases, changelogs, and feature overviews!
