### ISSUE TITLE
terminal_font_family

### ISSUE THREAD

**Issue by ctholho** [chriskiehl/Gooey#338]
I have trouble properly using terminal_font_family.

I would like to specify 'monospace' but all I seem to be able is to specify a font name like Menlo etc. Whenever I give the argument 'serif' or 'monospace' Gooey falls back to the standard font.

Is this an OS problem or am I being stupid?

macos 10.13.6
Python version: 3.6
Gooey Version: 1.0.1

**Comment by chriskiehl** [comment]
You can specify a monospaced font-family like "Courier New". 

```
@Gooey(terminal_font_family='Courier New')
```

If you don't know which OSX monospace font to use, there's an older legacy option called `monospace_display`

```
@Gooey(monospace_display=True)
```

That'll have the UX Library use whatever default monospaced font it has.
