### ISSUE TITLE
Checkbox element not hiding textbox field

### ISSUE THREAD

**Issue by f-tonini** [chriskiehl/Gooey#340]
Hello,

I am working on a Windows 10 machine with python 3.6.x, Gooey version 1.0.1. 
I defined a basic GUI and I cannot seem to be able to use the checkbox element to work along with a textbox field (widget type DirChooser) in order to make it greyed-out/hidden when checkbox is equal to False. Is this expected behavior or there is a way in Gooey to hide/show a given field when a checkbox is True/False?

```
@Gooey(dump_build_config=True, 
       program_name="AccuSim", 
       image_dir="./img",
       default_size=(715, 550)
       )
def main():
    desc = "AccuSim is a convenient, freely-available GUI-based tool designed to facilitate and automate the validation of\nsimulated land-change models. Fore more information, see the README file that accompanies this tool."
    parser = GooeyParser(description=desc)

    parser.add_argument(
        "Baseline", 
        help="Help", 
        widget="FileChooser"
    )
    parser.add_argument(
        "Comparison", 
        help="Help",
        widget="FileChooser"
    )

    parser.add_argument("Output_Folder", help="Select a folder where you want to save your output metrics files", widget="DirChooser")
    
    fragstats_group = parser.add_argument_group(
        "FRAGSTATS (for Windows users ONLY)",
        gooey_options={
            'show_border': False,
            'columns': 2 
        }
    )

    fragstats_group.add_argument(
        "--Calculate metrics", 
        default=False,
        action="store_true",
        help="Check the box"
    )
    
    fragstats_group.add_argument(
        "--Executable_File_Location",
        widget="DirChooser",
        help="Select the folder of the FRAGSTATS executable (.exe) file"
    )

    args = parser.parse_args()
```

Attached is a screenshot of the GUI with markers to point to the described issue above.

![1](https://user-images.githubusercontent.com/1470540/47312420-4f1b3400-d60a-11e8-9dde-d0913d90d05e.png)

**Comment by chriskiehl** [comment]
There is no notion of dependent widgets. However, you could get pretty close to what you're after (items greyed out until clicked) by using an optional mutually exclusive group, but with a single option .

```
my_cool_parser = GooeyParser(description=desc)
verbosity = my_cool_parser.add_mutually_exclusive_group()
verbosity.add_argument('--executable-file-location', help='Select the folder of the FRAG', widget='FileChooser')
```

That'll have the effect of their being a radio button with a greyed out option inside of it. Once you click the radio group, it'll make the form field active.

**Comment by f-tonini** [comment]
Thanks Chris, this should work. How would I then handle the presence of a value for that greyed out parameter in my code? Is it just a simple IF check to see if the "executable-file-location" parameter is empty or not?

**Comment by f-tonini** [comment]
Also, the mutually exclusive group comes out with the default "choose_one" title but cannot find any instructions/examples on how to customize that header name. Is there a par needed or this cannot be altered?
