### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by diimdeep** [chriskiehl/Gooey#341]
- Windows 10
 - Python 3.7.1
 - Gooey==1.0.1
 - Thorough description of problem 
     - Expected Behavior - import Gooey
     - Actual Behavior - import error!

```
python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gooey import Gooey, GooeyParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\gooey\__init__.py", line 2, in <module>
    from gooey.python_bindings.gooey_decorator import Gooey
  File "C:\Python37\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 14, in <module>
    from gooey.gui import application
  File "C:\Python37\lib\site-packages\gooey\gui\application.py", line 5, in <module>
    import wx
  File "C:\Python37\lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Python37\lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed: The specified module could not be found.
```

update:
works with Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by PeterKucirek** [comment]
I've also found the same problem when attempting to run a script in Python 3.7, as part of a Conda environment, on Windows 7. I get a problem with the Intel MKL library, but the general issue is the same. It seems like there is an issue with the `PATH` variable not being set properly, or being modified during installation.

Downgrading to Python 3.6 was the solution that worked for me.

**Comment by chriskiehl** [comment]
Closing as there's no action to take on my end. 

3.7 seems to be an overall [buggy release](https://github.com/chriskiehl/Gooey/issues/342) O_o
