### ISSUE TITLE
Gooey does not work with Python 3.7 on Windows

### ISSUE THREAD

**Issue by diimdeep** [chriskiehl/Gooey#342]
- Windows 10 (Parallels)
 - Python 3.6.7
 - Gooey==1.0.1
 - After Start button host process executes script, child process finishes and dies, but host GUI do not respond in any way, host UI showing like child process still running infinitely.
     - Expected Behavior - show print statements from child process, update UI about finished process.
     - Actual Behavior - nothing is updated, nothing displayed, as if child process still running.
- Also this incorrect behaviour appears with any program from examples.

In macOS 10.14 works as expected.

Here is screenshot showing GUI without updates, on left you can see that child process(in red) died.

<img width="1233" alt="screenshot 2018-10-30 at 00 30 42" src="https://user-images.githubusercontent.com/485713/47681664-23d0b000-dbdb-11e8-8179-5a38a70502fc.png">

**Comment by chriskiehl** [comment]
Parallels, huh? Hmm.. 

Couple of questions:  

* Is this after packaging, or when running from code? 
* could you provide a minimal example?
* Could you checkout the [1.0.2 branch](https://github.com/chriskiehl/Gooey/tree/1.0.2-release) and try running with the `requires_shell` decorator argument with True/False? 
* do you see any error messaging at all?

**Comment by diimdeep** [comment]
- from code
- GooeyExamples\examples\example_progress_bar_1.py
- same
- no errors

**Comment by LeoFCardoso** [comment]
Same here. Running from code (downloaded with PIP).
requires_shell True / False lead to same results. No errors at all... :(
Python 3.7.1
Windows 10 (Microsoft Windows [version 10.0.17134.228])

**Comment by chriskiehl** [comment]
@LeoFCardoso You're also running under Parallels? 

Does the subprocess actually die in all cases, or does it just not produce output? 

If you guys modify https://github.com/chriskiehl/Gooey/blob/109f4972b2c21c55f66b3433526d988f70dc86bd/gooey/gui/cli.py to log the command, and then run that command manually, does the process behave as expected? 

Another deep-down-in-the-weeds debugging step would be to drop a breakpoint at this line: 

https://github.com/chriskiehl/Gooey/blob/109f4972b2c21c55f66b3433526d988f70dc86bd/gooey/gui/processor.py#L46

and see what the process is actually doing or if it sends any message before crapping out.

**Comment by LeoFCardoso** [comment]
Hello @chriskiehl .
I'm not using Parallels.
As stated in the bug report, the external process run correctly.

I tried your suggestion for debug. There is a try/except block. In normal execution, there is an exception (argument of type 'int' is not iterable), and

"self._process = subprocess.Popen(
                command,
                bufsize=1, stdout=subprocess.PIPE, stdin=subprocess.PIPE,
                stderr=subprocess.STDOUT, shell=True, env=env)"

is executed...

**Comment by chriskiehl** [comment]
Ah, ok, so, I didn't realize the Python world was steadily moving forward. I was still on 3.6. Once I installed 3.7 I was able to reproduce the issue.

Interestingly, it seems to be caused by the multiprocessing.dummy library when running under 3.7, but I haven't quite pinned down _why_. Whenever it tries to finish executing the worker, it calls `get()` on a blocking queue with nothing in it, and then hangs there forever. 

Seems like a bit of a bug in Python itself, tbh. 

A work around seems to be to just use a Thread directly rather than the current pool api. I need to tests it a bit more, but will update shortly.

**Comment by LeoFCardoso** [comment]
I can confirm the bug in Windows 8 also.

**Comment by chriskiehl** [comment]
@diimdeep @LeoFCardoso 

Could you guys install [this branch](https://github.com/chriskiehl/Gooey/tree/1.0.1-hotfix) and let me know if it resolves both of your issues? 

```
pip install git+https://github.com/chriskiehl/Gooey@1.0.1-hotfix
```

**Comment by LeoFCardoso** [comment]
@chriskiehl patch works fine in Windows and Mac. Thanks!

**Comment by chriskiehl** [comment]
Master has been updated. You can now grab the Python 3.7 compatible version on pip. 

Thanks for the report!
