### ISSUE TITLE
Gooey, pythonw.exe and Popen

### ISSUE THREAD

**Issue by 13MaxG** [chriskiehl/Gooey#355]
Hi. 

I'm operating on Windows 10, with Python 3.7.1 and Gooey-1.0.2.

When I run `pythonw main.py` and I start execution a program that usues Popen, the stdout of it's printed in a new console window.  On the contrary, `python main.py` gets the stdout printed nicely in Gooey logs widget. 

main.py:
```
import subprocess
import gooey 

@gooey.Gooey()
def main():
    parser = gooey.GooeyParser()
    args = parser.parse_args()    

    process = subprocess.Popen(["ping", "127.0.0.1", "-n", "5", ])
    process.wait()
    if process.returncode != 0:
        print("An error occurred :", process.returncode)
        exit(1)               

if __name__ == '__main__':
    main()
```

`pythonw main.py`:
![obraz](https://user-images.githubusercontent.com/875386/48982129-77e98a00-f0de-11e8-9c46-23a60bbc121f.png)

`python main.py`:
![obraz](https://user-images.githubusercontent.com/875386/48982134-89cb2d00-f0de-11e8-8d64-f88607a821bb.png)

**Comment by chriskiehl** [comment]
This seems to be a quick of pythonw and Popen in general. Checkout this [StackOverflow issue](https://stackoverflow.com/questions/1813872/running-a-process-in-pythonw-with-popen-without-a-console)

If you take a dash of the suggestion above, and sprinkle on a little manual Subprocess piping as seen in [this issue](https://github.com/chriskiehl/Gooey/issues/495), you can get your Popen calls displaying in Gooey even under `pythonw`

Full example: 

```
import subprocess
import gooey 

@gooey.Gooey
def main():
    parser = gooey.GooeyParser()
    args = parser.parse_args()    

    startupinfo = subprocess.STARTUPINFO()
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
    process = subprocess.Popen(["ping", "127.0.0.1", "-n", "5", ], 
        startupinfo=startupinfo,
        stdout=subprocess.PIPE,
        stdin=subprocess.PIPE,
        stderr=subprocess.STDOUT)

    for line in process.stdout:
        print(line.decode('utf-8'))
    process.wait()
    if process.returncode != 0:
        print("An error occurred :", process.returncode)
        exit(1)               

if __name__ == '__main__':
    main()
```
