### ISSUE TITLE
Setup.py is missing Python 3 metadata

### ISSUE THREAD

**Issue by vpoulailleau** [chriskiehl/Gooey#359]
Gooey looks great, I really have to try that.

According to README, Gooey supports Python 3.

But according to
https://github.com/chriskiehl/Gooey/blob/abd69a9bae66c4f81e294742b32d53a76537c400/setup.py#L33-L41
only Python 2.6 and 2.7 are supported.

Is it possible to update setup.py (and PyPI) if Python 3 is officially supported? Or do you plan the end of the beta phase before any update?

**Comment by chriskiehl** [comment]
Python 3 is supported and where most development takes place these days. That's just a bit of metadata that's fallen out of date (thanks for pointing it out btw!). You can pip install Gooey from python 3.

**Comment by chriskiehl** [comment]
Resolved by https://github.com/chriskiehl/Gooey/commit/067d63fbc73cfeb56727e3a2ea50b1756b55ceb6
