### ISSUE TITLE
Wildcards in choosers

### ISSUE THREAD

**Issue by gonzygonz** [chriskiehl/Gooey#363]
Hi there,
I saw there is a TODO to add wildcards to choosers as they are not supported at the moment.
i assume this issue is known so i didnt add any example. 

I think i know how to implement this feature, so if no one is working at it at the moment ill go ahead and prepare a pull request (and also support message and defaultFile along the way)

Thanks! :>

**Comment by gonzygonz** [comment]
Hi,
I implemented wildcards support, and on the way also support for defaultFile, defaultFolder and message For choosers that support this.

I want to prepare a PR for this.
Based on which branch should i do it?

Thanks :>

**Comment by chriskiehl** [comment]
Can't wait to check it out! 1.0.3-release is the chap you should target.

**Comment by gonzygonz** [comment]
hi, is there anything still needed to accept the PR?

**Comment by chriskiehl** [comment]
Nope. Just needed to poke me ^_^ Nights and weekends are eaten up by other projects these days.. 

I'll try to get all the pending PRs merged/reviewed soon. I'll try to get to them all over the weekend. And, then, hopefully, _finally_, actually kick 1.0.3 out the door!

**Comment by gonzygonz** [comment]
Yea, i know the feeling.
Great job on this lib. Very useful for many small things i do. Keep up the good job
Cant wait to port to 1.0.3

**Comment by chriskiehl** [comment]
Closing. Completed by you! ^_^
