### ISSUE TITLE
Required non-positional fields show as optional

### ISSUE THREAD

**Issue by narfanar** [chriskiehl/Gooey#368]
- [x] OS: Windows 10 Build 1803
 - [x] Python Version : 3.7.1
 - [x] Gooey Version : 1.0.2
 - [x] Thorough description of problem 
     - [x] Expected Behavior: Required non-positional field fields show as required.
     - [x] Actual Behavior: Non-positional fields are always optional. No 'required' part is in the layout if there's no positional argument.
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 

![image](https://user-images.githubusercontent.com/5769148/51261503-0d0b4f80-19b9-11e9-8f78-2aaade501764.png)

^ Resized manually. Can confirm there's nothing hidden or cutoff by the resize.

```py
from gooey import Gooey, GooeyParser
import argparse

@Gooey
def main():
    cli = GooeyParser(description='Utils')
    cli.add_argument(
        '-i', '--in', required=True, metavar='PATH', dest='inpath'
    )
    cli.add_argument(
        '-o', '--out', required=True, metavar='PATH', dest='outpath'
    )
    args = cli.parse_args()

if __name__ == '__main__':
    main()
```
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
Gooey made argument groups a first class citizen and stopped naively merging your arguments into the default groups along the way. 

The good news: you can now have super complex layouts like this! 

![image](https://user-images.githubusercontent.com/1408720/51958197-a39d2f00-2403-11e9-8169-0489d8d008c0.png)

The 'bad' news: you'll have to explicitly add an group when you want to have optional, but required, arguments. 

The good news: its just an extra line

```python
from gooey import Gooey, GooeyParser
import argparse

@Gooey
def main():
    cli = GooeyParser(description='Utils')
    required_args = cli.add_argument_group("Required Arguments")  # <-- new line here! 
    required_args.add_argument(
        '-i', '--in', required=True, metavar='PATH', dest='inpath'
    )
    required_args.add_argument(
        '-o', '--out', required=True, metavar='PATH', dest='outpath'
    )
    args = cli.parse_args()

if __name__ == '__main__':
    main()
```

Moar good news: You can name the group anything you want! 

```
required_args = cli.add_argument_group("You gotta fill these out")
```

So this is a `wontfix`, as there are more powerful alternatives for grouping arguments. I generally try to always keep backwards compatibility, but the old style required argument "merging" no longer makes sense in light of argument groups.
