### ISSUE TITLE
show_failure_modal option

### ISSUE THREAD

**Issue by nelsonjchen** [chriskiehl/Gooey#370]
https://github.com/chriskiehl/Gooey/blob/109f4972b2c21c55f66b3433526d988f70dc86bd/gooey/gui/containers/application.py#L128

Could a `show_failure_modal` option be made like `show_success_modal`? I have a script that could use the failure GUI with the red failure icon quite often.

**Comment by chriskiehl** [comment]
Good idea! 

Implemented [here](https://github.com/chriskiehl/Gooey/commit/8281840171cb2073733cd81cc2242a36072be9b9). Will be part of the next release.
