### ISSUE TITLE
Not possible to have an argument of type int with default value of 0

### ISSUE THREAD

**Issue by dusans** [chriskiehl/Gooey#374]
- [Windows] OS
 - [2.7] Python Version 
 - [1.0.2] Gooey Version 

Expected Behavior: If we have an argument of type **int** and we set the value to **0** it will not be displayed in the gui

**Example**:
```
        group.add_argument(
            '--integer_argument',
            type=int,
            default=0)
```

**Reason**: 

gooey\gui\components\widgets\bases.py:
```
class TextContainer(BaseWidget):
    def __init__(self, parent, widgetInfo, *args, **kwargs):
```

The if statement is only 

`        if self._meta['default']:`

It should be

`        if self._meta['default'] is not None:`

**Comment by chriskiehl** [comment]
This is fixed in the [release branch](https://github.com/chriskiehl/Gooey/tree/1.0.3-release) which'll be released..... soon!
