### ISSUE TITLE
Gooey does not work on Lubuntu 16.10

### ISSUE THREAD

**Issue by sagiftw** [chriskiehl/Gooey#376]
Hi.
I'm trying to install Gooey. My OS is Lubuntu 16.10 (pretty much like Ubuntu).
My python version is 3.5.2-1. 

The problem is, when I'm trying to install Gooey, using:
`sudo -H pip3 install Gooey`

But it fails to install, and I'm getting the error message:
`Failed building wheel for psutil
Failed building wheel for wxpython
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-b761crcm/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1q7c_rn4/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-b761crcm/psutil/
`
I attached a log file of the full output of the terminal, when I used installation command above.

Thanks!

[log.txt](https://github.com/chriskiehl/Gooey/files/2827639/log.txt)

**Comment by chriskiehl** [comment]
Looks like WxPython, Gooey's core UI dependency, isn't happy. It is notoriously finicky. 

This is beyond my pay grade, unfortunately. I'd hit up https://github.com/wxWidgets/wxPython to see if they could help you getting it installed on your platform.
