### ISSUE TITLE
iamges/images.jpg unused

### ISSUE THREAD

**Issue by icegreentea** [chriskiehl/Gooey#392]
Gooey Version: 1.0.2 and above.

If you run `python setup.py bdist_wheel` to create a wheel, it generates a 1MB+ wheel. Most of that is taken up by `gooey/images/images.jpg` which doesn't seem to be used. I think that file can be removed from the project.

**Comment by chriskiehl** [comment]
Oh, whoa -- yeah. Five years that's been floating around for no reason at all. 

Thanks for pointing it out! [Now removed on the release branch!](https://github.com/chriskiehl/Gooey/commit/6abdec3ae5d0e88b431df5b9dfee5e05ca331906)
