### ISSUE TITLE
Default directory location for FileChooser

### ISSUE THREAD

**Issue by chrisborbidge** [chriskiehl/Gooey#398]
Is it possible to set the default directory of the GooeyParser FileChooser widget?

Perhapys using the [wx.FileDialog.SetDirectory](https://wxpython.org/Phoenix/docs/html/wx.FileDialog.html#wx.FileDialog.SetDirectory) method of wx?

**Comment by gonzygonz** [comment]
Hi
i made a PR for that in #400 
hope it gets in soon.

**Comment by smokephil** [comment]
You can use it by simply define the default_dir in the gooey_options dictionary.

https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md
