### ISSUE TITLE
fix missing i18n translate in group names

### ISSUE THREAD

**Issue by badiku** [chriskiehl/Gooey#399]
Group names:
required_args_msg
optional_args_msg

it seems that currently they are not referred,
though already translated in each languages.

quick fix:

1 at Gooey/gooey/python_bindings/argparse_to_json.py 
change line 139 :
group['name'] = 'Required Arguments'
to:
group['name'] = 'required_args_msg'

change line 141:
group['name'] = 'Optional Arguments'
to:
group['name'] = 'optional_args_msg'

2 at Gooey/gooey/gui/components/config.py 
add i18n import:
from gooey.gui.lang.i18n import _

add to line 94 in function makeGroup:
group['name'] = _(group['name'])

**Comment by chriskiehl** [comment]
Thanks for pointing that out. Fixed on release branch [here](https://github.com/chriskiehl/Gooey/commit/2a9c5afd9e3cf3708d622c20742475fb5a8e47e3)
