### ISSUE TITLE
Have Gooey work with docopt

### ISSUE THREAD

**Issue by brianbruggeman** [chriskiehl/Gooey#4]
Really cool library.

Not so much an issue, more of a feature request:  have Gooey work with or use docopt.

**Comment by aliabbasjp** [comment]
so any forks which implements this?

**Comment by chriskiehl** [comment]
@aliabbasjp None that I know of. I kinda thought that through the glory of Open Source some awesome person would have picked up the torch. But alas, that plan didn't pan out. : ) So! I'll stop being lazy, re-open this, and get to work!

**Comment by casperdcl** [comment]
I have implemented a `docopt` to `argparse` module; but can't seem to get Gooey to work with it:

``` python
from argopt import argopt
from gooey import Gooey, GooeyParser


@Gooey
def main(doc):
    # parser = argopt(doc, version='0.1.2-3.4')
    # parser.print_help()

    parser = argopt(doc, argparser=GooeyParser)

    args = parser.parse_args()
    print (args)


if __name__ == '__main__':
    doc = '''
Ex

Usage:
    test.py [-h | --help | options] <f> [<g>...]

Options:
    --anarg=<b>  Its [default: True]
    -f, --force  Force
'''
    main(doc)
```

I get a `TypeError: <lambda>() takes no arguments (1 given)` when using the `Gooey` wrapper.

**Comment by casperdcl** [comment]
I have implemented a `docopt` to `argparse` module called `argopt`; but can't seem to get Gooey to work with it:

``` python
from argopt import argopt
from gooey import Gooey, GooeyParser


@Gooey
def main(doc):
    # parser = argopt(doc, version='0.1.2-3.4')
    # parser.print_help()

    parser = argopt(doc, argparser=GooeyParser)

    args = parser.parse_args()
    print (args)


if __name__ == '__main__':
    doc = '''
Ex

Usage:
    test.py [-h | --help | options] <f> [<g>...]

Options:
    --anarg=<b>  Its [default: True]
    -f, --force  Force
'''
    main(doc)
```

I get a `TypeError: <lambda>() takes no arguments (1 given)` when using the `Gooey` wrapper. The uncommented version works fine...

**Comment by brianbruggeman** [comment]
https://github.com/chriskiehl/Gooey/search?utf8=✓&q=lambda

Looks like the events and decorators are causes.   While python certainly provides lambda as a tool, more often than not it obfuscates debugging and causes more issues when other developers look at the code.  Usually, a new function is far better for providing clear code.

**Comment by casperdcl** [comment]
Thanks @brianbruggeman see #158

**Comment by casperdcl** [comment]
Incidentally `argopt` works for python 2.6 through to 3... It's pretty useful for extending syntax of `docopt` as well (just define most of the simple arguments in a docstring, then add advanced arguments manually).

**Comment by makefu** [comment]
Hey all, is there any chance to get this into gooey at some point?
Cheers!

**Comment by casperdcl** [comment]
@makefu have you tried out `argopt`?

```python
conda install argopt Gooey
git clone https://github.com/casperdcl/argopt
cd argopt/examples
argopt/examples (master)$ python demo_advanced.py --with-gooey
```

**Comment by makefu** [comment]
@casperdcl actually i did this just yesterday and it looks extremely promising! thanks for the hints!

**Comment by brianbruggeman** [comment]
@makefu  I originally opened this comment (wow - 2014) when I first heard about Gooey (from a reddit post I believe).  At the time, Docopt was also reasonably new and I thought it was pretty nice.

Today, I think [click](https://click.palletsprojects.com/en/7.x/) is probably better at this point.  Docopt promises simplicity, but click really delivers on composition.  And there may be a little bit more boilerplate, but the composition click enforces makes your code explicit and straight-forward.
