### ISSUE TITLE
wxpython inspection tools opened by default

### ISSUE THREAD

**Issue by gonzygonz** [chriskiehl/Gooey#402]
- windows 10
 - Python 3.6
 - Gooey Version 1.0.3 branch

Since  11a53edac1f980e0e847b260d0cbf9126b07690a  whenever running, a new window of wxpython inspection tools is opened. 
is there a way to turn off this behavior?
it seems weird to me that by default this debug tool is opened. 

it happens since adding line:
`wx.lib.inspection.InspectionTool().Show()`
to gooey/gui/application.py

Thanks! ^_^

**Comment by chriskiehl** [comment]
> it seems weird to me that by default this debug tool is opened. 

Yeah, that's the branch on which I do all the active dev stuff ¯\\_(ツ)_/¯ It's got a bit of cruft / debug noise floating around. 

I'd say this isn't an issue, as it's a dev branch, but, just to make sure I don't forget, let's leave it open : )
