### ISSUE TITLE
clickable link from output

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#404]
I want the log output to include a link (either HTTP or a local flie) and that when the user clicks the link it will open that link in browser. is it possible?

**Comment by eladeyal-intel** [comment]
I googled and met TE_AUTO_URL - maybe this can help

**Comment by chriskiehl** [comment]
Added to the release branch 

```python
from gooey import Gooey, GooeyParser


@Gooey
def main():
    parser = GooeyParser()
    args = parser.parse_args()
    print('''
Who said that? SURE you can die! You want to die?! Enough about your 
promiscuous mother, Hermes! We have bigger problems. Does anybody else feel 
jealous and aroused and worried? There, now he's trapped in a book I 
wrote: a crummy world of plot holes and spelling errors!

http://fillerama.io/
    ''')


if __name__ == '__main__':
    main()
```

**Comment by eladeyal-intel** [comment]
@chriskiehl  please un-close

something is wrong.

Tested on python 3 on WIndows 10. 

When I click the URL it opens it lots and lots of times.

try to output the string r'file://c:\temp\x.xlsx' and you can see that it opens a few Excel  instances. Same goes for http://google.com - it opens multiple Chrome tabs.

**Comment by chriskiehl** [comment]
Un-close... or _re-open_...? hmm.. ^_^
 
Define "lots" for me? > 10? 2? Immediate hunch is that a single click event is spawning n-events. May just need debounced or something. I'll dig into it.

**Comment by eladeyal-intel** [comment]
@chriskiehl - More than 10. You want my guess?

according to https://comp.soft-sys.wxwindows.narkive.com/lGHAJaFi/how-to-use-evt-text-url-id-func-of-wxtextctrl - "EVT_TEXT_URL(id, func) A mouse event occured over an URL in the text control (Win32 only)" ; so it's not limited to a click event. Every time I move the mouse while inside the URL, it will spawn the handler. 

Here is a snippet from http://wxpython-users.1045709.n5.nabble.com/EVT-TEXT-URL-event-is-fired-many-times-td2357053.html :
```
def OnTextCtrl1TextUrl(self, event): 
         if event.MouseEvent.LeftUp(): 
             print 'ctrl 1 url: %s' % event.GetEventObject().GetValue() 
         event.Skip() 
```
