### ISSUE TITLE
Trivial Gooey application never completes

### ISSUE THREAD

**Issue by oharboe** [chriskiehl/Gooey#405]
1. Ubuntu 18, Python 3.6
2. Gooey 1.0.2
3. Expected: Run attached program, click start, it should complete immediately
4. Actual behavior: It never completes

**Comment by oharboe** [comment]
`$ python3 testapp.py 
'/usr/bin/python3' -u 'app/testapp.py' --ignore-gooey 
[never completes]
`

![image](https://user-images.githubusercontent.com/2798822/55876852-e3695b00-5b98-11e9-9cf0-4502ea95541e.png)

![image](https://user-images.githubusercontent.com/2798822/55876887-f3813a80-5b98-11e9-80c5-7d59d5c480b9.png)

At this point, the application never completes.

**Comment by oharboe** [comment]
[testapp.zip](https://github.com/chriskiehl/Gooey/files/3063635/testapp.zip)

**Comment by chriskiehl** [comment]
Please provide a minimal copy/pastable code example in the issue.  I can't look at a .zip on my phone.

**Comment by oharboe** [comment]
`import sys
from gooey import Gooey, GooeyParser

class simpletest(object):
    def __init__(self, args=[]):
        
        parser = GooeyParser(description="Why does this lock up?")

        parser.parse_args(args)
        

@Gooey()
def main():
    simpletest(sys.argv[1:])
    print("Blah")

if __name__ == "__main__":
    main()`

**Comment by chriskiehl** [comment]
That... isn't valid python.. 

From what I can gather from your broken code sample is that you're trying to run Gooey via a class. See this [issue](https://github.com/chriskiehl/Gooey/issues/309) for a class based example that can be run against the [release branch](https://github.com/chriskiehl/Gooey/tree/1.0.3-release). 

Other than that, closing, as I have no idea what you're asking or trying to accomplish.
