### ISSUE TITLE
Change progress bar without printing

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#407]
I'd want the ability to change the progress bar without writing so much text on the screen.

I thought you can do this easily by using the exiting progress regexp and a flag, hide_progress. If hide_progress==True, you simply filter out lines meeting the regex.

Maybe even add a function which when running vi Gooey it will output the progress, and when running w/o Gooey it will not print it.

**Comment by chriskiehl** [comment]
This has been implemented on the release branch [here](https://github.com/chriskiehl/Gooey/commit/f2cc708009f696f0654e9c7c403275426501409e)

**Comment by eladeyal-intel** [comment]
https://github.com/chriskiehl/Gooey/pull/409

**Comment by eladeyal-intel** [comment]
@chriskiehl am I correct to understand that this is part of gooey-1.0.3 ? and that the lastest gooey in pypi is 1.0.2 without this feature? thanks

**Comment by chriskiehl** [comment]
Yep yep. All the cool new stuff is in 1.0.3. 

PyPi will generally track what's in `master`.
