### ISSUE TITLE
hebrew

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#410]
@ronyhe
@eturkes

Comments for Hebrew translations:

change אתחול to התחל מחדש - I think this is a major bug, the word אתחול usually means "initialize" or "format"

The subtitle "Optional Arguments" is not translates to hebrew

I think the usual way to name buttons in Hebrew is ציווי (imperative) so

change התחלה to התחל 
change ביטול to בטל
change עצירה to עצור
change עריכה to ערוך

![image](https://user-images.githubusercontent.com/20379005/56090886-9b0baf00-5eb0-11e9-8372-f51dea606e09.png)

**Comment by chriskiehl** [comment]
Your language fixes: merged! 
The missing default group translation has been fixed on the release branch.
