### ISSUE TITLE
Feature Request: Intro tab

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#416]
I propose to add a "introductory" tab before all the other tabs, where software developer can provide some high level instruction on how to use the tool. mock up attached

![image](https://user-images.githubusercontent.com/20379005/56474950-f548d900-6489-11e9-89d3-1ac7107fabe2.png)

One way to provide this capability:
Add parameter to `Gooey` decorator called `intro_tab`

* `intro_tab==None` or `False` ==> legacy behaviour
* `intro_tab` is a string - This string is the title for the intro tab. The `description` argument from `ArgumentParser` is used in the intro tab instead of the title section.
* `intro_tab==True` ==> same as `intro_tab=='Introduction'` (subject to language translation)

**Comment by chriskiehl** [comment]
This is already possible via existing functionality, so no plans for making this a special case. 

![image](https://user-images.githubusercontent.com/1408720/57576891-fa150300-741f-11e9-8545-4fa893b8aa68.png)

Seems like it'd be a good Cookbook entry in the `docs` folder, though! 

FWIW, here's how I made the above: 

```python
@Gooey(
    program_name='Advanced Layout Groups',
    sidebar_title="Your Custom Title",
    show_sidebar=False,
    dump_build_config=True,
    tabbed_groups=True,
)
def main():
    import sys
    print(sys.argv)
    my_cool_parser = GooeyParser(description='Hai', add_help=False)

    description_area = my_cool_parser.add_argument_group(
        "Introduction",
        long_intro,
        gooey_options={
            'show_border': False,
            'show_underline': False,
        }
    )

    # We need at least on
    description_area.add_argument(
        '-nothing',
        gooey_options={
            'visible': False,
        }
    )

    categories = my_cool_parser.add_argument_group(
        'Categories',
        description='There are 13 species of crocodiles, so there are many different ' +
                    'sizes of crocodile. The smallest crocodile is the dwarf crocodile. ' +
                    'It grows to about 5.6 feet (1.7 meters) in length and weighs 13 to 15 pounds ',
        gooey_options={
            'show_border': False,
            'label_color': '#FF9900',
            'columns': 2,
            # 'margin_top': 90
        }
    )

    categories.add_argument(
        '--parent-category',
        metavar='Parent Category',
        help='This is a very, very, very long help text '
                             'to explain a very, very, very important input value. '
                             'Unfortunately, the end of this long message is cropped. ',
        choices=['a', 'b', 'c'],
        required=True)

    args = my_cool_parser.parse_args()
    print("Hiya!")


if __name__ == '__main__':
    main()
```
