### ISSUE TITLE
Add Clear option to console

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#426]
can we add an option to clear the console output?

![image](https://user-images.githubusercontent.com/20379005/57579560-c92be100-74a6-11e9-9130-d8690ed0870b.png)

**Comment by fontanka16** [comment]
It would be interesting to hear how others have implemented this. We add a lot of empty rows so that it at least appear empty.

**Comment by chriskiehl** [comment]
Checkout the [Global Configuration](clear_before_run) part of the README. You can set `clear_before_run=True` in the decorator, and it'll give you a blank slate on each run. 

Here's a quick demo:

![example](https://user-images.githubusercontent.com/1408720/121785800-c1046b00-cb70-11eb-87ac-e8a7ef14f1d2.gif)

**Comment by fontanka16** [comment]
Amazing! Thank you.
