### ISSUE TITLE
python3 unicode error 

### ISSUE THREAD

**Issue by rgiannico** [chriskiehl/Gooey#428]
Hi, I'm running Windows 10 with a miniconda3 (python3) 
I installed gooey (v1.0.2) and pyinstaller (v3.4) today following the 'packaging' instructions here: https://chriskiehl.com/article/packaging-gooey-with-pyinstaller 

I only changed this line to be added in my python script 
from this `nonbuffered_stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)` 
to this `nonbuffered_stdout = os.fdopen(sys.stdout.fileno(), 'w')` 
because of python3 needs (see [this stackoverflow topic](https://stackoverflow.com/questions/45263064/how-can-i-fix-this-valueerror-cant-have-unbuffered-text-i-o-in-python-3)  )
But I've got the following error. 

```
> pip install Gooey 
> pip install pyinstaller
> cd c:\mybuildingdir
> python test.py 
# this runs successfully
> pyinstaller build.spec
69 INFO: PyInstaller: 3.4
69 INFO: Python: 3.7.3
71 INFO: Platform: Windows-10-10.0.17134-SP0
73 INFO: UPX is not available.
Traceback (most recent call last):
  File "c:\users\giannico\appdata\local\continuum\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\giannico\appdata\local\continuum\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\giannico\AppData\Local\Continuum\miniconda3\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\giannico\appdata\local\continuum\miniconda3\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\giannico\appdata\local\continuum\miniconda3\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\giannico\appdata\local\continuum\miniconda3\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\giannico\appdata\local\continuum\miniconda3\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 7
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

Any suggestion?

**Comment by chriskiehl** [comment]
Please post a runnable code example demonstrating the problem.

**Comment by rgiannico** [comment]
Sorry, here it is. It's just a very basic script, it just show the interface and print "Done" on screen. 
(of course rename the attached files deleting the .txt extension) 
[build.spec.txt](https://github.com/chriskiehl/Gooey/files/3190343/build.spec.txt)
[test.py.txt](https://github.com/chriskiehl/Gooey/files/3190344/test.py.txt)

Uh I just solved the 'unicode error' changing this 'build.spec' lines
from this
```
a = Analysis(['test.py'],
             pathex=['C:\mypythontest\test_gooey'],
```
to this
```
a = Analysis([r'test.py'],
             pathex=[r'C:\mypythontest\test_gooey'],
```
because python3 needs it (see this [stackoverflow post](https://stackoverflow.com/questions/37400974/unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3-trunca?rq=1) )

But I still have a 'Fatal Error Detected: Failed to execute script' windows popup message when I try to execute the .exe 
Do you have any suggestion? (should I start a different issue?)

**Comment by rgiannico** [comment]
Uh I solved this one too!
Thanks to this issue here https://github.com/chriskiehl/Gooey/issues/295 
I changed the build.spec file line `console=False,` to `console=True,` and it works!
I'll add a step-by-step guide to the wiki here, if you think it could be useful

**Comment by chriskiehl** [comment]
You. Are. Amazing!

I've long been bugging people to add their packaging experiences / knowledge to the wiki. You are the first! Thanks for the wiki contribution!

**Comment by execptionerror** [comment]
All Possible solution added here [[Solved] SyntaxError: (unicode error) ‘unicodeescape’ codec can’t decode bytes in python3](https://flutterq.com/syntaxerror-unicode-error-unicodeescape-codec-cant-decode-bytes-in-python3/)
