### ISSUE TITLE
change font size for rich console

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#432]
When using the non-rich-text console, on Windows 10, you can use control+mouse wheel to enlarge the console text font. This is cool.

It doesn't work the same way for rich console.

It should.

**Comment by eladeyal-intel** [comment]
@chriskiehl closed the PR. Should I rebase and reopen? Or are you not interested?

**Comment by chriskiehl** [comment]
Closing. Merged into release.
