### ISSUE TITLE
rich console not appending text

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#433]
Run something with the rich console. Select any word inside the console. Click "Restart".

Expected behavior: New data from app should be appended to console window.
Actual behavior: Data is inserted at the cursor.

The obvious cause is that     AppendText() is overiden to call WriteText instead of AppendText:

https://github.com/chriskiehl/Gooey/blob/1202f13a5c916a5a4c07590a8c55b523de7cf606/gooey/gui/components/widgets/richtextconsole.py#L76 https://github.com/chriskiehl/Gooey/blob/1202f13a5c916a5a4c07590a8c55b523de7cf606/gooey/gui/components/widgets/richtextconsole.py#L85

**Comment by chriskiehl** [comment]
Resolved via:  fix rich console was not appending - fix #433
