### ISSUE TITLE
Missing return statement on ProcessController.poll()

### ISSUE THREAD

**Issue by Unit2MBailey** [chriskiehl/Gooey#436]
https://github.com/chriskiehl/Gooey/blob/e598573c6519b953e0ccfc1f3663f827f8cd7e22/gooey/gui/processor.py#L30

I frequently find that Gooey will get stuck waiting for a process to finish, and I found that its running() function is erroneously returning True. I don't think that's the cause of the issue though, as the issue is intermittent, and seemingly caused by the subprocess spawning another process not as a child.

**Comment by chriskiehl** [comment]
Yo, guy, please fill out the issue template. 

Gimmie a runnable code sample, gooey version, os, etc... For now, closing as there is nothing for me to do other than try to guess at your issue. Feel free to reopen.

**Comment by Unit2MBailey** [comment]
Sorry, please ignore my original comment and just read the title. I was pointing out that there is a missing "return" on the function. My comment was just unnecessary context!
