### ISSUE TITLE
How to display groups side by side

### ISSUE THREAD

**Issue by ATran31** [chriskiehl/Gooey#448]
How can I get sub groups to display side by side like the `Flags` and `Price_Range` groups below? I can create multiple groups but they all display top to bottom in the order they were defined. I would like to have sub groups in the `Required Options` group and tried to pass the `required_cols` argument to the Gooey decorator but it did nothing.

![image](https://user-images.githubusercontent.com/8496965/59460871-18d73280-8dee-11e9-9694-f427bc9587cd.png)

**Comment by chriskiehl** [comment]
Good question! I've been meaning to write up a doc on creating more complex layouts in Gooey. The argument you're looking for is `columns`. I've started documenting the various Gooey options here: https://github.com/chriskiehl/Gooey/blob/1.0.3-release/docs/Gooey-Options.md 

By default, groups are single column, but you can tune it to whatever you want. Here's a code sample:


```python
@Gooey
def main():
    parser = GooeyParser()
    parent = parser.add_argument_group('Search Options', gooey_options={
        'columns': 2
    })
    parent.add_argument('--query-string', help='the search string')

    child_one = parent.add_argument_group('flags', gooey_options={'show_border': True})
    child_one.add_argument('--option1', help='some text here')

    child_two = parent.add_argument_group('price', gooey_options={'show_border': True})
    child_two.add_argument('--option2', help='some text here')
    args = parser.parse_args()


if __name__ == '__main__':
    main()
```
