### ISSUE TITLE
Question: How to bind a shell command to Gooey Gui?

### ISSUE THREAD

**Issue by yuzibo** [chriskiehl/Gooey#450]
Hello all,
This is just my stupid question about Gooey.
My goal is find a tool about converting bash command (e.g ls, mv or mininet) into GUI.
If i understand correctly, Gooey will be suit the request.If so, should i to be do with it?
Thank you very much!

**Comment by chriskiehl** [comment]
You'd have to put some more definitions around "converting bash commands." I'm not totally sure your intent. 

If you just want a 'pretty' GUI into which people put a shell command and then see the output, then, yup, Gooey could do that. 

If you want to bind specific shell commands to specific UI controls such that your users don't _need_ to know about any kind of shell specific syntax, then you're also in luck: Gooey is super good at that, too. 

If you know just enough Python, then the rest should be in reach.
