### ISSUE TITLE
Exit Yes/No modal buttons missing i18n  

### ISSUE THREAD

**Issue by sgnp** [chriskiehl/Gooey#452]
When one preses the "Cancel" button (e.g. for  the simple_demo.py example, included in the github repo) a window will be raised asking the user whether he really wants to quit or not.

The "Yes" and "No" button language is not controlled by Gooey though, but through the system. This is not desirable. For example, if I set Gooey up in English but my system's language is French, it will have an inconsistent feel to, since the "Yes"/"No" button will be in French. 

So the only way to avoid this is if the system language conincides with the Gooeys language. But as an app creator, I would like my menus to be independent of the system's language. 

Setup:
Windows 10
Python 3.6.7
Gooey 1.02
wxPython 4.0.6

**Comment by chriskiehl** [comment]
Fixed on the [release branch](https://github.com/chriskiehl/Gooey/commit/df9284a467e557bef29f7067cf75e3d58f8f5cf0)
