### ISSUE TITLE
[how to use sidebar?]

### ISSUE THREAD

**Issue by pynickle** [chriskiehl/Gooey#454]
Hello, l saw the document and find **sidebar**. l try to use sidebar to **combine my small projects with gooey**. But it didn't work, l really want to know how can l use sidebar.

And l also hope the document can be more **detailed**.

**Comment by pynickle** [comment]
Ok, l have solved the problem

**Comment by chriskiehl** [comment]
Glad you solved it! ^_^ 

Would you mind going into a bit of detail about (a) where your confusion was, and (b) how you resolved it (current docs, outside resources, etc..)? 

I'm working on updating documentation and introducing more detailed guides. Hearing problem spots like yours helps me know where best to beef things up! Thanks!
