### ISSUE TITLE
Can't run in virtualenv

### ISSUE THREAD

**Issue by filips123** [chriskiehl/Gooey#455]
I can't use Gooey inside virtualenv.

---

I created [a program](https://pypi.org/project/hotbits/) which adds console scripts entry point to `__main__:main`. I cloned GitHub repository, created virtualenv and installed my program with `pip install -e .`.

It works when I use it without Gooey. But when I add `@Gooey` decorator, it doesn't.

Ui opens. Arguments are parsed and displayed correctly. But when I try to run it, I get an error.

When I directly run `hotbits` (name of my program), it fails with:

```
(null): can't open file 'PATH-TO-PROJECT\venv\Scripts\hotbits': [Errno 2] No such file or directory
```

When I run `python -m hotbits`, it fails with:

```
Traceback (most recent call last):
  File "PATH-TO-PROJECT\hotbits\__main__.py", line 10, in <module>
    from . import RandomDataGenerator
ImportError: cannot import name 'RandomDataGenerator' from '__main__' (PATH-TO-PROJECT\hotbits\__main__.py)
```

---

 - OS: Windows 10
 - Python Version: 3.7
 - Gooey Version: 1.0.2

**Comment by chriskiehl** [comment]
Please fill out the issue template in its entirety. Minimal code example is required for debugging your issue.

**Comment by filips123** [comment]
I can't provide a minimal code example, but I can provide steps to reproduce.

1. Clone https://github.com/filips123/HotBitsPy.git.
2. Modify `hotbits/__main__.py` and add `from gooey import Gooey` import and `@Gooey` decorator on `main` function.
3. Create virtualenv and activate it.
4. Install Gooey with `pip install Gooey`.
5. Install my program with `pip install -e .`
6. Try to run `hotbits` and `python -m hotbits`.

**Comment by bilderbuchi** [comment]
I think I've run into the same issue, only without using a virtualenv - I think the entrypoints feature could be the more relevant part here.

I have a suspicion that the cause is that the `.exe` gets lost from the executable name, in the path above `'PATH-TO-PROJECT\venv\Scripts\hotbits'`, the correct path will most probably be `'PATH-TO-PROJECT\venv\Scripts\hotbits.exe', so no wonder the file does not get found.

**Comment by bilderbuchi** [comment]
@chriskiehl I have defined a MWE:
```
git clone -b gooey_455 https://github.com/bilderbuchi/HotBitsPy.git
cd .\HotBitsPy\
conda create -n gooey_455 python Goeey
conda activate gooey_455
pip install -e .
hotbits
```
Running the last command opens the Gooey window. Pressing Start gives
``` 
C:\Users\buchner\AppData\Local\Continuum\miniconda3\envs\gooey_455\python.exe: can't open file 'C:\Users\buchner\AppData\Local\Continuum\miniconda3\envs\gooey_455\Scripts\hotbits': [Errno 2] No such file or directory

```
Running `python -m hotbits` gives another error
```
Traceback (most recent call last):
  File "C:\Users\buchner\Desktop\Python_local\HotBitsPy\hotbits\__main__.py", line 10, in <module>
    from . import RandomDataGenerator
ImportError: attempted relative import with no known parent package
```

I have observed the same behaviour in my (non-public :-/) package/code.

**Comment by fuzzmz** [comment]
Any updates on this?

**Comment by gustavorps** [comment]
+1

**Comment by PeterSR** [comment]
Why is this closed? Would be nice to have a solution to this. I am facing the same.

Normally I am running

```
python -m project.cli
```

Now I modified the `main` function in `cli` to be wrapped in `Gooey` and it launches the configuration screen but starting fails with the error message described above.
