### ISSUE TITLE
Display output image

### ISSUE THREAD

**Issue by Caugustine1** [chriskiehl/Gooey#457]
How do I display an output image (graph) using Gooey? I am using matplot plt.show() in my script and the only thing gooey is displaying is the framesize.

**Comment by chriskiehl** [comment]
FYI, issues like this sap an open source maintainer's soul. 

Gooey works a-ok with sklearn/matplotlib/whatever. Why doesn't work in your case? I couldn't tell ya. You've ignored the entire issue template and, in doing so, provided absolutely no valuable data with which I could help you. 

So, instead you, like so many others, get a response I've typed out a hundred times: 

# "please fill out the issue template."
