### ISSUE TITLE
Pytest compatibility

### ISSUE THREAD

**Issue by jonathangjertsen** [chriskiehl/Gooey#459]
I'm working with a pytest-based application for hardware testing which uses `pytest_addoption` to add command-line arguments. It would be useful to be able to add the @Gooey decorator there.

Alternatively, is there another way to make take an `ArgumentParser` object and convert it to a Gooey version? Then it could be done as part of the code in `pytest_addoption`.

**Comment by chriskiehl** [comment]
Howdy friend, 

I'm not actually sure what you're asking here. I don't know much about pytest, so I don't know where you're trying to integrate Gooey. If you have some concrete detailed integration examples + use cases, feel free to reopen this issue.
