### ISSUE TITLE
o

### ISSUE THREAD

**Issue by arceneauxx** [chriskiehl/Gooey#461]
Hello There, Future Issue Creator! 

If you've found a bug, make sure to include the following:

 - [ ] OS
 - [ ] Python Version 
 - [ ] Gooey Version 
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior 
     - [ ] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
O_o

**Comment by arceneauxx** [comment]
That was obviously some accident, though I don't remember. Apologies... You may delete this.
