### ISSUE TITLE
Color Change for Start , Edit ,Cancel , Date Buttons etc

### ISSUE THREAD

**Issue by kkumarsachin** [chriskiehl/Gooey#465]
Hi,

I am currently unable to change the color of the buttons nor the background color and Footer color. The Start , Cancel and Date buttons of widgets are all white with white background. I have tried changing the color using footer_bg_color but the color change is not reflected.

Kindly let me know how i can make this changes

 - OS - Mac OS - 10.14.6
 - Python Version - 3.7.4
 - Gooey Version  - 1.0.2

**Comment by chriskiehl** [comment]
Please fill out the issue template in its entirely.
