### ISSUE TITLE
argparse.SUPPRESS shows up as ==SUPPRESS== in the gui

### ISSUE THREAD

**Issue by anntzer** [chriskiehl/Gooey#469]
- [X] OS: Arch Linux
 - [X] Python Version: 3.7.3
 - [X] Gooey Version: 1.0.2
 - [X] Thorough description of problem 
     - [X] Expected Behavior: An option whose default is argparse.SUPPRESS (https://docs.python.org/3/library/argparse.html#default) shows up as `==SUPPRESS==` in the GUI.
     - [X] Actual Behavior: The default should be displayed as an empty text box.  (Yes, I know, `argparse.SUPPRESS == "==SUPPRESS=="` but that's arguably a problem on argparse's side; Gooey should still detect this and replace it by an empty box.)
 - [X] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!)
```
from argparse import ArgumentParser, SUPPRESS
from gooey import Gooey

@Gooey
def main():
    parser = ArgumentParser()
    parser.add_argument("--foo", default=SUPPRESS)
    print(parser.parse_args())

main()
```
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful

**Comment by chriskiehl** [comment]
Fixed on the [release branch](https://github.com/chriskiehl/Gooey/commit/c7f21aa90091abb47be689089ac4eb061a1a6fb3)!
