### ISSUE TITLE
Works with Windows-style command line switches?

### ISSUE THREAD

**Issue by jdlyga** [chriskiehl/Gooey#475]
I'd love to use Gooey as a front-end to some command line applications I regularly use.  These are windows command line applications that either use windows-style forward slashes to separate arguments:

e.g. MyConsoleApplication.exe /play:c:\audio\file.mp3 /loop

or more custom approaches that uses words without dashes to separate files

e.g. MyConsoleApplication.exe play c:\audio\file.mp3 100

Gooey is great, but it primarily conforms to the Mac/Linux command line parameter format.  Would it be possible to add a mode to add more flexibility to the output command line parameters?

**Comment by chriskiehl** [comment]
Oh, whoa, I didn't know that was a thing, tbh. I guess I never paid much mind to how the Windows terminal flavors worked. 

The variability is kind of scary, just from looking at the wiki entry. https://en.wikipedia.org/wiki/Command-line_interface#Option_conventions_in_DOS,_Windows,_OS/2

Do you know of an authoritative source for modern Window's syntax? Or a Python library that parses it? Something like the [GNU syntax docs](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) would be super helpful in knowing the delta between the two forms.
