### ISSUE TITLE
Does it support Mac?

### ISSUE THREAD

**Issue by phoenixg** [chriskiehl/Gooey#476]

**Comment by chriskiehl** [comment]
yep

**Comment by chumaumenze** [comment]
There's no documented way to compile/freeze for other platforms. I can't get an example app to build on mac. Followed https://github.com/chriskiehl/Gooey/issues/259 but to no resolve.

**Comment by chriskiehl** [comment]
Did you try the current packaging instructions in the docs folder? https://github.com/chriskiehl/Gooey/blob/master/docs/packaging/Packaging-Gooey.md
