### ISSUE TITLE
Add click support

### ISSUE THREAD

**Issue by hashstat** [chriskiehl/Gooey#478]
The `argparse` module is so yesterday. ;-)  Sure it's built in, but I honestly find it cumbersome. I found the [click](https://palletsprojects.com/p/click/) package earlier this year and it is soooo much better.

The great thing about click is that it uses decorators to annotate a function with all the arguments and options, so there is no need to search the file for `ArgumentParser`. Just add `Gooey` to the top of the decorator stack and all the options and arguments are available on the function passed into the decorator. Sweet!

```Python
import click
import gooey

@gooey.Gooey
@click.command()
@click.option("--count", default=1, help="Number of greetings.")
@click.option("--name", prompt="Your name",
              help="The person to greet.")
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for _ in range(count):
        click.echo("Hello, %s!" % name)

if __name__ == '__main__':
    hello()
```

Now that's slick, right?

**Comment by chriskiehl** [comment]
Click was requested way back in #135 : )

The unfortunate answer to this one is that additional bindings for libraries like Click will have to be driven (and maintained!) by the community.  

Keeping the core features flowing through Gooey (plus managing day job, life, other projects) is already a pretty high workload. Adding a whole other set of bindings to Gooey and getting it to feature parity with Argparse (and then keeping it up to date as Gooey continues to grow its feature set) isn't something I could feasibly do at the moment. I am but one fella :(

Gooey is all driven by JSON these days. So if someone was so inspired (hint! ^_^) all they would need to write would be something that mapped a Click object into the JSON schema used by Gooey

**Comment by hashstat** [comment]
It is tempting. I'll have to see if I can carve some time out.

**Comment by erinxocon** [comment]
I'm just checking out this project and figured the best way to learn was to help out on some things.  This sounds interesting!  I'd love to poke around for and maybe add support for click!
