### ISSUE TITLE
program_description does not override

### ISSUE THREAD

**Issue by dusans** [chriskiehl/Gooey#480]
Hello There, Future Issue Creator! 

 - [ ] OS : Windows 7 64 bit
 - [ ] Python Version : 2.7.15
 - [ ] Gooey Version : 1.0.3
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior: program_description should override program_description
     - [ ] Actual Behavior: it always takes parser.description
 - [ ] Current code: config_generator.py: 
`      build_spec['program_description'] = parser.description or build_spec['program_description']
`

 - [ ] Suggested code: config_generator.py: 
`      build_spec['program_description'] = build_spec['program_description'] or parser.description
`

**Comment by chriskiehl** [comment]
Fixed on the release branch: 

https://github.com/chriskiehl/Gooey/commit/f22fdcd7afc8704849ad018398d0af68c5a443ba
