### ISSUE TITLE
Utilising Data from Multiple Tabs

### ISSUE THREAD

**Issue by roblkdeboer** [chriskiehl/Gooey#481]
- [ ] OS
Windows 10
 - [ ] Python Version 
3.7.3
 - [ ] Gooey Version 
1.0.3
 - [ ] Thorough description of problem 
I am trying to create a form with multiple to allow users to input data in to then be used to query a database.  
     - [ ] Expected Behavior 
I would expect to be able to take data from both tabs to use it for processing.
     - [ ] Actual Behavior 
I am only able to take the input data from the tab that is selected and any other data I have entered is not usable.  In my attached example, I have Variable 1 in the General tab and Variable 2 in the Beta tab.  If I select ABC in Variable 1 in the General Tab and Time terminated in Variable 2 in the Beta tab and press start while on the general tab, I get an error saying there is no object with the attribute 'variable2' (refer to screenshot below).
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 

```
from __future__ import print_function
from gooey import Gooey, GooeyParser


#Build the UI
@Gooey(program_name='Report Builder', sidebar_title = 'Items to Select', navigation = 'SIDEBAR', show_sidebar = True, default_size=(715, 550))
def parse_args():
    parser = GooeyParser(description='Select the Job')
    subparser1 = parser.add_subparsers()
    general_subparser = subparser1.add_parser('General')
    parameter_args = general_subparser.add_argument_group("Parameters") 
    parameter_args.add_argument(
            '--variable1',
            metavar = 'Variable1',
            help='Which asset to calculate',
            choices={'ABC', 'DEF', 'GHI'},
            default = 'ABC',
            required=True,
            gooey_options={'visible': True})
    
    beta_subparser = subparser1.add_parser('Beta')
    
    beta_parameter_args = beta_subparser.add_argument_group("Parameters") 
    
    beta_parameter_args.add_argument(
            '--variable2',
            metavar = 'Variable2',
            choices = {'Time terminated', 'Failure terminated'},
            default = 'Time terminated',            
            required=True,
            gooey_options={'visible': True})
        
    args = parser.parse_args()
    return args
    
if __name__ == '__main__':
    args = parse_args()

    if args.variable1 == 'ABC':
        print('123')
    elif args.variable1 == 'DEF':
        print('456')
    else:
        print('789')
    
    if args.variable2 == 'Time terminated':
        print('time')
    else:
        print('failure')

```
 - [ ] Screenshot (if visual quirk) 

![image](https://user-images.githubusercontent.com/35453447/65656977-41f59900-e054-11e9-8211-eee3c1c856c5.png)

Thanks you!

**Comment by eladeyal-intel** [comment]
I thin you used Variable2 with capital V and with lowercase V interchangeably .

**Comment by ozcan-durak** [comment]
I m having the same issue like @roblkdeboer. And couldn't found a way to parse all tabs data.

**Comment by ozcan-durak** [comment]
@eladeyal-intel Can you please provide an example, i couldnt figured it out.

**Comment by eladeyal-intel** [comment]
https://github.com/chriskiehl/GooeyExamples/blob/master/examples/subparser_demo.py

**Comment by eladeyal-intel** [comment]
@ozcan-durak https://github.com/chriskiehl/GooeyExamples/pull/26/commits/763936bf95615f8d5ec31a9054b8381b88a9e3d8
