### ISSUE TITLE
[ Enhancement/Question] Is it possible to change the "Required Arguments" text?

### ISSUE THREAD

**Issue by soliverc** [chriskiehl/Gooey#484]
Not a bug, just a question and possibly feature request. 

Is there a way to change the 'required arguments' header in the GUI? If not, can this be an option? It's kind of a techy term and would like to change it to something more noob friendly or possibly related to the business application.

**Comment by chriskiehl** [comment]
Indeedily doodily! 

Checkout using [Argument Groups](https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md#argument-groups). You can place all your arguments into a custom container with whatever name you like. 

```python 
parser = ArgumentParser() 
custom_group = parser.add_argument_group('Custom Group Name!')
custom_group.add_argument('-f', '--foo', help='...')
# rest of code as usual
```

You can use as many groups as you want and even nest them to create complex layouts!
