### ISSUE TITLE
[Help] I can't for the life of me figure out how to add a checkbox

### ISSUE THREAD

**Issue by soliverc** [chriskiehl/Gooey#485]
First of all Gooey is amazing. I discovered it two days ago and have already reduced a colleague's two day job down to 5 MINUTES! 

Anyway, I decided to add a checkbox, but keep getting the error `list index out of range`.

I have followed the Dev's advice in a related issue [#148 ] word for word and letter for letter, but cannot seem to fix this. 

All I want is a `store_true` check box, which by default is `False`. 

My args:
```python
@Gooey(program_name="Moneyback Calculator",  default_size=(710, 500))
def parse_args():
    parser = GooeyParser(description='Create Monthly MoneyBack Report')

    parser.add_argument('Transaction_File',
                        metavar='Transaction Files',
                        action='store',
                        widget='FileChooser',
                        help="Upload Your File Containing All Transactions Here")

    parser.add_argument('Smart_Rewards_File',
                        action='store',
                        metavar='Smart Rewards File',
                        widget='FileChooser',
                        help="Upload The anPost Smart Rewards File Here")
    
    parser.add_argument('Choose_File_Name',
                        action='store',
                        metavar='File Name',
                        help="Choose A File Name For Your Report")

    parser.add_argument('Output_Directory',
                        widget='DirChooser',
                        metavar='Output',
                        action='store',
                        help="Output Directory To Save Report")

    parser.add_argument('Action',
                    widget='CheckBox',
                    metavar='Completed File',
                    action='store_true',
                    default=False,
                    help="Open Excel File Once Complete?")

    args = parser.parse_args()
    return args
```
If I tick the box, I get the error:
```python
Traceback (most recent call last):
  File "C:\Users\seanc\Anaconda3\lib\site-packages\wx\core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Users\seanc\Anaconda3\lib\site-packages\gooey\gui\containers\application.py", line 87, in onStart
    if config.isValid():
  File "C:\Users\seanc\Anaconda3\lib\site-packages\gooey\gui\components\config.py", line 50, in isValid
    states = [widget.getValue() for widget in self.reifiedWidgets]
  File "C:\Users\seanc\Anaconda3\lib\site-packages\gooey\gui\components\config.py", line 50, in <listcomp>
    states = [widget.getValue() for widget in self.reifiedWidgets]
  File "C:\Users\seanc\Anaconda3\lib\site-packages\gooey\gui\components\widgets\bases.py", line 133, in getValue
    'cmd': self.formatOutput(self._meta, value),
  File "C:\Users\seanc\Anaconda3\lib\site-packages\gooey\gui\components\widgets\checkbox.py", line 45, in formatOutput
    return formatters.checkbox(metatdata, value)
  File "C:\Users\seanc\Anaconda3\lib\site-packages\gooey\gui\formatters.py", line 9, in checkbox
    return metadata['commands'][0] if value else None
IndexError: list index out of range
``` 
And if I don't tick the box, nothing happens. 

Help? I have googled everywhere and can't find an answer. 

If more code is needed I will add it. It needs to be anonymized, which is why I just posted the args in case that's all that's needed. 

Thank you

**Comment by eladeyal-intel** [comment]
Try deleting the default clause and the widget clause.

**Comment by soliverc** [comment]
Thanks for the tip, unfortunately that didn't work. Same `IndexError`

If you look at the traceback, it's trying to index `metadata['commands'][0]` which causes the index error. Is that a clue to something I an fix in my arguments?

**Comment by eladeyal-intel** [comment]
So you're doing something which is confusing. An argument name such as 'Action' suggests a `Positional Parameter` (which is no optional); and on the other hand, `store_true` suggests an Optional Parameter (which may or may be not specified). 

If you try the same with argparse instead of Gooey you will see it doesn't work there as well. 

So your solution is to add two dashes before the word Action.

**Comment by soliverc** [comment]
OK ... I have never used argumentparser before. First time I used it was when I found Gooey two days ago. I guess I should read some how-to guides before getting too deep into this app. 
One more question - what does the two dashes mean and should I use it in any of my other arguments? If you know a good guide I can read I'd appreciate if you share a link.

**Comment by soliverc** [comment]
It works now by the way, thank you. 
You say that `store_true` is an optional argument. So what do we do if we want the checkbox to be a required argument? For example, moving it from the Optional section to Required: 
![image](https://user-images.githubusercontent.com/47222261/65793082-f4188800-e15c-11e9-9a84-57b55fe22f53.png)

**Comment by eladeyal-intel** [comment]
I don't know if you can do it. I usually use a drop box with two choices: yes and no.

**Comment by soliverc** [comment]
OK, good idea. Thanks for your help. Closing this issue now.
