### ISSUE TITLE
Should you be able to make a defaulted parameter, empty, by clearing the text box?

### ISSUE THREAD

**Issue by Unit2MBailey** [chriskiehl/Gooey#494]
Hi,

I'm not sure if this might just be a limitation of argparse, so apologies if it is. In the below example, I'm trying to add a string that has a helpful default value, to show people how to use it. However, I want them to be able to clear the text box and therefore pass in an empty string. However, if you empty the string then when the program re-runs itself it won't pass --specificDay on the command line. That makes the program use the default value of "Monday".

To see what I mean, run this sample, clear the text box, and press Start

```
from gooey import Gooey, GooeyParser

@Gooey
def main():
    parser = GooeyParser()
    parser.add_argument('--specificDay', default="Monday")

    args = parser.parse_args()

    print("Limited to day: ", args.specificDay)

if __name__ == "__main__":
    main() 
```
 
I'm running Gooey version 1.0.3, python version 3.6.2, on Windows.

Thank you for your time, and a great module!

Kind Regards,
Mat Bailey

**Comment by chriskiehl** [comment]
Yeah, as you mention, this is an Argparse thing. When you don't provide any input into one of the fields in Gooey, it doesn't send anything to your program, and thus argparse uses the default you provided. Placeholder text would be a general good feature for Gooey, though! 

As a work aroun, Argparse takes a `help` option which you can use to guide your user. Gooey will show it above the input field. You can make this as descriptive as you want.

```
add_argument('--specificDay', help='Enter the specific day you want. For example "Monday"')
```

**Comment by Unit2MBailey** [comment]
Ah that makes sense. Thank you for the reply. 

One idea I had was to not pass any defaults into argparse add_argument, if --ignore-gooey is on the command line.  I already do that for "choices", so that the UI is populated with sensible/common options, but the user can override with something custom if needed. 

But in general, I guess "don't provide a default if it's valid to leave empty" is a simple enough rule to follow. Actually, just to complicate things: On execution I save out a json file with all the arguments that were used, so that when the UI is opened next time those arguments are populated into the UI. The way I populate them into the UI is to load the json file and set the defaults through argparse set_defaults. That probably throws a bit of a spanner into the works here! If you clear a box that you had previously put a value in, it'll use your previous value. 

It seems like I need to not pass defaults in if --ignore-gooey is on the command line, for arguments where it's valid to leave them empty at least.

Kind Regards,
Mat Bailey

**Comment by frcarneiro** [comment]
Any updates on this?
