### ISSUE TITLE
How to deal with carriage return progress outputs ?

### ISSUE THREAD

**Issue by leoncvlt** [chriskiehl/Gooey#495]
Hi all, I was wondering whether there was any trick to work with long / carriage return progress outputs, such as encoding a long video with ffmpeg, which prints the output on the same line as the progress is ongoing.

The behaviour I noticed was that Gooey would not display any progress whatsoever, and then when the process ends (or is aborted by the user) it would display all lines at once. Problem is that with long processes (I had a video encoding for ~30 mins) it makes the window unresponsive. I have noticed the same behaviour when using both `subprocess.call` and `os.system` - haven't tested other invocation methods nor tried messing around with stdout.

I did see #213 and right now I'm just using an ffmpeg flag to hide any output, but it would be nice if I could see the progress in the Gooey terminal. Any tips or tricks from people who bumped in this same issue?

**Comment by gberardinelli** [comment]
My somewhat hacky workaround to that has been to redirect stdout/err to an object that strips the carriage return before writing to the stream.  Similar to this example which tees the stream into a log file:  https://stackoverflow.com/a/5916874/6179432

**Comment by chriskiehl** [comment]
@leoncvlt apologies for the long delay on answering your question! 

You can get really nice output from ffmpeg in Gooey if you do two things: 

1. set `universal_newlines=True`
2. read from `subprocess.stdout` 

Each ffmpeg update will be produced as a line in Gooey like this: 

![image](https://user-images.githubusercontent.com/1408720/79523076-35498a00-8012-11ea-9dbf-43122f750790.png)

Here's an example of reading the ffmpeg output line by line. 

```python
from gooey import Gooey, GooeyParser
import subprocess

cmd = [
    'ffmpeg',
    '-to', '30',
    '-i', 'Castle-in-the-Sky.mkv',
    'Castle-in-the-Sky.mp4'
]

@Gooey
def main():
    parser = GooeyParser()
    args = parser.parse_args()

    process = subprocess.Popen(
        ' '.join(cmd),
        bufsize=1,
        stdout=subprocess.PIPE,
        stdin=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        universal_newlines=True,  ## this is what makes everything work
        shell=True
    )
    # reading from the process' stdout 
    for line in process.stdout:
        print(line)


if __name__ == '__main__':
    main()
```
