### ISSUE TITLE
Add option to start Gooey fullscreen

### ISSUE THREAD

**Issue by dusans** [chriskiehl/Gooey#496]
It would be nice that we could configure if the Gooey gui should spawn in fullscreen:

https://wxpython.org/Phoenix/docs/html/wx.TopLevelWindow.html?highlight=showfullscreen#wx.TopLevelWindow.ShowFullScreen

**Comment by chriskiehl** [comment]
Added on the [release branch](https://github.com/chriskiehl/Gooey/issues/496) ^_^
