### ISSUE TITLE
header_show_title doesn't do anything

### ISSUE THREAD

**Issue by dusans** [chriskiehl/Gooey#497]
- [ ] OS: Windows 7
 - [ ] Python Version: 2.7.15
 - [ ] Gooey Version: 1.0.3
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior : The header should not be visible if header_show_title is set to False
     - [ ] Actual Behavior : Nothing happens since header_show_title is only being read in python_bindings\config_generator.py. Its not being used anywhere else in the code

**Comment by chriskiehl** [comment]
Please fill out the issue template

**Comment by chriskiehl** [comment]
\*cough\* you still didn't fill out the template entirely \*cough\* 

FWIW, code snippets make a OSS maintainer's life much better.  I can drop them into my editor and instantly start debugging, versus having to use my (slow, not that bright) brain to piece together a test case that demonstrates your problem. 

Still... egregious violations of the rules(!) not withstanding, will fix in 1.0.4!

**Comment by chriskiehl** [comment]
Okie dokie. Fixed on the release branch[0] if you want to give it a whirl. 

[0]https://github.com/chriskiehl/Gooey/tree/1.0.4-release
