### ISSUE TITLE
nargs issues with list values as defaults

### ISSUE THREAD

**Issue by nklapste** [chriskiehl/Gooey#500]
**OS:** Windows 10

**Python Version:** Python 3.6.3

**Gooey Version:** 1.0.3

**Expected Behavior**: argparse arguments that contain `nargs` share similar default arg behavior between CLI and GUI.
**Actual Behavior**: argparse arguments  that contain `nargs`  have different default arg behavior between CLI (defaults interpreted as lists) and GUI (defaults interpreted as strings).

**Example Code:**

Running the below code with a python native argparser causes `args.multi_arg` to be set to the list of strings `["foo bar"]`.

```python
import argparse


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        nargs="*",
        default=["foo bar"],
        dest="multi_arg",
    )
    return parser


def main():
    args = get_parser().parse_args()
    assert args.multi_arg == ["foo bar"]


if __name__ == "__main__":
    main()
```

Running the below code with the gooey GUI the `multi_arg` GUI text input is set to the string `['foo bar']` by default. Clicking start causes `args.multi_arg` to be set to the list of strings `["['foo", "bar']"]`.

 ```python
from gooey import GooeyParser, Gooey


def get_parser() -> GooeyParser:
    parser = GooeyParser()
    parser.add_argument(
        nargs="*",
        default=["foo bar"],
        dest="multi_arg",
    )
    return parser


@Gooey
def main():
    args = get_parser().parse_args()
    # assert passes with a python native CLI invoked argparser and fails with a GUI invoked argparser
    assert args.multi_arg == ["foo bar"]  


if __name__ == "__main__":
    main()
```

**Other:**
Passing in the string `"foo bar"` into the gooey GUI `multi_arg` GUI text input causes the above assert statement to pass.  Clicking start causes `args.multi_arg` to be set to the list of strings `["foo bar"]`.

**Comment by chriskiehl** [comment]
Fixed on the [release branch](https://github.com/chriskiehl/Gooey/issues/500)! ^_^
