### ISSUE TITLE
Is it possible to use args like ('-e RUNNER_NAME')?

### ISSUE THREAD

**Issue by s684373** [chriskiehl/Gooey#505]
- [x] OS windows10
 - [x] Python Version 3.8
 - [x] Gooey Version 1.0.3

Hi, is that possible to run the command like below using Gooey?
docker run --init -d --memory=4g --name e2e-test-runner -e HOST=%HOST% -e PORT=7090 -e ID=%RANDOM_ID% -e RUNNER_NAME="%RUNNER_NAME%" 

The except behavior for me is that I use parser.add_argument("-e RUNNER_NAME="), and after inputing the name I want, it can be linked like -e RUNNER_NAME={MYINPUT}.

Thanks for your help!

**Comment by eladeyal-intel** [comment]
`docker run -e` is used to specify **environment variables**. You can access environment variables from Python using `os.environ` [docs](https://docs.python.org/2/library/os.html#os.environ)

I *think* you can use the environment variable as a `default` for `add_argument` and this value will appear as a default value in the GUI textbox.

**Comment by chriskiehl** [comment]
Yep. What @eladeyal-intel said. If you read environment details and add them as defaults, they'll show in Gooey. 

```python
import os

from gooey import Gooey, GooeyParser

@Gooey()
def main():
    parser = GooeyParser(description='Just display the console')

    parser.add_argument('--host', help='Ze host!', default=os.environ.get('HOST'))
    args = parser.parse_args()
```
