### ISSUE TITLE
Amending stdlib ArgumentParser

### ISSUE THREAD

**Issue by simplynail** [chriskiehl/Gooey#506]
Hi all,
Is there a possibility to amend arguments configuration previously set to standard lib ArgumentParser with functionality avaialble in GooeyParser, to keep code DRY?

ie I have previosly created command line app using Argument Parser. For argument named "directory" it used argparse.FileType('w'). Now I want to hook up this script to Gooey, but I want "directory" arg to use neat widget='FileChooser' from Gooey, but don't want to rewrite all cli vesion just because this one thing.

Looking at GooeyParser class I tried achieving the above by amending gooey_parser.parser with cli_parser instance created previously in cli_main (as this attribute is actually ArgumentParser() instance looking at the code - but this didn't work.
Any ideas?

_cli_module.py_:
```
import argparse
cli_parser = argparse.ArgumentParser()
cli_parser.add_argument('directory', help='path to search files in', type=argparse.FileType('w'))
cli_parser.add_argument('--subdirectories', help='search inside subdirectories', action='store_true')
```
_gui_module.py_:
```
import gooey
import cli_module

@gooey.Gooey()
def main():
  gooey_parser = gooey.GooeyParser()
  gooey_parser.parser = cli_module.cli_parser
  gooey_parser.add_argument('directory', help="folder to search in", widget='DirChooser') 
  args = gooey_parser.parse_args()

if __name__ == "__main__":
    sys.exit(main())
```

**Comment by eladeyal-intel** [comment]
I usually do something like `from gooey import GooeyParser as ArgumentParser`

**Comment by simplynail** [comment]
Hi, I don't quite understand. What I would like to achieve is in the end to change/override default widget attached to ArgumentParser (from stdlib) to gooey's DirChooser

**Comment by chriskiehl** [comment]
I'm not _quite_ sure of what you're trying to accomplish. Superficially, it looks like @eladeyal-intel's advice is what you want. GooeyParser is a drop-in replacement for Argparse. You don't need to have _both_ `ArgumentParser` _and_ `GooeyParser` instances.

**Comment by simplynail** [comment]
Thanks for responses, looks like I have not described it good enough.

Let's say I have cli tool that I still need to maintain and it's using stdlib `ArgumentParser`. Now, parallely to that cli tool located in `cli_module`, I want to provide another way of interaction for it, in `gui_module`.

Gooey takes care of this quite well by taking my already created `ArgumentParser`, imported from my `cli_module`, and interpreting it to gui widgets after I apply `@gooey.Gooey` decorator. Except for one wigdet - I want to exchange/amend one argument to use different widget.
So for argument defined in `cli_module`:
`parser.add_argument('directory', help='path to search files in', type=argparse.FileType('w'))`
in `gui_module` I'd like Gooey to use `widget="DirChooser"` (by default Gooey applies `"FileChooser"` as stdlib argparse does not have `"DirChooser"` equivalent)

I wouldn't like to duplicate all code created in `cli_module`, just because I want one widget amended in `gui_module`. Can I somehow just amend that one argument in `gui_module`, and for rest rely on Gooye's interpretation of ArgumentParser?

**Comment by iamkroot** [comment]
@simplynail This isn't exactly what you want, but assuming you can edit the `cli_module` source, you could convert that `ArgumentParser` into a `GooeyParser` (and specify the extra gooey_options), and then just pass an `--ignore-gooey` as an (implicit) CLI arg by modifying `sys.argv` when you want to run it as CLI. To go one step further, and not have a dependency on Gooey for the `cli_module`, you can monkey patch the stdlib parser to ignore the gooey_options (I did something like that [here](https://github.com/iamkroot/ilc-scraper/blob/24774ce5ace0d1e67fe55a4892e8eae74ceb1900/utils.py#L12))

**Comment by simplynail** [comment]
all right, thanks for help @iamkroot , looks like I have actually approached the problem from the other way around and haven't stumbled upon `--ignore-gooey` which should do the trick. Thanks for sharing your monkey patching snippet, will try it out if `--ignore-gooey` won't be sufficient
