### ISSUE TITLE
Does Gooey works with other python cli parsers, like Click and and from Docopt?

### ISSUE THREAD

**Issue by aod7br** [chriskiehl/Gooey#507]
Just a question (or a feature request):

Does Gooey works with other python cli parsers?  
Like:

[Click](https://click.palletsprojects.com/en/7.x/)

and

[Docopt](http://docopt.org/)

thanks for any answer!

**Comment by chriskiehl** [comment]
Howdy,

Unfortunately not. You can checkout [this issue](https://github.com/chriskiehl/Gooey/issues/478) for the official reason. Short answer is: time/maintenance commitment required to make it and keep it up to date
