### ISSUE TITLE
Feature request: allow atexit-style application cleanup

### ISSUE THREAD

**Issue by methanm** [chriskiehl/Gooey#508]
I occasionally use Gooey to wrap CLI apps for internal distribution (primarily on Windows, but also some Linux).  I recently had to wrap a script that runs until canceled.  Prior to program exit, it tabulates some data and generates a graph.  I handle the graphing as a post-termination cleanup through the ``atexit`` module (but I have also trapped ``SIGKILL`` and ``SIGTERM`` to see if that works).

When the Gooey wrapper stops the underlying process, it appears that the ``atexit`` hooks aren't performed; and (apparently) due to wxWindow signal / exit handling in ``onClose``, none of my efforts at writing a signal handler work, either.  It would be nice to be able to inject a function call prior to destroying the wrapper for any application-land cleanup.

OS:  Linux and Windows
Python 3.7+

**Comment by chriskiehl** [comment]
Yeah, this is a good call out. It's in the backlog of things to get done -- I forgot about it until now. Original issue [is here](https://github.com/chriskiehl/Gooey/issues/232). Closing this one in favor of the original. 

I'll get it into the next release! :+1:

**Comment by methanm** [comment]
> Yeah, this is a good call out. It's in the backlog of things to get done -- I forgot about it until now. Original issue [is here](https://github.com/chriskiehl/Gooey/issues/232). Closing this one in favor of the original.
> 
> I'll get it into the next release! 👍

Thanks a bunch, Chris!  I'll dig at this if I have some extra time and see about submitting a patch, but it'll be delayed.
