### ISSUE TITLE
MultiFileChooser Desired Syntax

### ISSUE THREAD

**Issue by spot92** [chriskiehl/Gooey#509]
Is it possible to change the options in a way to have the different files chosen using the MultiFileChooser widget separate the files by a , and not by a ;   ?

**Comment by chriskiehl** [comment]
Nah, it defaults to `os.pathsep`. You could, in theory, override _that_, but... it's probably safer to just call `.replace(os.pathsep, 'your_desired_separator_here')` in your app code.
