### ISSUE TITLE
MultiFileChooser File Order

### ISSUE THREAD

**Issue by spot92** [chriskiehl/Gooey#510]
In MultiFileChooser, I am noticing that it always lists files alphabetically. Is there an option to have it list them in the order in which I selected them? I sometimes want them in a very specific order.

Edit: it appears to do so only when the number of files is greater than 2.

**Comment by chriskiehl** [comment]
Unfortunately not. The file dialogs are all managed by WxPython. I double checked the [docs](https://wxpython.org/Phoenix/docs/html/wx.FileDialog.html), but there's no handle for controlling file order. Sorry!
