### ISSUE TITLE
Fix simple typo: overriden -> overridden

### ISSUE THREAD

**Issue by timgates42** [chriskiehl/Gooey#515]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine gooey/gui/components/widgets/richtextconsole.py.
2. Search for `overriden`.

# Expected Behaviour

1. Should read `overridden`.

**Comment by chriskiehl** [comment]
[Fixed](7330fcefac8a259d4dd0c52ff2fec44df1b09a4e) : )
