### ISSUE TITLE
Mutually exclusive group: initial selection not enable edit box 

### ISSUE THREAD

**Issue by belmat** [chriskiehl/Gooey#517]
- OS: Windows10
- Python: 3.5
- Goeey: 1.0.3

```
group = parser.add_mutually_exclusive_group(required=True, gooey_options={"initial_selection": 0})
group.add_argument("-b", type=str)
group.add_argument("-d", type=str, widget="DateChooser")
```

When starting script with these options, the edit box linked to -b argument is not enable

![image](https://user-images.githubusercontent.com/9808839/71349326-0bee8500-256f-11ea-9200-ae83c1f0fd85.png)

**Comment by chriskiehl** [comment]
Fixed on the release branch here: https://github.com/chriskiehl/Gooey/commit/8ecf4c1245dda55c2bc0579b9460dd6b21e3b820
