### ISSUE TITLE
Subparsers with aliases are duplicated in the action column

### ISSUE THREAD

**Issue by pawamoy** [chriskiehl/Gooey#518]
- [x] OS: Windows 10
 - [x] Python Version: 3.6
 - [x] Gooey Version: 1.0.3
 - [x] Thorough description of problem
     - [x] Expected Behavior: list subparsers without duplicates for aliases
     - [x] Actual Behavior: a subparser with one or more aliases gets displayed twice in the action column: once with its name, and a second time with the name of the package and its name. Example: `pause` and `aria2p pause`.
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!)

```python
import argparse
from gooey import Gooey


@Gooey
def main():
    parser = argparse.ArgumentParser(prog="aria2p")
    subparsers = parser.add_subparsers(dest="subcommand", metavar="", prog="aria2p")
    subcommand_help = "Show this help message and exit."

    def subparser(command, text, **kwargs):
        sub = subparsers.add_parser(command, add_help=False, help=text, description=text, **kwargs)
        sub.add_argument("-h", "--help", action="help", help=subcommand_help)
        return sub

    pause_parser = subparser("pause", "Pause downloads.", aliases=["stop"])
```

 - [x] Screenshot (if visual quirk)
![aria2p_gooey](https://user-images.githubusercontent.com/3999221/71729151-48f42a80-2e3f-11ea-9ed3-3ac9412c52c1.png)

As you can see in the screenshot, every subparser with one or more aliases is duplicated.

 - [x] Anything else you may think will be helpful

**Comment by chriskiehl** [comment]
I think your code sample got cut off. Could you update with a complete example that demos the problem? 

Thanks!

**Comment by pawamoy** [comment]
Well, I'm having trouble writing a minimum reproducible example. You can see the complete code at https://github.com/pawamoy/aria2p/blob/master/src/aria2p/cli.py#L134

**Comment by chriskiehl** [comment]
Closing. Feel free to reopen if you can create a runnable example.
