### ISSUE TITLE
Non-ASCII output hangs execution in PyInstaller packaged app

### ISSUE THREAD

**Issue by simplynail** [chriskiehl/Gooey#520]
- [Windows 10] OS
 - [3.7.3 ] Python Version 
 - [1.0.3] Gooey Version 
 - [3.5] PyInstaller

Hi,
I'm having problem with running Gooey app packaged with PyInstaller. App prints some outputs to multi line textbox in "execution screen" but then hangs.
App runs with no issues when running it non-packaged.
I dug into it and appears the problem is with further printing to multi line box.

Traceback:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "lib\site-packages\gooey\gui\processor.py", line 71, in _forward_stdout
  File "lib\site-packages\gooey\gui\processor.py", line 84, in _extract_progress
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 16: invalid continuation byte
```

Changing `stdout` to the following fixed the problem:
```
utf8_stdout = os.fdopen(sys.stdout.fileno(), mode='w', encoding='utf-8', closefd=False)
sys.stdout = utf8_stdout
```

The issue seems to be related to this closed issue #230

**Comment by simplynail** [comment]
actually the problem still stands, as I would like to package app to one file with no console.
applying the fix to sys.stdout (mentioned above) helps just for building `--onefile` without `--noconsole` flag
however with `--noconsole` flag, Gooey doesn't even start because I get
> Fatal error: failed to execute script

**Comment by maxhaz** [comment]
I have a similar issue here.
I package my application on a **Windows 10 'utf-8'** and the gooey GUI hangs (freeze without display) if run on a **Windows 10 'cp932'** computer (Japanese).

(note that to know the Windows system encoding, you can type in a powershell terminal `[System.Text.Encoding]::Default `)

**Comment by maxhaz** [comment]
For what it worth, here is the work around I found.

In `Lib>site-packages>gooey>gui>processor.py`, I added `import local` near the top of the file, and I replaced in `__init__`:

 `self.encoding = encoding`

 by

 `self.encoding = locale.getpreferredencoding()`.

The purpose is to by-pass the Gooey encoding setting  and force to use the local system encoding for stdin and stdout when creating the subprocess.

(Note that other ways to get the system encoding, namely `sys.getdefaultencoding(), sys.getfilesystemencoding(), sys.stdout.encoding, sys.stdin.encoding` do not seem to work when used with `pyinstaller`, probably because pyinstaller freeze their value to the 'dev machine' system encoding instead of allowing to use the target machine system encoding)

**Comment by simplynail** [comment]
Thanks, I'll give it a go soon, sounds like a solution.
Till now I needed to walk it around andrun gooey with console and hide its window just after program starts

**Comment by simplynail** [comment]
I'm using Eng version of Windows but with Polish keyboard and localisation settings, so sounds like it can be a similar case. Will check System.Text.Encoding

**Comment by maxhaz** [comment]
The solution I proposed as an important limitation though:
 It does not allow to display character in the 'status text box' that does not exist in the locale system encoding. 

A solution similar to your original one is to reconfigure the system encoding:
```
sys.stdout.reconfigure(encoding='utf-8')
sys.stdin.reconfigure(encoding='utf-8')
```

but still, it does not allow to use pyinstaller in `--windowed` mode.

How did you manage to hide the console in `--console` mode?

**Comment by maxhaz** [comment]
Following this [great resource](http://www.macfreek.nl/memory/Encoding_of_Python_stdout), it seems that using the `codecs` module to redirect `stdout` and `stderr`  works. 

1. Forget about the modification of `processor.py`
2. Add near the top of your (main) script:

```
import codecs

if sys.stdout.encoding != 'UTF-8':
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
if sys.stderr.encoding != 'UTF-8':
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')
```

If this works for you, that could be the solution.

**Comment by simplynail** [comment]
great, thanks - solution with `condecs` works!

I also tried modifying `process` within gooey package, to use `locale.getpreferredencoding()` , but this didn't work.
my `[System.Text.Encoding]::Default` output is:

> IsSingleByte      : True
> BodyName          : iso-8859-2
> EncodingName      : Central European (Windows)
> HeaderName        : windows-1250
> WebName           : windows-1250
> WindowsCodePage   : 1250
> IsBrowserDisplay  : True
> IsBrowserSave     : True
> IsMailNewsDisplay : True
> IsMailNewsSave    : True
> EncoderFallback   : System.Text.InternalEncoderBestFitFallback
> DecoderFallback   : System.Text.InternalDecoderBestFitFallback
> IsReadOnly        : True
> CodePage          : 1250

Thanks for helping out!

**Comment by ManuelFort** [comment]
thanks maxhaz!

**Comment by zllebron3wade** [comment]
thanks maxhaz!

**Comment by Jakkwj** [comment]
> `locale.getpreferredencoding()`.

This is the only way to solve my problem, as  I am using:
 - [Windows 7] OS
 - [3.8.6 ] Python Version 
 - [ 1.0.8.1] Gooey Version 
 - [ 4.7] PyInstaller Version

**Comment by Jakkwj** [comment]
> This is the only way to solve my problem, as I am using:
> 
> * [Windows 7] OS
> * [3.8.6 ] Python Version
> * [ 1.0.8.1] Gooey Version
> * [ 4.7] PyInstaller Version

**Comment by Jakkwj** [comment]
https://github.com/chriskiehl/Gooey/issues/520#issuecomment-576155188
> For what it worth, here is the work around I found.
> 
> In `Lib>site-packages>gooey>gui>processor.py`, I added `import local` near the top of the file, and I replaced in `__init__`:
> 
> `self.encoding = encoding`
> 
> by
> 
> `self.encoding = locale.getpreferredencoding()`.
> 
> The purpose is to by-pass the Gooey encoding setting and force to use the local system encoding for stdin and stdout when creating the subprocess.
> 
> (Note that other ways to get the system encoding, namely `sys.getdefaultencoding(), sys.getfilesystemencoding(), sys.stdout.encoding, sys.stdin.encoding` do not seem to work when used with `pyinstaller`, probably because pyinstaller freeze their value to the 'dev machine' system encoding instead of allowing to use the target machine system encoding)




This is the only way to solve my problem, as I am using:
[Windows 7] OS
[3.8.6 ] Python Version
[ 1.0.8.1] Gooey Version
[ 4.7] PyInstaller Version

BTW, it should be `import locale`

**Comment by shangqiuping** [comment]
> Following this [great resource](http://www.macfreek.nl/memory/Encoding_of_Python_stdout), it seems that using the `codecs` module to redirect `stdout` and `stderr` works.
> 
> 1. Forget about the modification of `processor.py`
> 2. Add near the top of your (main) script:
> 
> ```
> import codecs
> 
> if sys.stdout.encoding != 'UTF-8':
>     sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
> if sys.stderr.encoding != 'UTF-8':
>     sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')
> ```
> 
> If this works for you, that could be the solution.

I have a same problem recently, I used this solution fixed my problem when I use "pyinstaller -F myfile.py",  But when I change to use "pyinstaller -F myfile.py -w",  another problem arise, the window show the following information:
Traceback (most recent call last):
  File "myfile.py", line 8, in <module>
AttributeError: 'NoneType' object has no attribute 'encoding'

**Comment by anbergem** [comment]
> For what it worth, here is the work around I found.
> 
> In `Lib>site-packages>gooey>gui>processor.py`, I added `import local` near the top of the file, and I replaced in `__init__`:
> 
> `self.encoding = encoding`
> 
> by
> 
> `self.encoding = locale.getpreferredencoding()`.
> 
> The purpose is to by-pass the Gooey encoding setting and force to use the local system encoding for stdin and stdout when creating the subprocess.
> 
> (Note that other ways to get the system encoding, namely `sys.getdefaultencoding(), sys.getfilesystemencoding(), sys.stdout.encoding, sys.stdin.encoding` do not seem to work when used with `pyinstaller`, probably because pyinstaller freeze their value to the 'dev machine' system encoding instead of allowing to use the target machine system encoding)

Instead of altering the package (should this ever be done...?), you can use the `encoding` argument provided by `gooey.Gooey`:
```py
import locale

@gooey.Gooey(encoding=locale.getpreferredencoding())
def run():
    ...
```

The argument is a `kwargs` provided argument, that is eventually sent in as an argument to the `ProcessController` in ` processor.py`.

**Comment by SymmFz** [comment]
> > For what it worth, here is the work around I found.
> > In `Lib>site-packages>gooey>gui>processor.py`, I added `import local` near the top of the file, and I replaced in `__init__`:
> > `self.encoding = encoding`
> > by
> > `self.encoding = locale.getpreferredencoding()`.
> > The purpose is to by-pass the Gooey encoding setting and force to use the local system encoding for stdin and stdout when creating the subprocess.
> > (Note that other ways to get the system encoding, namely `sys.getdefaultencoding(), sys.getfilesystemencoding(), sys.stdout.encoding, sys.stdin.encoding` do not seem to work when used with `pyinstaller`, probably because pyinstaller freeze their value to the 'dev machine' system encoding instead of allowing to use the target machine system encoding)
> 
> Instead of altering the package (should this ever be done...?), you can use the `encoding` argument provided by `gooey.Gooey`:
> 
> ```python
> import locale
> 
> @gooey.Gooey(encoding=locale.getpreferredencoding())
> def run():
>     ...
> ```
> 
> The argument is a `kwargs` provided argument, that is eventually sent in as an argument to the `ProcessController` in ` processor.py`.

Thanks, @anbergem. Your advice worked perfectly, and it’s a neat solution.
