### ISSUE TITLE
the DirChooser will block all the time after importing the pywinauto by using the widget_demo.py !

### ISSUE THREAD

**Issue by RyanLiuF** [chriskiehl/Gooey#521]
- As the title describe, the DirChoose will block all the time after importing the pywinauto.

- Meanwhile, I'm trying to fix this problem. 

- Does anyone encounter the kind of problem ?

Thanks! ^_^

**Comment by cal97g** [comment]
Surely it should block? You don't want to be doing anything else until the directory has been chosen?

**Comment by RyanLiuF** [comment]
It could not select any directory！Just block.




祝工作愉快！
刘凡 | Zachary (C/C++)软件工程师
Mobile：(+86)183 0201 6719
Address：长沙市雨花区
E-mail：ryanliuf@126.com
On 01/08/2020 21:27, Callam wrote:

Surely it should block? You don't want to be doing anything else until the directory has been chosen?

**Comment by maxim-sermin** [comment]
I have the same issue with pywinauto + DirChooser. The window just freezes forever after clicking the "Browse" button. Using MultiDirChooser instead is a good enough workaround for me though.
