### ISSUE TITLE
Add ColorChooser widget

### ISSUE THREAD

**Issue by conradhilley** [chriskiehl/Gooey#523]
Add a `ColorChooser` widget option via `wx.ColourDialog`. 

Example below where hex is returned from the chooser and the input dialogs are colored such that their background and text colors match the selected color.

![image](https://user-images.githubusercontent.com/21027844/72227206-91ea6400-354e-11ea-90d5-d709a13fd0f8.png)

![image](https://user-images.githubusercontent.com/21027844/72227182-4b950500-354e-11ea-9983-056fd8a5f976.png)

**Comment by chriskiehl** [comment]
Merged. :+1:
