### ISSUE TITLE
Bug: Tickmarks do not work if specific default arguments are given

### ISSUE THREAD

**Issue by luc35** [chriskiehl/Gooey#526]
Great work!

 - [win 10 ] OS
 - [CPython 3.7.1 ] Python Version 
 - [?] Gooey Version  Could not find this, where is it documented?  It was downloaded januari 2020. 
 - [ ] Thorough description of problem 

Tickmarks (action='store_true' or action='store_false') do not work if default arguments are given, try this example:

   from gooey import Gooey, GooeyParser
    
    @Gooey()
    def gui():
        parser = GooeyParser(description='Process')

        parser.add_argument(
            '-f', '--foo',
            metavar='Some Flag1',
            action='store_true',
            default=True)  #BUG: always yields True!  (works only when default=False)
        
        parser.add_argument(
            '-b', '--bar',
            metavar='Some Flag2',
            action='store_false',
            default=False)  #BUG: always yields False!  (works only when default=True)

        args = vars(parser.parse_args())
        return args

    if __name__ == '__main__'
        var=gui()
        print('var:',var) #<--watch output to see the bug

**Comment by chriskiehl** [comment]
This is not a bug. Argparse is doing exactly what you're asking it too. I've seen others get tripped up by this in the past. Argparse can be a little unintuitive at times.  

For starters, you can verify that Gooey is doing the right thing by dumping out `sys,argv`. It dutifully passes along the params as when they're checked. 

For instance, if both are checked: 

```['issue526.py', '-f', '-b']```

if one is checked: 

```[issue526.py', '-f']```

None are checked

```[issue526.py', '-f']```


Note that CLI flags are either present or not. 

Now, in your code, you ask Argparse to store `True` when `-f` is present the arguments. You `default` to `True` if it is _not_ present in the args. This is not a bug, you've just prevented it from varying regardless of what gets sent. 

Ditto for the `-b` param. If present: False, if not present.... also False.
