### ISSUE TITLE
Add documentation for Richtext controls

### ISSUE THREAD

**Issue by sundayj** [chriskiehl/Gooey#527]
Hello,

Would it be possible to get some extra clarification on the rich text controls config parameter? Like, what does that allow us to do within the use of Gooey? Can you provide an example?

Thank you!

**Comment by chriskiehl** [comment]
You can check out some runnable code in the examples repo here: https://github.com/chriskiehl/GooeyExamples/blob/master/examples/richtext_demo.py

I'll leave this open as a TODO for adding better documentation.

**Comment by eladeyal-intel** [comment]
![image](https://user-images.githubusercontent.com/20379005/74504853-366d1680-4efe-11ea-8270-2cbaf6a41d3d.png)

**Comment by sundayj** [comment]
Thanks guys! This is exactly what I was looking for!

**Comment by chriskiehl** [comment]
Additional docs added here: https://github.com/chriskiehl/Gooey/blob/1.0.4-release/docs/Using-Richtext-Controls.md
