### ISSUE TITLE
How to specify elgible filetypes when using the FileChooser widget

### ISSUE THREAD

**Issue by fgs-dbudwin** [chriskiehl/Gooey#533]
This isn't a bug, but a help request.  I am on Windows 10, using Python 3.8 with Gooey 1.0.3.  I am using a `FileChooser` widget like so:

```
inputs_group.add_argument(
        "-f",
        "--file",
        dest="file",
        required=True,
        type=argparse.FileType("r"),
        help="Path to CSV file",
        widget="FileChooser")
```

I want to restrict the types of files I can choose when the widget opens to only allow CSV files.  How can I adjust the `All files (*.*)` dropdown in Windows to only allow CSV files.  Right now, `All files (*.*)` is the only option in the dropdown menu.

![Inkedcanvas_LI](https://user-images.githubusercontent.com/14611316/75780365-31df9500-5d29-11ea-9eca-ec1d346f7397.jpg)

**Comment by eladeyal-intel** [comment]
https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md#file-and-folder-choosers
