### ISSUE TITLE
Uncheck checkboxes when hitting edit

### ISSUE THREAD

**Issue by Musakuu** [chriskiehl/Gooey#534]
Hello everyone,

This is my first time posting on github (and my first major project). I have been learning python for about 2 months now, so I am still struggling with a lot of things. 

I am trying to make gooey uncheck the checkboxes after I hit the restart button after the program has finished. I built a taxi optimizer where you select the places for the taxis to go for day 1 then it prints them onto an excel file. Then you hit restart and select different places and it will print out day 2. 

By searching through the gooey files I found the event WINDOW_EDIT in \gooey\gui\containers\application.py. It directs to **def onEdit(self):**

I have tried changing so many things but I can't get it to work. Any advice from anyone would be greatly appreciated.

Thanks a lot.

Ps. This is an amazing tool. Thanks for your hard work.

**Comment by chriskiehl** [comment]
`OnEdit` is indeed where you'd probably hook into for such a feature. In that same file, you'll find reference to something called `configs`, these house the actual widgets (see: `reifiedWidgets`). You could probably expose a method called `reset` or something which handles the actual clearing out of your check boxes. 

```python
def onEdit():
    for config in self.configs: 
        for config.reset()
```

Where reset is something like..

```python 
for widget in self.reifiedWidgets:
    widget.setValue(None)
```

Good luck!

**Comment by Musakuu** [comment]
Thanks alot Chris, I have never seen object orientated programming before seeing gooey. I actually am learning wxpython because that's what you use here. I ended up making my own GUI now. 

To kill some isolation time I implemented your instructions. I want to just clarify what I did exactly so that way other people can do the same if they need it. I'm sure I haven't done anything perfectly, so if anyone out there wants to point out a better way please share it here. 

**Step 1: Make a new method in gui\config.py.**
```
def resetCheckBox(self):
   for widget in self.reifiedWidgets:
      try:
         widget.setBox(None)
      except:
         pass
```
I put this underneath the **def hideErrors(self)** block.

In Chris' original method, it would set all the widget's values to None. This made my text boxes all display none and threw an error whenever something didn't have the method .setValue. 

To fix the error, I used try and except. You can learn more about that [here](https://www.w3schools.com/python/python_try_except.asp). 

To fix the part where everything said None, I made a new method called  .setBox. More on that below.

**Step 2: Making .setBox in gui\components\widgets\checkbox.py**

```
def setBox(self, value):
   self.widget.SetValue(value)
```
I put this right under the **def SetValue(self, value)** block. (yes setBox is very similar to setValue)

This will be the only widget with this method, so we can call it across all the widgets and this will be the only one that is affected.


**Step 3: Adding resetCheckBox to onEdit in gui\containers\application.py**

```
def onEdit(self):
    self.config.resetCheckBox()
    """Return the user to the settings screen for further editing"""
    with transactUI(self):
        if self.buildSpec['poll_external_updates']:
            self.fetchExternalUpdates()
        self.showSettings()
```
We are just attaching to Chris' code here. Make sure you do call it before you showSettings or you won't see the changes you made. 

I hope that this tiny guide will help someone if they have a similar problem.


############## Side Note#############
Thanks a lot for doing this project @chriskiehl . I have learned a lot from looking at your work and try to organize my own GUIs in the same way. You have made this simple mechanical engineer very happy. It's so easy to make a good GUI with gooey. If our paths ever cross, I'll buy you a beer :D
