### ISSUE TITLE
[Question] New arguments after finished running

### ISSUE THREAD

**Issue by MrSassyBritches** [chriskiehl/Gooey#535]
After the program has finished processing my script, I would like it to open a new window to take new arguments. So take argument A, run. Then instead of closing or restarting, take new arguments and then run one more time.

I thought this snippet I made would work, but it just runs them both when I hit start.
 import sys
from gooey import Gooey, GooeyParser

```
@Gooey
def the_goo():
    goo = GooeyParser(description="Addition")
    goo.add_argument('Digit 1')
    goo.add_argument('Digit 2')

    goo.parse_args()
    digit_1 = sys.argv[2]
    digit_2 = sys.argv[3]
    print(digit_1)
    print(digit_2)
    print(f"{digit_1} + {digit_2} = ", int(digit_1) + int(digit_2))


def the_blob():
    blob = GooeyParser(description="Subtraction")
    blob.add_argument('Digit 1')
    blob.add_argument('Digit 2')

    blob.parse_args()
    digit_1 = sys.argv[2]
    digit_2 = sys.argv[3]
    print(digit_1)
    print(digit_2)
    print(f"{digit_1} - {digit_2} = ", int(digit_1) - int(digit_2))


the_goo()
the_blob()

```

I wasn't sure how to ask this, so I apologize if this duplicates another Issue.
Fantastic project by the way 😄

**Comment by chriskiehl** [comment]
So, there's not a directly supported way of accomplishing what you're after, atm. The exact details of why are a little hard to explain without going into the depths of the Gooey life-cycle. In short, wizard like functionality, where you have steps which get processed, isn't something Gooey can do. 

As a long shot, _if_ the processes are independent of each other and _if_ they're called only for their side effects, then you can kind of fake it by invoking each via subprocess if put them in different files. 

**Step A:**

```python
from gooey import Gooey, GooeyParser
import sys

@Gooey
def the_goo():
    goo = GooeyParser(description="Addition")
    goo.add_argument('Digit 1')
    goo.add_argument('Digit 2')

    goo.parse_args()
    digit_1 = sys.argv[2]
    digit_2 = sys.argv[3]
    print(digit_1)
    print(digit_2)
    print(f"{digit_1} + {digit_2} = ", int(digit_1) + int(digit_2))

the_goo()
```

**Step B:** 

```python
from gooey import Gooey, GooeyParser
import sys

@Gooey
def the_blob():
    blob = GooeyParser(description="Subtraction")
    blob.add_argument('Digit 1')
    blob.add_argument('Digit 2')

    blob.parse_args()
    digit_1 = sys.argv[2]
    digit_2 = sys.argv[3]
    print(digit_1)
    print(digit_2)
    print(f"{digit_1} - {digit_2} = ", int(digit_1) - int(digit_2))

the_blob()
```

**Coordinating the invocations:**

```python 
import subprocess

subprocess.call('python ./a.py')
subprocess.call('python ./b.py')
```

Probably not what you're ultimately after, but I leave it as a clunky _semi_ work around ^_^
