### ISSUE TITLE
add_argument returns None instead of argparse.Action

### ISSUE THREAD

**Issue by donaldst** [chriskiehl/Gooey#537]
When adding an argument to a parser with add_argument, argparse will return the Action associated with the argument. This functionality is lost in GooeyParser's add_argument function.

While not well documented in the Python docs, this is a powerful feature of Argparse and not having it blocks (or at least makes more difficult than necessary) some in-depth use of custom Actions with Gooey.

**Comment by chriskiehl** [comment]
You fix was merged here : https://github.com/chriskiehl/Gooey/pull/538
