### ISSUE TITLE
when l install gooey ,numpy is also installed,it make my exe too big

### ISSUE THREAD

**Issue by renmu123** [chriskiehl/Gooey#539]
OS:win10
Python Version: 3.7 
Gooey Version: 1.0.3 

l use virtualenv for my python environment 
when package my exe with pyinstaller, l found it is too big(about 200m)。
l checked installed packages and found numpy has been installed by gooey.
l try to exclude this import, but after do this,my exe do not work well.
l found some information about this, but do not work.

Thanks very much for your time on this

**Comment by chriskiehl** [comment]
`numpy` is a dependency of wxPython: https://github.com/wxWidgets/Phoenix/blob/master/requirements/install.txt 

So, unfortunately, there's nothing I can do to remove it for ya.
