### ISSUE TITLE
possible issue with wxpython April24 update?

### ISSUE THREAD

**Issue by bradh11** [chriskiehl/Gooey#549]
- [windows 10 ] OS
 - [ 3.8.2] Python Version 
 - [1.0.3 ] Gooey Version 
 - [ It seems i have a bug in code that was working until recently.  The error happens upon launch.  Code runs perfectly without the @Gooey decorator] Thorough description of problem 
     - [ launch gui for my argparse app] Expected Behavior 
     - [ stacktrace] Actual Behavior 
 - [see below for error ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [n/a - gui doesnt launch ] Screenshot (if visual quirk) 
 - [ I think this is related to yesterdays wxpython 4.1.0 update...] Anything else you may think will be helpful 

 ```
$ python cucm-exporter.py 
status: starting 2020-04-25 08:41:26.255955
Traceback (most recent call last):
  File "cucm-exporter.py", line 287, in <module>
    main()
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "cucm-exporter.py", line 214, in main
    cli_args = parser.parse_args()
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\python_bindings\gooey_parser.py", line 114, in parse_args
    return self.parser.parse_args(args, namespace)
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 82, in run_gooey
    application.run(build_spec)
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\gui\application.py", line 21, in run
    app = build_app(build_spec)
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\gui\application.py", line 30, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\gui\containers\application.py", line 42, in __init__
    self.header = FrameHeader(self, buildSpec)
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\gui\components\header.py", line 33, in __init__
    self.layoutComponent()
  File "C:\Users\bradh\Documents\code\cucm-exporter\.venv\lib\site-packages\gooey\gui\components\header.py", line 75, in layoutComponent
    sizer.Add(headings_sizer, 1,
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_HORIZONTAL)" failed at ..\..\src\common\sizer.cpp(2106) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
```
pip libraries
```
$ pip list
Package           Version   
----------------- ----------
appdirs           1.4.3
attrs             19.3.0
autopep8          1.5.2
cached-property   1.5.1
certifi           2020.4.5.1
chardet           3.0.4
ciscoaxl          0.156
ciscoris          0.0.5
colored           1.4.2
defusedxml        0.6.0
Gooey             1.0.3
idna              2.8
isodate           0.6.0
lxml              4.5.0
numpy             1.18.3
Pillow            7.1.1
pip               20.0.2
psutil            5.7.0
pycodestyle       2.5.0
pytz              2019.3
requests          2.22.0
requests-toolbelt 0.9.1
setuptools        41.2.0
six               1.12.0
urllib3           1.23
wxPython          4.1.0
zeep              3.4.0
```
Thanks! ^_^

**Comment by bernizt** [comment]
Same issue here, under the same conditions. I managed to get Gooey running by downgrading wxPython to 4.0.7

`pip install wxPython==4.0.7`

**Comment by bradh11** [comment]
Yes.    I did the same with success.    Pinned WxPython at the older 4.0.7 revision. I only noticed it because my github actions was building from scratch and my local dev environment had the older WxPython still.    Once I put two and two together I realized what was going on.    
  

  
  
  

  
  
>

**Comment by chriskiehl** [comment]
Thanks for pointing this out! 

A minor version bump that silently breaks backwards compatibility is just, like, _peak_ modern software. >:( 

I'm the dummy here for relaxing the deps in `setup.py` which allows these sorts of things to happen. Lesson learned! Apologies for the instability. 

I cut a quick release that downgrades [wxpython to 4.0.7](https://github.com/chriskiehl/Gooey/releases/tag/1.0.3.1-hotfix). I'm still looking into whether or not removing the `sizer` options `Wx` is suddenly complaining about causes any visual regressions on Gooey's side.  

I'll also cut a ticket with the Wx project shortly. The [release notes](https://wxpython.org/news/2020-04-24-wxpython-410-release/index.html) don't specifically mention any breaking changes, but I do see [this issue from last year](https://github.com/wxWidgets/Phoenix/issues/1270) which has the general guidance of updating as the right path, so... we'll see if this is a blip in wx or something long term.

**Comment by chriskiehl** [comment]
Wx issue [here](https://github.com/wxWidgets/Phoenix/issues/1612) 

On a more careful reading of the notes, it does mention removal of deprecations, but this seems unrelated to any warnings generated by WX for previous versions.  So, 🤷 we'll see what the WX folks say.
