### ISSUE TITLE
MultiDirChooser does not handle Windows volume labels correctly

### ISSUE THREAD

**Issue by besslwalker** [chriskiehl/Gooey#553]
- [x] OS - Windows 7
 - [x] Python Version - 3.8
 - [x] Gooey Version - 1.0.3 (with fix for Issue #550)
 - [x] Thorough description of problem 
     - [x] Expected Behavior 
After choosing a directory (or more) in the MultiDirChooser, I should be able to use the value of the argument as a valid directory name on the system.
     - [x] Actual Behavior 
Attempting to use the argument value as a directory name gives me this message:

> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'Media (E:)\\Users\\My Name\\Music'

I imagine this ought to be just E: as the volume label, not Media(E:).

 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
Run the following on a Windows machine, selecting at least one directory. Observe the error message in the output window.

```
import os

from gooey import Gooey
from gooey import GooeyParser

@Gooey
def main(args):
    parser = GooeyParser()
    parser.add_argument("dirnames", nargs = "+", widget="MultiDirChooser")
    args = parser.parse_args(args)

    # try to access the given path
    os.listdir(args.dirnames[0])

if __name__ == '__main__':
    import sys
    main(sys.argv[1:])
```

 - [x] Screenshot (if visual quirk) - N/A, incorrect volume syntax appears in GUI as well.
 - [x] Anything else you may think will be helpful 
 The plain 'ol DirChooser does not have this problem.

I'm investigating and will hopefully have a pull request for you soon.

**Comment by besslwalker** [comment]
This appears to be how wx.lib.agw.multidirdialog provides the directories; Gooey is not doing anything wrong here.

**Comment by besslwalker** [comment]
And that appears to be a consequence of wx.lib.agw.multidirdialog having volume labels in its chooser.

Since wx.lib.agw.multidirdialog hasn't seen changes since 2012, I assume this is the correct behavior for it. However, it's very bad behavior for Gooey, so probably Gooey should add some additional massaging to the output of the wx dialog.

**Comment by chriskiehl** [comment]
Pull request now merged! Thanks for the fix!
