### ISSUE TITLE
`pip install -U gooey` does not solve #549 for me

### ISSUE THREAD

**Issue by qm2k** [chriskiehl/Gooey#556]
>README: Are you suddenly seeing errors related to Alignmnet flags when starting Gooey? Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Yes, I'm seeing exactly this problem, but `pip install -U gooey` does not solve the problem for me, since it only installs version 1.0.3. Downgrading wxpython with `pip install wxpython==4.0.7` works though.

 - [x] OS: Microsoft Windows 10 Pro, Version 10.0.18363 Build 18363
 - [x] Python Version: 3.7.4 
 - [x] Gooey Version: 1.0.3
 - [x] Thorough description of problem: 
     - [x] Expected Behavior: Gooey works after upgrading to latest version
     - [x] Actual Behavior: Gooey does not work, all my scripts using it no longer work :(((
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!)
```python
#!/usr/bin/env python3
import gooey

@gooey.Gooey
def main():
    parser = gooey.GooeyParser()
    parser.add_argument('filename')
    parser.parse_args()

main()
```
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
Ah, crud, I didn't follow my own release checklist and forgot to update PyPi..

Latest is now pushed! Upgrading should now pick it up now.  

Thanks for letting me know!

**Comment by qm2k** [comment]
Now I'm seeing it, thank you.
