### ISSUE TITLE
Not possible to print over the previously written line in the display section

### ISSUE THREAD

**Issue by jmm5351** [chriskiehl/Gooey#558]
Is it possible when printing to the **display** section of gooey to overwrite the previous printed line. I tried everything I can think of and each printed string gets written to a new line. I tried `print('\rsome string', end='')` and also everything else out there that works in the Windows shell but it will not work with gooey.

**Comment by chriskiehl** [comment]
Nay. It's not something Gooey handles. It's primarily geared towards append only console output.
