### ISSUE TITLE
WindowsError in removing temp files

### ISSUE THREAD

**Issue by lapsed-pacifist** [chriskiehl/Gooey#56]
```python
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Python27\\lib\\site-packages\\gooey-0.1.0-
py2.7.egg\\gooey\\python_bindings\\da56848393418e7c55974af7edbbb2d2.pyc'
```
This just results from the inclusion of the decorator in any program

**Comment by ardoramor** [comment]
I'm getting the same error:

...
    main()
  File "C:\Python27\lib\site-packages\gooey-0.1.0-py2.7.egg\gooey\python_bindings\gooey_decorator.py", line 119, in inner
    parser = get_parser(main_module_path)
  File "C:\Python27\lib\site-packages\gooey-0.1.0-py2.7.egg\gooey\python_bindings\gooey_decorator.py", line 162, in get_parser
    return source_parser.extract_parser(module_path)
  File "C:\Python27\lib\site-packages\gooey-0.1.0-py2.7.egg\gooey\python_bindings\source_parser.py", line 145, in extract_parser
    client_module = modules.load(module_source)
  File "C:\Python27\lib\site-packages\gooey-0.1.0-py2.7.egg\gooey\python_bindings\modules.py", line 33, in load
    os.remove(tmp_pyc_file)
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Python27\\lib\\site-packages\\gooey-0.1.0-py2.7.egg\\gooey\\python_bindings\\e68dbae79cf81af7bd68c8d4b59c07e.pyc'

I have Python 2.7 installed. Installed master Gooey. Seems like it has problem compiling binding?

**Comment by chriskiehl** [comment]
Could you post the code you were attempting to run? Stacktrace alone doesn't give quite enough info.

**Comment by ardoramor** [comment]
import argparse
from gooey import Gooey

@Gooey
def main():
	parser = argparse.ArgumentParser(description='UV Metadata Uploader.')
	parser.add_argument('server_url', 
			help='URL of the UV server where the metadata will be uploaded.')
	parser.add_argument('api_key', 
			help='Server API key that authenticates to an account with permissions to manage metadata of a feed.')
	parser.add_argument('feed_id', type=int, nargs=1, 
			help='ID of the feed for which the metadata will be uploaded.')
	parser.add_argument('gpx_files', type=argparse.FileType('r'), nargs='+', 
			help='File containing GPX metadata that will be uploaded to the UV server.')
	args = parser.parse_args()
	
	print('test')
	# there was more code but this is enough to produce the same error

if __name__ == "__main__":
    main()

**Comment by ardoramor** [comment]
I think I've found the problem. I didn't have exit() at the end. It now works.

**Comment by chriskiehl** [comment]
So.. Safe to close? :)

**Comment by piksel** [comment]
Well, the error is not really descriptive. This is what generates it:
```python
  try:
    with open(tmp_py_file, 'w') as f:
      f.write(module_source)
    return __import__(tmp_filename)
  finally:
    os.remove(tmp_py_file)
    os.remove(tmp_pyc_file)
```
Which means that if there is an error either creating or importing the code, there is no other feedback than the failure to remove the files.

**Comment by aphorton** [comment]
I saw the same error for tab-indented main() functions. See my pull request for a fix.

This doesn't solve the broader issue, as @piksel pointed out, since other errors can lead to the same place.
