### ISSUE TITLE
Terminal window jumps to top on job completion

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#563]
Is it possible to cause Gooey to keep the output window as-is on job completion? I don't want to jump back to the top of the output as what I am really interested in is at the bottom.

**Comment by chriskiehl** [comment]
Which platform, version, etc..? 

It does this for any output? Do you have an example case? 

Gooey doesn't contain any logic for snapping things back to the top on finish. So, you seeing that behavior is definitely out of the norm

**Comment by bje-** [comment]
Given that this isn't expected, I'll gather some more details.

 - [Ubuntu 18.04 ] OS
 - [3.6.9 ] Python Version
 - [1.0.3.1] Gooey Version
 - [4.0.7] wxPython

I will try to create a small reproduceable test case.

**Comment by bje-** [comment]
Test case:

```
import argparse
from gooey import Gooey

@Gooey()
def process_options():
    parser = argparse.ArgumentParser()
    parser.add_argument('num', type=int, default=100)
    return parser.parse_args()

args = process_options()

for i in range(args.num):
  print(i)
```

**Comment by eladeyal-intel** [comment]
@bje- is this different for "rich console" and regular console? (i.e. replace `@Gooey()` with `@Gooey(richtext_controls=True)` ).  It might be your workaround.

On my setup (Windows 10) I do not experience this behavior.

**Comment by bje-** [comment]
That does work, thanks @eladeyal-intel. It is potentially a workaround, although I would prefer things to work without it.

**Comment by bje-** [comment]
Reproduced on Ubuntu 20.04.

**Comment by bje-** [comment]
Through trial and error, I have come up with some clues. It seems that freezing and thawing the `TextCtrl` widget might cause it to reset the insertion position to 0. This hack (`diff -w` output shown) fixes the problem by avoiding `transactUI`, but I realise this is probably not the right fix. I hope this is helpful.

```
index 9147b26..7c436e0 100644
--- a/gooey/gui/containers/application.py
+++ b/gooey/gui/containers/application.py
@@ -125,7 +125,6 @@ class GooeyApplication(wx.Frame):
         Display the appropriate screen based on the success/fail of the
         host program
         """
-        with transactUI(self):
         if self.clientRunner.was_success():
             if self.buildSpec.get('return_to_config', False):
                 self.showSettings()
```

**Comment by bje-** [comment]
Any suggestions with how to progress this one?

**Comment by chriskiehl** [comment]
looking into it

**Comment by chriskiehl** [comment]
@bje- 

This appears to be a bug in wxPython itself. I've opened an issue with them [here](https://github.com/wxWidgets/Phoenix/issues/1698) if you wanna check it out. I've attached a small reproducible demo of the problem there. 

You were looking in the right area. Internally,that `transactUI` bit calls `freeze/Thaw` to prevent the UI from flickering as it mounts/unmounts certain elements. This `thaw`ing seems to cause `TextCtrl`s to "forget" their current `insertionPoint` in the UI -- and _only_ in the UI, it remains correctly set in their internal state. 

We'll see what the WX folks say. It's straight forward to patch around, but if the wx timeline is reasonable, I'll wait for upstream to be fixed rather than hacking around it in my codebase .

**Comment by bje-** [comment]
Thanks a lot, that's great for your efforts. In my own application, I am using the rich text control for now as a workaround and that's acceptable.

**Comment by bje-** [comment]
This will be fixed in the widget toolkit in due course. We can close this issue, I think, as it is not a bug in Gooey.

**Comment by chriskiehl** [comment]
@bje- , That was awesome of you to follow up and cut a [ticket](https://trac.wxwidgets.org/ticket/18808#no1) in the wx tracker! Thanks a bunch! 👍
