### ISSUE TITLE
incorrect behaviour for action='version'

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#564]
The following simple example demonstrates the problem:

```
import argparse
from gooey import Gooey

@Gooey()
def process_options():
    parser = argparse.ArgumentParser('foo')
    parser.add_argument('--version', action='version', version='1.0')
    return parser.parse_args()

process_options()
```

This gives:

![Screenshot_2020-05-24_16-28-25](https://user-images.githubusercontent.com/4327840/82747519-037bce00-9ddd-11ea-866a-b7fc8b396c2c.png)

I am expecting to see a checkbox to enable this option, not a text entry field containing `==SUPRESS==`. Presumably this is because the default type in `argparse` is `str` and I have not specified any other type?

I have other options that use the `store_true` action. In these cases, Gooey behaves correctly and shows a checkbox. My usage for `--version` above comes straight from the Python documentation and I would expect it to be a common usage. Can Gooey be made to work correctly when encountering a `version` action?

**Comment by chriskiehl** [comment]
This is related to https://github.com/chriskiehl/Gooey/issues/469. I'm going to close this one and track everything there. Will fix in 1.0.4. 

This is a quirk of Argparse which puts the literal string "==SUPPRESS==" for some arguments. Gooey dutifully shows that string in the UI.
