### ISSUE TITLE
catching errors in progress_expr

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#566]
- [Ubuntu 18.04 ] OS
 - [3.6.9 ] Python Version 
 - [1.0.3.1] Gooey Version 
 - [The progress expression (`progress_expr`) can contain errors that are hard to troubleshoot because Gooey catches every exception the expression may raise. The progress bar just silently fails to operate correctly.] Thorough description of problem 
     - [ I think, on balance, Goorey should allow the exception to propagate up to the mainline so that the user/developer becomes aware of the problem.] Expected Behavior 
     - [ Errors in `progress_expr` are silently discarded. ] Actual Behavior 
 - [ Set `progress_expr=raise(ValueError())`  ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!)

**Comment by chriskiehl** [comment]
Sounds reasonable to me! 

It'd be as a flag you can turn on. Gooey suddenly throwing exceptions when it previously didn't would be no bueno.

**Comment by bje-** [comment]
Fair enough, I suppose.

**Comment by bje-** [comment]
On balance, I think this isn't worth creating yet another flag for. I think the behaviour should instead just be documented.
