### ISSUE TITLE
Using progress_expr with limited progress output

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#567]
This is not a bug report, per se, but an issue for me all the same. :smiley:

The documentation says that `progress_expr` is an expression that can carry out more complex calculations of the progress based on the `progress_regexp` matches. In my application, the calculation is similar to the example of `current / total * 100`. In my case the denominator is not in the output, but is available as an argparse argument entered through the GUI. The `progress_expr` is evaluated within `_eval_progress`.

Can you suggest a way forward? Thanks!

**Comment by chriskiehl** [comment]
Currently, the only way forward is to just include the total in your output so Gooey can pick it up. 

Progress reporting is pretty bare-bones atm. You give it a line of text, it tries to match your regex. It has no knowledge of the wider program's context. That could change in the future, but given that there's generally a path forward by means of just included the stuff you need in the output, it's lower in the list of things to work on for me.
