### ISSUE TITLE
Logical sense of checkboxes is confusing

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#571]
Consider the following example:

```
import argparse
from gooey import Gooey

@Gooey()
def process_options():
    parser = argparse.ArgumentParser()
    parser.add_argument("--enable-foo", action="store_true", help="enable the foo option")
    parser.add_argument("--disable-bar", action="store_false", help="disable the bar option")
    return parser.parse_args()

args = process_options()
```
In the CLI world, the help text tells us that `--disable-bar` will "disable the bar option". The help text tells us what action the option will take (disabling a feature). In the Gooey world, we get:

![Screenshot_2020-05-26_11-21-59](https://user-images.githubusercontent.com/4327840/82851871-89665900-9f44-11ea-93ea-90b98fdab4dd.png)

The UI shows the `--disable-bar` option as a checkbox with the box checked. That is, the option is enabled and unchecking the checkbox will disable it. That's fine, but the help text is unclear now because the help text says "disable the bar option". Users might think, "Does checking the box disable the option or enable it?". Changing the help text (for example, to "bar option") makes it pretty unhelpful for CLI users.

It makes me wonder if it would be best if every boolean option had an unchecked box and that checking the box would be equivalent to passing the option on the command line.

**Comment by eladeyal-intel** [comment]
I'm thinking that you can use just hide `--disable-bar` from the GUI, using `"visible": False`
```
import argparse
from gooey import Gooey, GooeyParser as ArgumentParser

@Gooey()
def process_options():
        parser = ArgumentParser()
        parser.add_argument("--enable-foo", action="store_true", help="enable the foo option")
        parser.add_argument("--disable-bar", action="store_false", help="disable the bar option", gooey_options={"visible": False})
        return parser.parse_args()

args = process_options()
```

![image](https://user-images.githubusercontent.com/20379005/83447705-7fb78680-a459-11ea-87e7-ae1e84edd576.png)

**Comment by bje-** [comment]
Then the user cannot disable the `bar` option at all. The checkbox needs to be there. I'm just saying that if the logical sense of the text and the checkbox is to be consistent, the checkbox default should be "off". Selecting the checkbox would be the equivalent of passing `--disable-bar` on the command line.

**Comment by eladeyal-intel** [comment]
Oh. I gave a good solution to the wrong problem.

When I see this:
![image](https://user-images.githubusercontent.com/20379005/83479570-a3062400-a4a1-11ea-8b60-4a8e18455490.png)
it is clear to me that ☑ means bar is disabled; and ☐ means bar is not disabled.

I think, when you write
```
    parser.add_argument("--disable-bar", action="store_false", help="disable the bar option")
```
it means that `disable-bar` is by default `True`; and if the user specifies `--disable-bar` then the variable `disable-bar` is set to `False`. So the variable `disable-bar` does not hold "bar is disabled" but rather "bar is enabled". So you'd want to add `dest=` there to remove some confusion

**Comment by chriskiehl** [comment]
>checking the box would be equivalent to passing the option on the command line.

This _is_ what Gooey does. 

Argparse's `store_false` is counter intuitive, and people rightly get tripped up by it. `store_false` actually internally sets the default value to `true`. Similarly, `store_true` does the opposite. You can see this in your example if you log the `args`. 

```
Namespace(disable_bar=True, enable_foo=False)
```

They have the opposite values even with no external arguments supplied to the program. 

So, Gooey is doing what you're telling it to do: display a checkbox that defaults to True, and is thus selected. I'd argue that `store_false` is overall "Considered Harmful." Even the semantics within the program are potentially confusing. I'd certainly read a variable called `disable_bar` with a value of `false` to mean _not_ to disable `bar`. That's my $0.02.
