### ISSUE TITLE
Enhancement: Provide option to hide labels

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#573]
In some instances, there is no need to show the labels (ie, the command line options) in the GUI. The help text is sufficient and would lead to a more compact window layout. It would be great if there was a global option to hide the labels.

**Comment by chriskiehl** [comment]
Labels, help text, and widgets themselves can be controlled via [Gooey Options](https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md)
