### ISSUE TITLE
nargs optional arguments not able to add

### ISSUE THREAD

**Issue by ardoramor** [chriskiehl/Gooey#59]
:) sorry for all the reports but I think it just means you have an awesome plugin and people use it!

So when I specify the following argument:
   `parser.add_argument('gpx_files', type=argparse.FileType('r'), nargs='+', 
      help='File containing GPX metadata that will be uploaded to the UV server.')`
I get one input field in the required (which is correct because + means one or more) and an optional but empty fieldset. Is there a way to dynamically add an optional field? Like a [+] button.

Also, it seems that type=file gets a file input widget but argparse.FileType gets just a text input.

**Comment by chriskiehl** [comment]
>Is there a way to dynamically add an optional field? Like a [+] button.

Not currently. You'd want the [+] to spawn a new input widget? Only issue I have with that is that it'd make the spacing in the gui really lopsided. 

>Also, it seems that type=file gets a file input widget but argparse.FileType gets just a text input.

I probably missed a rule in the `argparse_to_json` module. I'll have to update it.

**Comment by chriskiehl** [comment]
`argparse.FileType` is now recognized by the mapper. 

I don't plan on the Nargs button for now as it'd make for a lopsided GUI. But, If you have a mockup, feel free to reopen the issue.
