### ISSUE TITLE
poll_external_updates slows gooey startup

### ISSUE THREAD

**Issue by frederikvs** [chriskiehl/Gooey#591]
We're using the `poll_external_updates` feature to update a dropdown widget. This seems to have slowed down starting gooey up. In some situations it takes around 15-20 seconds to start gooey. (Running `xxx.py gooey-seed-ui` is much faster.)

I've boiled it down to a simple example, filling the dropdown with 500 items.

```
import json
import sys
from pprint import pprint

from gooey import Gooey, GooeyParser

@Gooey( program_name="Using Dynamic Values", poll_external_updates=True)
def main():
    parser = GooeyParser()
    parser.add_argument(
        '--name',
        metavar='name',
        widget='Dropdown',
        choices=['a' for i in range(500)]
    )
    

    args = parser.parse_args()
    pprint(args)

if __name__ == '__main__':
    if 'gooey-seed-ui' in sys.argv:
        l = ['a' for i in range(500)]
        print(json.dumps({'--name': l}))
        exit()
    print("-"*80)
    pprint(sys.argv)
    main()
```

If I run this as-is, it takes about 15 seconds before I see the gooey window. If I change the `poll_external_updates` to `False`, it's instantaneous. (The dropdown is still filled with the same contents due to the `choices` parameter).

Note : this is only when starting up. Once gooey is running, going back to the edit window (which also invokes the `gooey-seed-ui`) is instantaneous.

Currently running on :
gooey 1.0.4
python 3.6.5
Windows 10 Pro 1903

**Comment by chriskiehl** [comment]
Interesting! 

Can you give the [release branch](https://github.com/chriskiehl/Gooey/tree/1.0.5-release) a quick spin and let me know if that helps your issue? 

Previously, I was adding items to the dropdown one at a time, which was a bit dumb. I've swapped that bit of code over to use `ComboBox`'s `SetItems` API, which allows setting the whole shebang at once. On my machine, this gives about a 4x speedup. 

This will probably not bring it down to `poll_external=False` levels of speed on your machine. I wasn't able to recreate the 15s latency you described. Before patching, the average latency for your example was hovering around 1.5seconds in my tests. Post fix, this is about .4s. A completely vanilla run on my machine takes about .2s to get Gooey on the screen. 

So, all that to say, the entirety of the latency is being sunk on a single call to Wx. Adding hundreds of things to a ComboBox unfortunately just takes a bit of time. Wx isn't very speedy in this area, it seems. This is code in the core GUI library, which means it's unfortunately outside of Gooey's control to make it faster. 

Anyways, hopefully this patch brings it back into acceptable levels. Let me know.

**Comment by frederikvs** [comment]
Awesome!
One the release branch, as far as I can tell, the problem is gone.

Apparently, on our machines, those calls to Wx came with a far worse penalty than on yours (We're running over remote desktop, maybe that changes something in those calls? Who knows!) - but on the release branch right now, if I run that example script above, gooey is on screen on the order of 1-2 seconds, regardless of whether `poll_external` is set `True` or `False`. There might still be half a second difference between the two, but that's a guesstimate based on one or two datapoints, with a "one mississippi two mississippi" kind of accuracy.

In the real application we're using, it's now on the order of 3 seconds (the script to generate the options also takes a little time), and this is more than fast enough for us :-)

Thanks for the quick response!

**Comment by chriskiehl** [comment]
Hooray! Closing this then. Will officially go out with 1.0.5.
