### ISSUE TITLE
 When the program is running, clicking the close button in the upper right corner will cause the program to freeze.

### ISSUE THREAD

**Issue by aaronhua123** [chriskiehl/Gooey#592]
- [ ] windows10
 - [ ] Python 3.7
 - [ ] Gooey  1.0.4.0.0.0 
 - [ ] Thorough description of problem 
     - [ ]  close the program
     - [ ]  program is hangs
 - [ ] Screenshot 
![123456](https://user-images.githubusercontent.com/34960412/86459287-22b13800-bd59-11ea-9247-43306858c4c0.PNG)
 - [ ] A minimal code example
Thanks! ^_^ 

```
import sys
import time

from gooey import Gooey, GooeyParser


@Gooey()
def gooey_app():
    parser = GooeyParser()
    args = parser.parse_args()

    # Do something for a long time
    for i in range(100):
        time.sleep(1)

    return 0

if __name__ == '__main__':
    sys.exit(gooey_app())
```

**Comment by aaronhua123** [comment]
Can someone help me？
I will be very grateful to you

**Comment by eladeyal-intel** [comment]
That's not a complete code example.

Where is import? 

Where is @Gooey decorator?

**Comment by aaronhua123** [comment]
Sorry, it is my fault, i have change the code example.Looking forward to your reply。

**Comment by eladeyal-intel** [comment]
I tried to reproduce but everything is in Chinese so I don't know what to pick. I suggest you change the example to a minimal one - you should be able to recreate the same problem with only 1 GUI element .

**Comment by aaronhua123** [comment]
I modified the example, so just need to get started. I think that the shutdown should stop the program first.

**Comment by eladeyal-intel** [comment]
It's the same for me, Windows 10, Python 3.8.3, wxPython 4.0.7, trunk.

@chriskiehl ,  I don't think this is something specific to the close button. For example: from the Windows command prompt, run this code at the top of this issue. Stop the underlying app using the Gooey Cancel button + press OK. Then close the window with X - it will still hang. Press Control+C (in the Windows command prompt). I get
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
```

**Comment by chriskiehl** [comment]
Fixed here: https://github.com/chriskiehl/Gooey/issues/592 

The problem came from the fact that there's an active thread running in the background that wasn't being cleaned up when you click the "X" button to close Gooey. It has been updated to run through the same machinery used when you force-stop and execution, which ensures everything gets cleaned up correctly before shutting down.

**Comment by chriskiehl** [comment]
whoops. Not quite fixed! Still working on this.
