### ISSUE TITLE
poll_external_updates forgets selected item

### ISSUE THREAD

**Issue by frederikvs** [chriskiehl/Gooey#593]
When using the feature `poll_external_updates`, my selection is forgotten.

E.g. if you run the below example code, select 'b', start it, and then go back to edit, 'b' is no longer selected. If you run the same with `poll_external_updates=False`, your last selection is remembered.

```
import json
import sys
from pprint import pprint

from gooey import Gooey, GooeyParser

@Gooey( program_name="Using Dynamic Values", poll_external_updates=True)
def main():
    parser = GooeyParser()
    parser.add_argument(
        '--name',
        metavar='name',
        widget='Dropdown',
        choices=['a','b','c']
    )

    args = parser.parse_args()
    pprint(args)

if __name__ == '__main__':
    if 'gooey-seed-ui' in sys.argv:
        l = ['a','b','c']
        print(json.dumps({'--name': l}))
        exit()
    print("-"*80)
    pprint(sys.argv)
    main()
```

I understand that with the external updates the selected option may no longer be there. If it's no longer there, I understand that nothing is selected. But when the selected option is still available, I would have hoped it would remember that selection.

Currently running on :
gooey 1.0.4
python 3.6.5
Windows 10 Pro 1903

**Comment by chriskiehl** [comment]
Fixed on the  [release branch](https://github.com/chriskiehl/Gooey/tree/1.0.5-release)! Could you give it a whirl? Lemme know if I missed any cases.

**Comment by frederikvs** [comment]
At first glance this looks like it fixed the issue, thanks!
I'll try to see if I can find missing cases, but that'll be for Monday when I'm back in the office :-)

**Comment by frederikvs** [comment]
I experimented some more with this today : when the list stays the same, it works splendidly.

However, it looks like it doesn't always retain the selected item if the list changes. E.g. in my use case (filtering the list), if I update the filter, sometimes the item selection is retained, sometimes not.

What I think is going on : if the list changes, and the selected item is at the same position in the new list as it was in the old, then it remains selected.
But if its position in the list changed, it gets forgotten.


For my purposes, there's no need to fix this additional case. If the list contents change, that means you probably want to select something else. However, other people may have other use cases, so I just want to give you all the info I have :-)
