### ISSUE TITLE
feedback on Dynamic Values (poll_external_updates)

### ISSUE THREAD

**Issue by frederikvs** [chriskiehl/Gooey#594]
As you may have noticed from my recent issues (#593, #591, #584 ) I'm using the experimental feature `poll_external_updates`. 
Since there's an explicit request for feedback, I figured I'd describe our use case. Not sure where to put it, so I'll just put it in the issue tracker. It's not a bug report, nor a real feature request, so strictly speaking it doesn't belong here. Feel free to move, remove, close, disregard, whatever :-)

Context : We are working on a test job management system. We have a bunch of test scripts, each of which can run on a number of configurations of the hardware we're testing. Our testers need to be able to select one of these scripts and activate it on the machine they're working on.
Since the list is quite long (number of test scripts multiplied by number of hardware configurations), we want to be able to filter them. On the command line we can use fzf for this, but our testers are using a gooey-based interface right now.

I've been building on the example code at  https://github.com/chriskiehl/GooeyExamples/blob/master/examples/dynamic_updates.py

Currently I have it working more or less. The relevant part looks like this : 
<img width="973" alt="Screenshot 2020-07-03 at 13 19 49" src="https://user-images.githubusercontent.com/3795966/86464504-ea493400-bd2f-11ea-873f-13714e209864.png">

If you select the "filter" radio button, you can enter some text and press "Start" to save the filter in a text file. Then you need to click "Edit" and the `gooey-seed-ui` mechanism reads that text file, and updates the dropdown with the filtered list. 

This is of course less convenient than the way fzf works on the command line. Our ideal scenario would have been that you can just start typing, and the dropdown starts shrinking, like fzf does. 
I understand this may not be easy to implement, and that if we want to achieve that, we may be forced to create our own GUI, without gooey. For now, this way of working, though less than ideal, will suffice. It beats searching through 600+ names of test cases :-)

Again, not a real bug report or anything, I don't expect any particular response or action on this from you @chriskiehl , I just thought you'd like to know how this experimental feature is being used :-)

Keep up the good work!

**Comment by chriskiehl** [comment]
Thanks for the feedback! I _DO_ like hearing how the experimental stuff is used! ^_^ This is awesome. 

I think your request is totally reasonable. It seems _fairly_ straight forward(ish) to have dynamic filtering / auto-complete kind of functionality tacked onto the Dropdown. 

I've tagged this for inclusion in 1.0.5 

Thanks for the feedback! I'd love to hear any other issues, quirks, or problems you run into as you use dynamic values. I've got my own little plans for the direction I want to go with it, but hearing how people actually use it is invaluable for making sure I hit the mark on functionality

**Comment by chriskiehl** [comment]
Hey @frederikvs, 

I've added a new widget type to the release branch that has filtering built in! Check this out: 

![FilterableDropdown Demo 2020-10-25 14-44-51](https://user-images.githubusercontent.com/1408720/97120143-6649fc00-16d2-11eb-95a9-f8c49cae055f.gif)

I've got some example code showing it in action here: https://github.com/chriskiehl/GooeyExamples/blob/1.0.5-release/examples/FilterableDropdown.py

You could give it a spin via the release branch: 
```
pip install -U git+https://github.com/chriskiehl/Gooey.git@1.0.5-release
``` 

Note: it may be a _little_ rough. For various reasons (mostly boiling down to Wx being a very quirky framework), this had to be rolled by hand. So, it may have some cross platform issues or a few bugs which need to be stamped down. Additionally, it currently uses a just a straight O(n) search for finding matches, so the performance may not be up to snuff for the data sets you need to filter just yet. If you find some time, give it a try and let me know if it solves your use case!

**Comment by eladeyal-intel** [comment]
Looks cool. FilterableDropDown could be a  default for any "choices" control with more than 10 options or so.
