### ISSUE TITLE
How to configure multiple execution steps?

### ISSUE THREAD

**Issue by thefriedman** [chriskiehl/Gooey#602]
Greetings,

Thanks for a great library.  
I am currently attempting to use Gooey for a relatively simple process that occurs in two steps.  
The user supplies some options, and the process runs to an intermediate point.  
Then, the user does some manual checks on the output before providing a couple more options.  The process then runs to final completion. 

I see that Gooey can provide multiple tabs/screens of argument options, but I don't see how to present these options after the program has succeeded with the first option group/parser.  The only options at that point are to edit the original options, restart or exit the program.  What am I missing?

Thanks for any help!

**Comment by eladeyal-intel** [comment]
I don't think Gooey can do that.

I have made some demos of using Gooey in tandem with other packages


https://github.com/chriskiehl/GooeyExamples/pull/17/files

https://github.com/chriskiehl/GooeyExamples/blob/2e54c4f74624b350c5382828b4c33b7cf1e3a2c2/examples/example_PySimpleGUI.py


For a simple "Are you sure" or "How to proceed" questions I actually used this below, which works for both GUI and non-GUI executions:


```python
def prompt_for_one_of(prompt_text, *args):
    if sys.stdout.isatty():
        while True:
            print(prompt_text)
            for i,s in enumerate(args): print(f'{i+1}. {s}')
            i=input()
            try:
                return args[int(i)-1]
            except:
                pass

    else:
        import PySimpleGUI as sg
        window=sg.Window(Path(__file__).stem,
                         [ [sg.Text(prompt_text)],
                           [sg.Button(t) for t in args] ])
        event, values = window.Read()
        window.Close()
        return event

action=prompt_for_one_of ('Are you sure?', 'Yes', 'No')
```

**Comment by chriskiehl** [comment]
Yep, like @eladeyal-intel described, this is not something Gooey currently does nor specifically aims to support. His solution is pretty cool if you just need that confirmation kind of behavior mid-way through your run.
