### ISSUE TITLE
Item mandatorily selected in mutually exclusive group with action "store_const" 

### ISSUE THREAD

**Issue by jgaffiot** [chriskiehl/Gooey#604]
Hello There, Future Issue Resolver! 

When I create a mutually exclusive group (*not* required) and use "store_const" actions, an element of the Radio Group is always selected (the first one), and it is not possible to deselect it. This is not a serious issue (I replaced everything with "store" and no more mutually exclusive group), but this construction is very useful when you work with Enums (as shown in the example).

- My OS is LinuxMint Ulyana (aka Ubuntu 20.04),
- My Python Version is Python 3.8,
- My Gooey version is 1.0.4.0.0.0, with the following dependencies:
  - colored [required: >=1.3.93, installed: 1.4.2]
  - Pillow [required: >=4.3.0, installed: 7.2.0]
  - psutil [required: >=5.4.2, installed: 5.7.2]
  - wxpython [required: ==4.0.7, installed: 4.0.7]
    - numpy [required: Any, installed: 1.19.0]
    - pillow [required: Any, installed: 7.2.0]
    - six [required: Any, installed: 1.15.0]

Here is the Minimal, Reproducible (hopefully) Example:

    import sys
    from enum import Enum
    from gooey import Gooey, GooeyParser

    class TestMode(Enum):
        PRODUCTION = 0
        VALIDATION = 1
        TEST = 2

    @Gooey()
    def main() -> int:
        parser = GooeyParser(description="Show unexpected behaviour")

        parser.set_defaults(mode=TestMode.PRODUCTION)
        mode = parser.add_mutually_exclusive_group()

        mode.add_argument(
            "--validation",
            metavar="Validation",
            action="store_const",
            const=TestMode.VALIDATION,
            help="Target the validation database.",
        )
        mode.add_argument(
            "--test",
            metavar="Test",
            dest="mode",
            action="store_const",
            const=TestMode.TEST,
            help="Target the test database.",
        )

        print(parser.parse_args())

    main()

Best regards and thanks for the amazing library.

**Comment by chriskiehl** [comment]
This took some digging. Interestingly, this appears to be up to the whims of the underlying platform. The wxPython maintainer explains it very briefly [here](http://wxpython-users.1045709.n5.nabble.com/Unselecting-radiobuttons-td2362359.html). On Ubuntu, it looks like GTK [doesn't accept radio groups without an option as valid](https://trac.wxwidgets.org/ticket/12344) 

So, for GTK backed Wx installations, it doesn't matter if you tell the radio button the deselect itself. The button will staunchly ignore your request. 

```
button1 = wx.RadioButton(self, style=wx.RB_GROUP)
button2 = wx.RadioButton(self) 

button1.GetValue() // True (selected by default) 
button1.SetValue(False) // explicitly telling the system to deselect the button 
button1.GetValue() // button is still selected. 
```

Really obnoxious when programs directly ignore commands!

As a work around, you could always add an additional argument to act as a "none" type. 

```python
@Gooey()
def main() -> int:
    parser = GooeyParser(description="Show unexpected behaviour")

    parser.set_defaults(mode=TestMode.PRODUCTION)
    mode = parser.add_mutually_exclusive_group()

    mode.add_argument(
        "--none",
        metavar="None",
        action="store_const",
        const=TestMode.NONE,
        help="Don't use any special validation logic",
    )

    mode.add_argument(
        "--validation",
        metavar="Validation",
        action="store_const",
        const=TestMode.VALIDATION,
        help="Target the validation database.",
    )
    mode.add_argument(
        "--test",
        metavar="Test",
        dest="mode",
        action="store_const",
        const=TestMode.TEST,
        help="Target the test database.",
    )

    print(parser.parse_args())
    // handle mode == None here

main()
```

It's a bit clunky, but at least allows you to retain the mutual exclusion semantics. 

I'll update the docs to note this odd GTK behavior. 


![image](https://user-images.githubusercontent.com/1408720/89109594-947fae80-d3f7-11ea-8bb4-9a7ee8367d62.png)

**Comment by jgaffiot** [comment]
OK I understand. Thanks for the digging, it seems not obvious to find the root cause, and thanks for the workaround.
Still an amazing library!
