### ISSUE TITLE
Feature request or reference to existing feature

### ISSUE THREAD

**Issue by stefanomorni** [chriskiehl/Gooey#606]
Hi.
First of all, many thanks for sharing this beautiful library.
I'm looking to develop a GUI for filtering a panda data frame dynamically based on user input in the GUI.
To show the initial dataframe and the filtered dataframe I need a table widget.
Do Gooey have a table widget? I looked long and hard for it but couldn't find any reference to any... so i decided to ask you hoping on a kind response.

Should not be any available, is such a widget planned for the near future or would you have any suggestion for a workaround?
I hope I didn't misuse this communication channel... if so, I apologize.

Thank you very much.

Stefano

**Comment by chriskiehl** [comment]
Perfectly fine communication channel ^_^ 

So, nope. No table widget as of right now, unfortunately. I poked around Wx, Gooey graphics library, and it doesn't look like there's an off-the-shelf one readily available either.  

I don't immediately see this as something that I'd be adding in the future. However, I'm always happy to have pull requests or hear additional use cases!

**Comment by stefanomorni** [comment]
Hi. Thank you very much for taking the time to answer my question.
Well, I will have to find another solution
...I'm new to python and not a programming expert...should I get good enough to contribute to your library, I will surely do so.
Thx

⁣Stefano Morniroli
morniroli.stefano@gmail.com
  
  ​

Il giorno 30 lug 2020, 06:01, alle ore 06:01, Chris <notifications@github.com> ha scritto:
