### ISSUE TITLE
Widgets are ignored in parent parsers

### ISSUE THREAD

**Issue by neonbunny** [chriskiehl/Gooey#608]
Argparse supports the notion of parser parents for reusing common arguments, e.g. between subparsers. However, when a GooeyParser is defined with arguments that have custom widgets and is then passed via the parents parameter, those widgets seem to be ignored.

The following code shows the problem, only `b_file` is shown with a FileChooser widget, despite both `a_file` and `b_file` being configured to use this widget. (Tested on Win 10, Gooey 1.0.4, Python 3.8.1)

```python
from gooey import Gooey, GooeyParser


@Gooey()
def main():
    base_parser = GooeyParser(add_help=False)
    base_parser.add_argument("a_file", widget="FileChooser")

    parser = GooeyParser(parents=[base_parser])
    parser.add_argument("b_file", widget="FileChooser")

    print(parser.parse_args())

if __name__ == "__main__":
    main()
```

![image](https://user-images.githubusercontent.com/6201399/89556146-de5a0180-d808-11ea-871b-13bd4cc02590.png)

**Comment by chriskiehl** [comment]
Closing. Resolved by your PR.
