### ISSUE TITLE
[question] How to use Error Screen

### ISSUE THREAD

**Issue by tugot17** [chriskiehl/Gooey#612]
Like in the title,  how to use Error Screen so I can inform the user that made something incorrect? In my case it is that they didn't check any checkbox

I mean what I should put instead of `show_error_message`

```python

if not my_condition:
   show_error_message
```

**Comment by chriskiehl** [comment]
The error screen is shown if your program returns a non-zero exit status. You can checkout an example [here](https://github.com/chriskiehl/GooeyExamples/blob/master/examples/error_demo.py).
