### ISSUE TITLE
How to print a pandas dataframe in the Gooey Output?

### ISSUE THREAD

**Issue by soliverc** [chriskiehl/Gooey#613]
I made a small program to crunch some numbers in pandas and display a table of results in the output using `print(df)`

However the layout is very messy. 

I have tried using the tabulate package to tidy it up, but it doesn't work. 

I also used `to_string()` i.e. `print(df.to_string)`

Here it a sample dataframe printed from a jupyter notbook:

![image](https://user-images.githubusercontent.com/47222261/90390227-e58fd380-e082-11ea-9739-e34191af71dc.png)

How it looks in the Gooey output:

![image](https://user-images.githubusercontent.com/47222261/90390497-546d2c80-e083-11ea-864f-2fb0d250d028.png)

I will admit it doesn't look absolutely terrible, but that's because I am using a fake dataframe. My actual data is not as simple, and when printed out is kind of destroyed and hard to read. However it's only 5 columns and 5 rows. 

Is there any way to tidy up a dataframe printout?

edit: added my "real world" data. 

Formatting is all messed up in the Gooey output no matter what I try. 

![image](https://user-images.githubusercontent.com/47222261/90392680-3f929800-e087-11ea-8132-d4280365c488.png)

**Comment by soliverc** [comment]
My "real world" data. 

Formatting is all messed up in the Gooey output.

![image](https://user-images.githubusercontent.com/47222261/90392680-3f929800-e087-11ea-8132-d4280365c488.png)

**Comment by eladeyal-intel** [comment]
I think you just need to enable monospace output.

**Comment by soliverc** [comment]
@eladeyal-intel  How do I do that?

**Comment by eladeyal-intel** [comment]
Not sure, I'm not next to my pc.

See #338 

But maybe Google it I think there's an explicit option for that.

**Comment by soliverc** [comment]
THanks @eladeyal-intel  

Works perfectly. I used `monospace_display=True`.
