### ISSUE TITLE
Isssue: Body Font Color & Bold

### ISSUE THREAD

**Issue by Th3Tr1ckst3r** [chriskiehl/Gooey#625]
Hi,

I've been having a lot of success with Gooey so far, and I've ran into what looks like might be a development halt.

I've set things up to where I have all background colors preset to black, but when I have attempted to change the body font color, it remains the default black. I've been reading all of the documentation, and it looks like the main body font does not have a way to change its color.

 **-[Windows 10 ] OS**
**-[3.7 ] Python Version**
**- [Latest Version ] Gooey Version** 

This is core settings that I've been debugging with, and haven't had issues color wise by setting other parts of the GUI to these colors:

```Python
bg_color = "#000000"
font_color = "#7CFC00"
#Background Settings
header_bg_color=bg_color,
body_bg_color=bg_color,
footer_bg_color=bg_color,
terminal_panel_color=bg_color,
#Font Settings
terminal_font_color=font_color,
terminal_font_weight='BOLD',
```
 
I have also been having an issue where i cant set the fonts to bold. If i set BOLD like in the docs, i got this:

```Python
Traceback (most recent call last):
  File "C:\Users\Misleading\Desktop\Project Volt\GUI\GUI.py", line 96, in <module>
    terminal_font_weight=BOLD,
NameError: name 'BOLD' is not defined
```

I thought then that if i dont treat it as a string, the results i got would be different, but then i got this when i dont use '':

```Python
Traceback (most recent call last):
  File "C:\Users\Misleading\Desktop\Project Volt\GUI\GUI.py", line 168, in <module>
    main()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 124, in inner2
    return payload(*args, **kwargs)
  File "C:\Users\Misleading\Desktop\Project Volt\GUI\GUI.py", line 161, in main
    args = parser.parse_args()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\python_bindings\gooey_parser.py", line 116, in parse_args
    return self.parser.parse_args(args, namespace)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 119, in run_gooey
    application.run(build_spec)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\application.py", line 21, in run
    app, _ = build_app(build_spec)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\application.py", line 30, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\containers\application.py", line 46, in __init__
    self.console = Console(self, buildSpec)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\components\console.py", line 27, in __init__
    self.textbox.SetFont(wx.Font(
TypeError: Font(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
  overload 4: argument 4 has unexpected type 'str'
  overload 5: argument 1 has unexpected type 'int'
  overload 6: argument 1 has unexpected type 'int'
  overload 7: argument 1 has unexpected type 'int'
```

I'd appreciate it if i can get any help, and if you have any other questions or need more info, i can submit that as needed.

Thank you.

**Comment by chriskiehl** [comment]
Could you give a runnable code sample? I'm not sure I understand all of your current examples. 

For handling the colors, there isn't currently a global override, but you can do it per-widget. Checkout [Gooey Options](https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md). They'll let you customize the colors of all the text. 

For the font_weight thing, that's a bug :( Or, more specifically, that's a bit of WX configuration leaking out into the Gooey layer. If you pass `terminal_font_weight=700` your text will show as bold (as this translates to the value of `wx.BOLD`). Will fix.

**Comment by chriskiehl** [comment]
`terminal_font_weight` has been fixed. The README has been updated to reflect the correct usage. 

```
from gooey import constants
@Gooey(terminal_font_weight=constants.FONTWEIGHT_BOLD) 
```

Additionally, the `terminal_panel_color` is now honored. This was failing due to a typo in the code. 

You can checkout the fixes on the [release branch](https://github.com/chriskiehl/Gooey/commit/b7e298fd06e0dca85d416478dddf8aa38b71b6a8)

**Comment by Th3Tr1ckst3r** [comment]
Thank you, I attempted this method, but it failed to import constants. Is the commits pushed automatically to where it can be pip installed, or is their a better method for testing this?

I used the following code shown here:

```Python
#Test App
import os
import sys
import argparse
from gooey import Gooey
from gooey import GooeyParser
from gooey import constants


def test(args):
	try:
		print(args.three)
		sys.exit(0)
	except KeyboardInterrupt:
		sys.exit(1)


@Gooey(program_name="Test", terminal_font_weight=constants.FONTWEIGHT_BOLD)
def main():
	try:
		global parser
		parser = GooeyParser(description='Test')
		parser.add_argument('one', widget="CheckBox", action='store_true', help='Test 1')
		parser.add_argument('two', widget="CheckBox", action='store_true', help='Test 2')
		parser.add_argument('three', help='Test 3')
		args = parser.parse_args()
		test(args)
	except KeyboardInterrupt:
		sys.exit(1)
		
		
if __name__ == "__main__":
	main()
	sys.exit(1)
```

I then got this error after reinstalling with pip:

```Python
Traceback (most recent call last):
  File "C:\Users\Misleading\Desktop\blank_setting.py", line 7, in <module>
    from gooey import constants
ImportError: cannot import name 'constants' from 'gooey' (C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\__init__.py)
```

Thank you.

**Comment by chriskiehl** [comment]
The release branch isn't on PyPi, so you'll have to install from the branch to test things out. 

```
pip install -U git+https://github.com/chriskiehl/Gooey.git@1.0.5-release 
```
