### ISSUE TITLE
Feature Requests: In Global Configuration

### ISSUE THREAD

**Issue by Th3Tr1ckst3r** [chriskiehl/Gooey#626]
Hi,

I have noticed that the default color for body text is black, and I have read the documentation. However, I have noticed that their is no way to change it globally, and it would be very beneficial when customizing a UI. 

I also believe that adding something like disable_fullscreen_button for the top bar near the exit button, allow for, or disable minimize_wxPython_window after GUI starts up, and lock_default_window_size so it can stay its designed size would also really be beneficial for others using this project.

I could really use these features myself, but their worth a small wait.

Here's a smaller list to sum up the feature requests(4 Total):
- body_font_color
- disable_fullscreen_button
- lock_default_window_size
- minimize_wxPython_window

Thank you, and I really like the project so far. 💯

**Comment by chriskiehl** [comment]
Howdy. 

Having a way to globally configure the text style is a decent idea. I've opened that as a separate issue [here](https://github.com/chriskiehl/Gooey/issues/628) to make tracking easier. 

I'm going to close this one as I don't see myself including the other options. Few things make me more annoyed than when applications staunchly deny norms and take away the ability to run things on my machine as I see fit. Minimizing, maximizing, and resizing are things which should be up to the person running the program (imho!)

**Comment by Th3Tr1ckst3r** [comment]
I agree, thank you.
