### ISSUE TITLE
Feature Request - PathChooser

### ISSUE THREAD

**Issue by Pseudonium** [chriskiehl/Gooey#636]
Not sure if this is possible with regular file dialogs, but a chooser that lets you choose either a file or a folder (i.e. any path).

**Comment by twardoch** [comment]
I imagine it might be possible to make a widget where, if you clicked the button, the file dialog would open but if you Alt-clicked it, the folder dialog would open.

**Comment by Pseudonium** [comment]
Oh is this possible in the current version, or is this a suggestion for how it could be implemented in a future version?

**Comment by chriskiehl** [comment]
@Pseudonium That's not possible in the core GUI libraries. The [dir](https://docs.wxwidgets.org/3.0/classwx_file_dialog.html) and [file dialogs](https://docs.wxwidgets.org/3.0/classwx_dir_dialog.html) exist in distinct spaces. 

If you want one or the other, maybe you could use a mutually exclusive group? 

```python
@Gooey
def gooey_app():
    parser = GooeyParser()

    group = parser.add_mutually_exclusive_group(required=True, gooey_options={
        'initial_selection': 0
    })
    group.add_argument('-f', '--file', help="Chose a File", widget='FileChooser')
    group.add_argument('-d', '--dir', help="Chose a directory", widget='DirChooser')


    args = parser.parse_args()
```

**Comment by Pseudonium** [comment]
Thanks for this - works perfectly!
