### ISSUE TITLE
(wish) Replace `_` with spaces in GUI repr of `metavar`

### ISSUE THREAD

**Issue by twardoch** [chriskiehl/Gooey#637]
Gooey is great! 

One small request: 

I’d like to define multi-word `matavar` attributes of the arg parser to have underscores, as this looks better in the CLI. But for now, I used spaces, which looks better in the GUI. 

Consider the code: https://github.com/twardoch/pypolona/blob/master/pypolona/__main__.py

I put spaces in metavars like `download to folder` because I wanted them to look like this in the GUI:
![](https://raw.githubusercontent.com/twardoch/pypolona/master/docs/img/pypolona3.png)

I made this little adaptation package [`ezgooey`](https://github.com/twardoch/ezgooey) which lets me run the app with GUI if no CL args are supplied but with CLI if they are.

So for the CLI, I’d actually prefer the multi-word metavars to be rendered in the CLI help with underscores.

Therefore my suggestion: when showing the metavars in the GUI, Gooey should replace underscores with spaces. That could be an option of course. Another option might be uppercasing the first letter in GUI. That would make the GUI instantly prettier.

**Comment by chriskiehl** [comment]
Howdy! 

Glad you're enjoying Gooey! 

So, unfortunately, status of this wish is gunna be: _denied_. TL;DR: I think these kinds of presentation choices should fall to your client code, not Gooey. 

It's tough to make everyone happy with presentational stuff. I could add some option in Gooey to replace underscores with spaces, but that'd probably not satisfy everyone's needs (for example, I'm more of a kebab-case guy myself). We could make it configurable, some kind of `metavar_replacement_key='_'` thing, but this again is kind of a crummy half-solution to a niche problem. In my opinion, how your strings get displayed should be managed by the code instrumenting Gooey (_because_ you've got the full power of a language behind you), not by Gooey making assumptions on your behalf, or picking up some under-powered mini-configuration / replacement rules / DSL that'll kinda work for some people's use cases some of the time.

**Comment by twardoch** [comment]
OK, I understand. A semi-related question then: 

I know that Gooey supports multilingual strings — is that only for its own built-in widgeting? 

CLI apps typically are single-language (though there may be exceptions), but I wonder: what would be the right way to internationalize the app-supplied strings in Gooey? Because that might kind of solve the problem I’m facing as well. I agree that a hardcoded solution for just the specific problem feels like a hack. But if there was some way to hook into the _entire_ process of presenting the strings for a given language (including English), for example with a decorator parameter where I could supply my own function, which would take the string being displayed, and optionally some language identifier, then I could do actual translation with that function, but also do some presentational-style adjustments along the line I’ve suggested.
