### ISSUE TITLE
get gooey working on os x 

### ISSUE THREAD

**Issue by ssbarnea** [chriskiehl/Gooey#64]
I observed that there was an OS X support feature in the TODO, but no issue in the tracker so I added one as I would like to hear when this will be available.

**Comment by chriskiehl** [comment]
I don't currently have OSX. So there's no timeline. However, others have (mostly) successfully run Gooey on the platform.  

https://github.com/chriskiehl/Gooey/issues/57

**Comment by SethMMorton** [comment]
I can also confirm it works on my Mac (Mavericks).

**Comment by amorde** [comment]
I've been running this on OS X for a very long time now, I think you can mark this closed

**Comment by nikett** [comment]
After trying through many suggestions, the following works on Mac OSX:
```
Step 0: conda activate my_env
Step 1: pip install gooey (or,  pip install -U gooey)
Step 2: conda install python.app (I think to get the gui environment for python)
Step 3: pythonw src/eval/tw_specific_eval/simple_t5_eval.py
```
