### ISSUE TITLE
Support for Ubuntu20.04 with wxPython4.1.0?

### ISSUE THREAD

**Issue by Anees93** [chriskiehl/Gooey#643]
- [Ubuntu 20.04 ] OS
 - [3.8 ] Python Version 
 - [1.0.4 ] Gooey Version 
 - [description of problem 
    The issue is that I use ubuntu 20.04 and wxPython4.1.0 is the only version supported therefore Gooey is not supported 

Thanks! ^_^

**Comment by chriskiehl** [comment]
1.0.5 release has the version bumped to 4.1.0. 

The release is still in progress, but you could install from the branch in the meantime.

```
pip install git+https://github.com/chriskiehl/Gooey/@1.0.5-release
```
