### ISSUE TITLE
cannot drag and drop several files

### ISSUE THREAD

**Issue by Karulp** [chriskiehl/Gooey#645]
Hello!

One argument of my program is a list of filepaths.
I added it in my program like this:
parser.add_argument('paths',
                        metavar='N',
                        type=str,
                        nargs='+',
                        widget='MultiDirChooser')

I would like to be able to drag and drop several folders from a file explorer window to the gooey widget of my argument.
When I do that, all the paths are concatenated together, without character like space to separate them.
Ex: the drag and drop of C:\test_gooey\folder1, C:\test_gooey\folder2, C:\test_gooey\folder3 and C:\test_gooey\folder4 makes C:\test_gooey\folder1C:\test_gooey\folder2C:\test_gooey\folder3C:\test_gooey\folder4
Thus, when my program starts, it sees all the paths like one path and failed.

The version I use:
Gooey==1.0.4.0.0.0
Windows 10

Is there something to do, so gooey would add a character to separate the paths?

Thank you!

**Comment by Karulp** [comment]
And the version I use:
Gooey==1.0.4.0.0.0
Windows 10

**Comment by chriskiehl** [comment]
This appears to be a valid bug. Maybe your [other issue](https://github.com/chriskiehl/Gooey/issues/646) mixed up this effect? 

In short, looks like the drop handler wasn't overridden to use the same pathsep logic as when you go through the dialog. 

Thanks for the report. This'll be fixed in 1.0.5!

**Comment by chriskiehl** [comment]
Fixed on the [release branch](https://github.com/chriskiehl/Gooey/commit/402f0b0c8ab51b9cedae214f7f9d2c333705c0e7). 

You can test it out via: 

```
pip install -U git+https://github.com/chriskiehl/Gooey.git@1.0.5-release
```

**Comment by Karulp** [comment]
You are very fast!
Thank you!

**Comment by chriskiehl** [comment]
>You are very fast! 

lol. Happened to catch me as I'm working on it. My response times are usually measured in months! x_x
