### ISSUE TITLE
MultiFileChooser and filepath with space

### ISSUE THREAD

**Issue by Karulp** [chriskiehl/Gooey#646]
Hello!

One argument of my program is a list of filepaths.
I added it in my program like this:
parser.add_argument('paths',
    metavar='N',
    type=str,
    nargs='+',
    widget='MultiFileChooser')

The bug occurs when I choose a file with a space in its name: The program sees it as two arguments.
For example, it sees C:\test_gooey\my file.txt as C:\test_gooey\my and file.txt.
If I manually add quotes at the beginning and the end of the path before I click the start button, the program sees it as an argument, but then it has to remove the quotes to call os methods on the path.

With the drag and drop of the file from a file explorer window to the gooey widget of my argument, the behavior is the same.

The version I use:
Gooey==1.0.4.0.0.0
Windows 10

Is there something I should do to fix this?

Thank you!

**Comment by chriskiehl** [comment]
Is your example the exact code you're running where you see the issue? I'm unable to reproduce even after setting up a path in which both the directory and selected files have spaces in their names. 

I'm not totally sure how it'd happen tbh. Gooey [joins the files via `os.pathsep` in the UI](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/components/widgets/core/chooser.py#L87), and then [surrounds each pathsep separated piece in quotes before passing to your program.](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/formatters.py#L21). So the presence (or absence!) of spaces shouldn't (in theory) matter.

**Comment by chriskiehl** [comment]
resolved the root Drag and Drop issue https://github.com/chriskiehl/Gooey/issues/645
