### ISSUE TITLE
Feature Request: Allow custom filter for Filterable Dropdown

### ISSUE THREAD

**Issue by dries007** [chriskiehl/Gooey#652]
Hi there

I'm a colleague of @frederikvs and I'm doing some followup on his suggestions in #594. We're updating to 1.0.5 soon and would like to ditch our DIY filter mess for the newly introduced FilterableDropdown widget. It works great so far but unfortunately we're being limited by the search implementation you chose.

Now the filter is hardcoded to `choice.lower().startswith(prompt)`. While this might be a great default in many situations, we need a more "fuzzy" implementation because large groups of our choices start with a long identical prefix.

Ideally we could pass along a filter function/lambda via the `gooey_options` dict. Would that be an acceptable solution for you? If yes, I might be able to create a PR, since that's how I intend to patch it locally for now.

**Comment by dries007** [comment]
This is how I solved it on our repo: Qteal/Gooey@6f0efd848466f9eaf169672d44f528e2f47619b9, it's a relativly minor change.

**Comment by chriskiehl** [comment]
Howdy!

Ah, I figured that naive search was less than ideal. I went with it just for the sake of not sitting on 1.0.5 any longer (which I'll tend to do indefinitely as I tinker with things). I'm planning on doing a followup release shortly with swappable search strategies. For instance, a fast trie backed prefix search (word and words approaches), fuzzy Levenshtein matchers, and then a full on detailed substring searching like you're doing (likely stolen directly from what you pasted above, in fact). I'm hoping those cover most of the cases people will have. 

For your suggestion of making it configurable by passing in a function, in almost any other software project I'd agree with that as the perfect solution. However, for Gooey, I'm generally against passing arbitrary code from Python land. I'll spare you my full boring rationale, but the tl;dr is that it doesn't serialize well and locks out other languages (the full background for this reasoning is elsewhere in the tracker). So, for this instance, I'll have to unfortunately decline that pull (sorry!) 

Optimistically, I'm hoping to get the updated search functions in this weekend.

**Comment by chriskiehl** [comment]
Give 1.0.6 a whirl and let me know if it fills your use case. If I understand your code sample appropriately, you're after being able to match on any word or word part. To do that with the current Gooey functionality, you'd use something like the below: 

```
@Gooey(program_name='FilterableDropdown Demo', poll_external_updates=True)
def main():
    parser = GooeyParser(description="Example of the Filterable Dropdown")
    parser.add_argument(
        "-a",
        "--myargument",
        metavar='Country',
        help='Search for a country',
        choices=data,
        widget='FilterableDropdown',
        gooey_options={
            'label_color': (255, 100, 100),
            'placeholder': 'Start typing to view suggestions',
            'search_strategy': {
                'type': 'PrefixFilter',
                'choice_tokenizer': PrefixTokenizers.WORDS,
                'input_tokenizer': PrefixTokenizers.WORDS,
                'ignore_case': True,
                'operator': 'AND',
                'index_suffix': True  #<-- this will index slices of the total string to allow partial matches
            }
        })
    args = parser.parse_args()
    print(args)
```

This'll load everything into a suffix trie and give you really fast O(logN) searching against any arbitrary substring in the dataset (and the cost of burning some extra memory). 

So it allows filtering via some initial prefix + some later string qualifier 

![image](https://user-images.githubusercontent.com/1408720/99162293-f915ff00-26b0-11eb-8fdc-1ce8df4f67de.png)

**Comment by dries007** [comment]
It looks great so far, much more optimized I'm sure.
I implemented the search like that because it was quick and easy, I didn't care about performance or one particuar search strategy over another.

Your example configuration/options work great. As far as I can see it covers our usecase.
Thanks for the quick work.
