### ISSUE TITLE
Tabbed groups "optional arguments" tab not translated

### ISSUE THREAD

**Issue by neonbunny** [chriskiehl/Gooey#653]
When using tabbed groups in Gooey 1.0.6, the tab title for "Optional Arguments" is shown as:

![image](https://user-images.githubusercontent.com/6201399/99541616-f36a3300-29a8-11eb-8f27-750548841ca0.png)

This appears to be the placeholder string prior to i18n translation.

**Comment by chriskiehl** [comment]
Closing (fixed by you!)
