### ISSUE TITLE
support action='version'

### ISSUE THREAD

**Issue by casperdcl** [chriskiehl/Gooey#655]
from https://docs.python.org/3/library/argparse.html#action

```
parser.add_argument('--version', action='version', version='%(prog)s 2.0')
```

should be treated like `store_true` (checkbox), but Gooey treats it like `store` (free text entry)

![image](https://user-images.githubusercontent.com/10780059/100495035-509b7c80-313f-11eb-9b57-479b54f92be4.png)

Python 3.6 Gooey 1.0.4.0

**Comment by chriskiehl** [comment]
Implemented on the current [release branch](https://github.com/chriskiehl/Gooey/commit/633e7c88677a0d9ff230469711ce5e24e3632d7b)!
