### ISSUE TITLE
Error running Gooey in virtualenv

### ISSUE THREAD

**Issue by vesatoivonen** [chriskiehl/Gooey#66]
I'm trying to get mock_argparse_example.py to run as is, but after pressing start I get this error:
```
Traceback (most recent call last):
  File "/home/vesa/venv/local/lib/python2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/gui/windows/footer.py", line 152, in OnStartButton
    self._controller.OnStartButton(event, self)
  File "/home/vesa/venv/local/lib/python2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/gui/controller.py", line 61, in OnStartButton
    self.RunClientCode(command)
  File "/home/vesa/venv/local/lib/python2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/gui/controller.py", line 72, in RunClientCode
    p = subprocess.Popen(command, bufsize=1, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

My current environment:
```
(venv)vesa@xubuntu ~> lsb_release -d
Description:	Ubuntu 14.04.1 LTS
(venv)vesa@xubuntu ~> python --version
Python 2.7.6
(venv)vesa@xubuntu ~> pip freeze
Gooey==0.1.0
Pillow==2.7.0
argparse==1.2.1
docx==0.2.4
jdcal==1.0
lxml==3.4.1
openpyxl==2.1.4
wsgiref==0.1.2
wxPython==2.8.12.1
```

**Comment by chriskiehl** [comment]
Couple of quick debugging questions: 

1. Does this happen *exclusively* inside of Virtualenv? What happens if you try to run it outside? 
2. Are you running the latest version?

**Comment by vesatoivonen** [comment]
I'm running the latest version and the problem persists outside virtualenv.

**Comment by chriskiehl** [comment]
Alright, I've been digging into this tonight. It gave me an excuse to spin up a VM and finally play around with Gooey on Ubuntu. 

To fix your specific issue, you only need to add `shell=true` to the `Popen` call in `controller.py`. Its got something to do with the way I'm passing in the command line args and how they're processed on linux. As an aside, it's interesting that this is uniquely an issue on linux and not OSX. 

So, that takes care of that. 

Next problem: Once the above was working, a whole new slew of errors started popping up. WxPython on Linux is crazy finicky about threads and how they interact with the GUI. It would explode anytime the update thread tried to write some text on the screen. But! After a bit of reading and tinkering, I think I've got the below as a preliminary fix. More or less it boiled down to wrap everything in `wx,CallAfter`. 

I haven't committed this yet. So you'll have to patch it locally using the diff for now. However, I'll push it up within the next few days. Just need to see if this solution works on Windows and OSX as well. 







    --- a/gooey/gui/controller.py
    +++ b/gooey/gui/controller.py
    @@ -61,16 +61,18 @@ class Controller(object):
         self.RunClientCode(command)
     
       def RunClientCode(self, command):
    
         def doInBackground(process, callback):
           while True:
             line = process.stdout.readline()
             if not line:
               break
    -        self.core_gui.PublishConsoleMsg(line)
    -      callback(process)
    +        wx.CallAfter(self.core_gui.PublishConsoleMsg, line)^M
    +      wx.CallAfter(callback, process)^M
     
    -    p = subprocess.Popen(command, bufsize=1, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    +    p = subprocess.Popen(command, bufsize=1, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell
         _pool = Pool(1)
    +    # wx.CallAfter(doInBackground, p, self.HandleResult)^M
         _pool.apply_async(doInBackground, (p, self.HandleResult))
     
       def HandleResult(self, process):
  (END)

**Comment by vesatoivonen** [comment]
This seems to fix the issue I'm having.
Thanks.

**Comment by chriskiehl** [comment]
Fix has been pushed.
