### ISSUE TITLE
utf-8 error 

### ISSUE THREAD

**Issue by gengyanlei** [chriskiehl/Gooey#665]
pyinstaller to exe

![image](https://user-images.githubusercontent.com/22360785/104010498-8bd1a680-51e7-11eb-8dcd-aabbb2689995.png)
![image](https://user-images.githubusercontent.com/22360785/104010622-c0ddf900-51e7-11eb-944f-69eaf8df2284.png)

**Comment by gengyanlei** [comment]
pyinstaller to exe

**Comment by gengyanlei** [comment]
code：

import os
import pinyin
from gooey import Gooey, GooeyParser
from icrawler.builtin import GoogleImageCrawler
from icrawler.builtin import BaiduImageCrawler
from icrawler.builtin import BingImageCrawler

# 每个搜索 都有1个对应的爬虫数量
@Gooey(
    richtext_controls=True,  # 打开终端对颜色支持
    program_name="图片爬虫工具",  # 程序名称
    encoding="utf-8",  # 设置编码格式，打包的时候遇到问题
    # progress_regex=r"^progress: (\d+)%$"  # 正则，用于模式化运行时进度信息
    # progress_regex=r"^progress: (?P<current>\d+)/(?P<total>\d+)$",
    # progress_expr="current / total * 100"
)
def main():
    settings_msg = '三大搜索引擎爬虫图像-谷歌暂不支持！'
    parser = GooeyParser(description=settings_msg)

    parser.add_argument("search_engine", metavar='请选择搜索引擎', help="BaiDu, Google, Bing", choices=["百度图片", "Bing图片"], default="百度图片")
    parser.add_argument("save_root", metavar='设置保存路径', help="在选择路径下，自动新建多个文件夹保存图像", widget="DirChooser")
    parser.add_argument("img_num", metavar='输入下载数量', help="请输入1个数字", widget="TextField", default=10)
    parser.add_argument("key", metavar='请输入1个关键字', help="请输入关键字", widget="TextField", default="中国")

    args = parser.parse_args()
    args.img_num = int(args.img_num)

    key = pinyin.get(args.key, format="strip", delimiter="")
    image_save_root = os.path.join(args.save_root, key)
    if not os.path.exists(image_save_root):
        os.makedirs(image_save_root)
    storage = {'root_dir': image_save_root}
    if args.search_engine == "百度图片":
        crawler = BaiduImageCrawler(storage=storage)
    elif args.search_engine == "Bing图片":
        crawler = BingImageCrawler(storage=storage)

    crawler.crawl(keyword=args.key, max_num=args.img_num)

if __name__=="__main__":
    main()

**Comment by chriskiehl** [comment]
![image](https://user-images.githubusercontent.com/1408720/104050508-95352180-519b-11eb-991f-3f296461d5bc.png)

I can't run your program, because I don't have your deps, so I can't reproduce the error. I also have no idea which version of Gooey you're using.

**Comment by chriskiehl** [comment]
You don't have to close, just fill out the issue template and we'll work through it ^_^

**Comment by simin75simin** [comment]
similar problem, tried [this](https://stackoverflow.com/questions/47692960/error-when-using-pyinstaller-unicodedecodeerror-utf-8-codec-cant-decode-byt) but didn't work

**Comment by simin75simin** [comment]
> similar problem, tried [this](https://stackoverflow.com/questions/47692960/error-when-using-pyinstaller-unicodedecodeerror-utf-8-codec-cant-decode-byt) but didn't work

i followed [this](https://github.com/chriskiehl/Gooey/issues/520#issuecomment-578074690) thread and added the following code to the start of my main program and it worked with single file pyinstaller on windows 10, python3.7.9:
```import codecs
import sys

if sys.stdout.encoding != 'UTF-8':
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
if sys.stderr.encoding != 'UTF-8':
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')```
