### ISSUE TITLE
Display the output graph/images of my code in the same window

### ISSUE THREAD

**Issue by monjoybme** [chriskiehl/Gooey#668]
Is it possible to display the output graph/images of my code in the same window just like the attached image? 

<img width="363" alt="Screen Shot 2021-01-27 at 10 53 27 AM" src="https://user-images.githubusercontent.com/17875749/106017055-0fb3db80-608e-11eb-8cad-a8804beb3731.png">

[Image Source](https://www.researchgate.net/figure/Example-output-from-the-MatLab-GUI-showing-current-velocity-throughout-the-model-domain_fig1_229037416)

>README: Are you suddenly seeing errors related to Alignment flags when starting Gooey? Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Found a bug? Just a friendly heads up, _debugging it requires information from you!_ Make sure the template below is filled out in its entirety. 

 - [ ] OS- UBUNTU
 - [ ] Python Version : 3.6
 - [ ] Gooey Version :
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior 
     - [ ] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
Unfortunately not. Gooey wraps CLI programs, so it's fairly text focused. You could launch additional windows while running, but there's not currently a way, nor any immediate plans to support, displaying any rich media inline.
