### ISSUE TITLE
Hide `Runnning` and `Complete` Screens

### ISSUE THREAD

**Issue by OrkhanHI** [chriskiehl/Gooey#674]
Hi there,

When I get first screen, I give the path to my document.

After that it shows Running screen and when the script done it will show Complete screen.

Is there anyway to hide Running and Complete screens?

Thank you in advance.

**Comment by chriskiehl** [comment]
What do you have in mind for the behavior of the start button under this setup?

**Comment by OrkhanHI** [comment]
I found the solution, thanks.
