### ISSUE TITLE
 error: unrecognized arguments: --ignore-gooey

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#679]
- Ubuntu 20.04
- Python version 3.8.5
- Gooey version 1.0.8 **(worked fine until I upgraded from 1.0.4)**

### Expected Behavior 

I expected to not see this argument being passed to my argparser.

### Actual Behavior

Gooey passes `--ignore-gooey` to my argparser.

### Minimal code example

None of this happens unless I use my `conditionalGooey` decorator:

```
def conditionalGooey(*pargs, **kwargs):
    """Conditional decorator that wraps the Gooey decorator if the display can be found."""
    def decorator(func):
        if not wx.PyApp.IsDisplayAvailable():  # pylint: disable=no-member
            return func
        if len(sys.argv) > 1:
            return func
        return Gooey(*pargs, **kwargs)(func)
    return decorator
```

```
@conditionalGooey(program_name="Test case")
def process_options():
  ....
```

**Comment by bje-** [comment]
My mistake -- the problem even existed in 1.0.4.

**Comment by Shadoward** [comment]
Hi,
Please follow this instruction.
https://github.com/chriskiehl/Gooey/issues/449

**Comment by bje-** [comment]
Oh, that's excellent, thank you!

**Comment by Shadoward** [comment]
😉
