### ISSUE TITLE
IndentationError when if statement is in main() function

### ISSUE THREAD

**Issue by SethMMorton** [chriskiehl/Gooey#68]
When I run the following MWE:

```python
from gooey import Gooey, GooeyParser

@Gooey
def main():
    parser = GooeyParser(description="My Cool GUI Program!") 
    parser.add_argument('Filename', widget="FileChooser")
    parser.add_argument('--hello', action='store_true', default=False)
    args = parser.parse_args()

    print args.Filename
    if args.hello:
        print 'Hello!!'

if __name__ == '__main__':
    main()
```

I get the following error:

```
Traceback (most recent call last):
  File "gui.py", line 16, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 118, in inner
    parser = get_parser(main_module_path)
  File "/usr/local/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 161, in get_parser
    return source_parser.extract_parser(module_path)
  File "/usr/local/lib/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 146, in extract_parser
    client_module = modules.load(module_source)
  File "/usr/local/lib/python2.7/site-packages/gooey/python_bindings/modules.py", line 21, in load
    return __import__(tmpfilename)
  File "/var/folders/9m/f1_73gtj5fq855hdxt9mb0nc0000gn/T/tmpP5Y9qh.py", line 9
    print 'Hello!!'
    ^
IndentationError: unexpected indent
```

I took a look at what is being passed to `modules.load()` and it is the following:

```python
from gooey import Gooey, GooeyParser

def main():
    parser = GooeyParser(description="My Cool GUI Program!") 
    parser.add_argument('Filename', widget="FileChooser")
    parser.add_argument('--hello', action='store_true', default=False)
    return parser

        print 'Hello!!'

if __name__ == '__main__':
    main()
```

I understand that there is a fair amount of magic going on under the hood to get this to work, but it seems that this magic does not expect there to be any nested code structures in the `main()` function after the parser has been fully defined.  Everything works as expected if there are no nested structures or if the nested structures are put into a separate function.

Could `Gooey` be updated to either handle this situation, or reflect this limitation in the README (if this limitation cannot be overcome)?

P.S. Amazing library!

**Comment by chriskiehl** [comment]
Good bug! I'm surprised that no one has run across this before. 

It appears to be a bug in Python's `ast` module. The `lineno` reported by `ast.If`objects is always off by one. A simple rule to account for that fact and everything started running fine again. 

And thanks for showing both the code you were trying to run *and* the error produced *and* preliminary debugging info! Helped me narrow it down super quick. You're one of the good ones :) 

Pull a fresh copy of the repo and everything should run OK.

**Comment by SethMMorton** [comment]
Thanks for the speedy response!  While this does fix the `if` statement problem, I get an identical error for other nested structures (i.e. `for`, `with`, `def`, etc.).  You may need to come up with a more general  solution or create a larger "case" statement to fix this. :(

**Comment by SethMMorton** [comment]
I think a complete list would be `if`, `elif`, `else`, `try`, `except`, `finally`, `with`, `for`, `while`, and `def`.

**Comment by SethMMorton** [comment]
I took a stab at it, and I modified your recent commit to

```python
  # ast seemingly incorrectly reports the line no of ast.If objects (bug?)
  # thus, if we end on an IF statement, decriment the line number by one.
  final_line = main_func.body[-1]
  block_statements = (ast.If, ast.IfExp, ast.ClassDef, ast.FunctionDef,
                      ast.While, ast.For, ast.With, ast.TryExcept, ast.TryFinally)
  restart_line = final_line.lineno if not isinstance(final_line, block_statements) else final_line.lineno - 1
```

It runs now, but is still not working properly.  To illustrated I modified the MWE to be the following:

```python
from gooey import Gooey, GooeyParser

@Gooey
def main():
    parser = GooeyParser(description="My Cool GUI Program!") 
    parser.add_argument('Filename', widget="FileChooser")
    parser.add_argument('--hello', action='store_true', default=False)
    args = parser.parse_args()

    print args.Filename
    if args.hello:
        print 'Hello!!'
        print 'This!'

    def test():
        print 10
        return x

    for x in range(10):
        print x
        print 'Hi!'

    with open('test.txt') as fl:
        x = 10
        print fl

    try:
        x = 10
        y = 10
    except Exception:
        x = 9
        y = 18


if __name__ == '__main__':
    main()
```

Now, the code being passed to `modules.load()` is

```python
from gooey import Gooey, GooeyParser

def main():
    parser = GooeyParser(description="My Cool GUI Program!") 
    parser.add_argument('Filename', widget="FileChooser")
    parser.add_argument('--hello', action='store_true', default=False)
    return parser

    try:
        x = 10
        y = 10
    except Exception:
        x = 9
        y = 18


if __name__ == '__main__':
    main()
```

The `.lineno` attribute of the block structure tells you the line it *starts* on, not ends on, so the `- 1` trick is removing the indentation error, but also removing this logic from what was in the the `main()` function when all the magic happens in the background.  In order to get the *last* line, you would have to recursively descend into the nested block structure which is nontrivial because the `ast` structure is different for each block type.

You might be better off looking for the starting line of the *next* `ast` structure after the `main()` function, and doing the `- 1` trick on that to get this to work.  You would have to account for the possibility that the `main()` is the last.  I replaced the code you added in the recent commit with the below, and the it works as I would expect:

```python
  # ast reports line no of a block structure as the start of the structure,
  # not the end, so we look for the line no of the next node after main()
  # and use that as the the reference for the end of the main() function.
  try:
    restart_line = nodes.body[nodes.body.index(main_func)+1].lineno - 1
  except IndexError:
    restart_line = len(source)
```

yields

```python
from gooey import Gooey, GooeyParser

def main():
    parser = GooeyParser(description="My Cool GUI Program!") 
    parser.add_argument('Filename', widget="FileChooser")
    parser.add_argument('--hello', action='store_true', default=False)
    return parser

if __name__ == '__main__':
    main()
```

---

If you would like me to make a formal pull request, I can do that, but feel free to simply copy and paste that code in if you want.

**Comment by chriskiehl** [comment]
Man, I appreciate all the research you've done on this!  You seem to have pinned down the problem exactly. 

I don't want to take credit for your work. Pull request that stuff!

**Comment by erm3nda** [comment]
I got this error too just now with my recent download. I've tried with some premade scripts so it was fast to end up with indent error. My personal case was triying to don't run only in GUI, so added a param `if not sys.argv[0] == "--gui":
    try:
        from gooey import Gooey
        @Gooey
    except:
        pass` and did appear. It is fixed now?

**Comment by chriskiehl** [comment]
@erm3nda 

This issue was mixed many, many, many, _many_ commits ago :) My best guess is that you're using an outdated version of Gooey. I'd suggest running a quick `pip install -U gooey` to upgrade to the latest. 

Now, with regards to _not_ running Gooey, you don't need to do this: 

	if not sys.argv[0] == "--gui":
	    try:
	        from gooey import Gooey
	        @Gooey
	    except:
	        pass


I haven't yet added it to the documentation, but Gooey is pre-wired to short circuit if you sent it an `--ignore-gooey` flag. 

So, all you'll have to do is run your script like this: 

```python your_script.py --ignore-gooey [the rest of your command line args]```

Gooey will automatically pop the `--ignore-gooey` bit out of `sys.argv`, so you're program will run exactly as though Gooey wasn't there at all.
