### ISSUE TITLE
Hebrew translation not gender-neutral

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#685]
![image](https://user-images.githubusercontent.com/20379005/113510006-24669100-9561-11eb-8191-d0f8fd479c93.png)

Assuming these screenshots are still relevant, then these instructions are addressing the user. Current wording assumes the user is male.

It should be gender neutral

```
  "choose_date": "בחר תאריך",
  "choose_file": "בחר קובץ",
  "choose_folder": "בחר תיקייה",
  "choose_one": "בחר פריט",
```

**Comment by chriskiehl** [comment]
PR the fix, my friend! 1.0.9-release. 

I'm a big ol' single language (barely!) speaking dummy. I have to leave the smart people stuff to others.

**Comment by rodrigoeam** [comment]
same drawback
The Spanish translation is also not neutral
How can I solve?
![Captura de pantalla de 2022-06-29 18-19-54](https://user-images.githubusercontent.com/108445730/176588216-40afd8f8-d4dc-4b63-8e44-8e08d843317a.png)
![Captura de pantalla de 2022-06-29 18-21-37](https://user-images.githubusercontent.com/108445730/176588237-95afd931-b492-42b7-adc3-b7c39f308b43.png)

**Comment by rodrigoeam** [comment]
How can I solve this translation problem?
I have the same problem in Spanish translation
![Captura de pantalla de 2022-06-29 18-18-23](https://user-images.githubusercontent.com/108445730/176755402-b208172f-2a1b-4745-97fc-a3522243e664.png)
![Captura de pantalla de 2022-06-29 18-21-37](https://user-images.githubusercontent.com/108445730/176755441-584fd65a-8f3c-46b9-ba34-609d87d81887.png)
![Captura de pantalla de 2022-06-29 18-19-54](https://user-images.githubusercontent.com/108445730/176755475-b49011eb-2178-41d0-8dbb-4284a08044ef.png)
