### ISSUE TITLE
Don`t know how to display textarea widget for  more than 2 lines !

### ISSUE THREAD

**Issue by video000** [chriskiehl/Gooey#689]
It is simple,but still not found a solution.
 I cannot display a textarea widget for more than 2 lines.
options do not  contains that option.
how ?

**Comment by chai3** [comment]
@video000
You can use height of **gooey_options**(not options).
https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md#textarea

Example
---

```python
from gooey import Gooey, GooeyParser

@Gooey()
def main():
    parser = GooeyParser() 
    parser.add_argument('-default-text-area', widget="Textarea")
    parser.add_argument('-large-text-area', widget="Textarea", gooey_options={"height": 80, "full_width": True})
    parser.parser.parse_args()

if __name__ == "__main__":
    main()
```

![image](https://user-images.githubusercontent.com/16031581/117442928-5d37c280-af72-11eb-96ee-5c2b06738c33.png)

**Comment by chriskiehl** [comment]
@chai3 thanks for the answer!

**Comment by video000** [comment]
Thank u very much ,problem solved!!!!
