### ISSUE TITLE
Missing link to Group parameters (and advice on how to achieve monospace_displayin the "modern way"

### ISSUE THREAD

**Issue by fontanka16** [chriskiehl/Gooey#691]
The Readme has multiple broken links on a section on "Group Parameters" https://github.com/chriskiehl/Gooey#group-configuration, but that section is missing from the Readme. The real ask here is that I note that 

Gooey Option `monospace_display` is a legacy option.
 
and that I am looking for a way to achieve this.

**Comment by chriskiehl** [comment]
Apologies for the delay! 

Checkout the `terminal_font_color` option in the [Global Configuration section of the readme](https://github.com/chriskiehl/Gooey#global-configuration). They'll let you control the fonts as well as their weight and color. 

For instance, 

```
from gooey import Gooey, GooeyParser

@Gooey(terminal_font_family='consolas')
def main():
    parser = GooeyParser()
    # parser.add_argument('-default-text-area', widget="Textarea")
    # parser.add_argument('-large-text-area', widget="Textarea", gooey_options={"height": 180, "full_width": True})
    parser.parser.parse_args()
    print("""
  /\_____\    
 _\ \__/_/_   
/\_\ \_____\  
\ \ \/ / / /  
 \ \/ /\/ /   
  \/_/\/_/    
    """)


if __name__ == "__main__":
    main()
```


Thanks for letting me know about the broken links in the README. I've fixed them on the [release branch](https://github.com/chriskiehl/Gooey/commit/0b3ac04ca07569a6d1a744db5b2854dd2abec2ed)

**Comment by fontanka16** [comment]
Thank you @chriskiehl !
