### ISSUE TITLE
Prompts not showing in the status

### ISSUE THREAD

**Issue by naninaveen** [chriskiehl/Gooey#692]
If the script is required to get some input from the user,
in that case using `input(prompt)` will not show any message in the status of the program.
Only when you stop the program, then the prompt is shown in the status.

 - [x] OS - Windows 10
 - [x] Python Version - 3.6.5
 - [x] Gooey Version - 1.0.8
 - [x] Thorough description of problem 
     - [x] Expected Behavior - when input(prompt) is used the Gooey should show some window for taking the user input
     - [x] Actual Behavior - No message/prompt is shown
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
```python
import argparse
from gooey import Gooey


@Gooey
def main():
    """main function"""
    description = "Description"
    parser = argparse.ArgumentParser(
        description=description, conflict_handler="resolve"
    )
    parser.add_argument(
        "required_arg1",
        help="Required argument 1",
        type=str,
    )
    general = parser.add_argument_group("General")
    general.add_argument("-h", "--help", action="help", help="Shows the help.")
    general.add_argument(
        "-v", "--version", action="version", version="v1.0.0", help="Shows the version."
    )

    args = parser.parse_args()
    input("Please enter something: ")


if __name__ == "__main__":
    main()
```
 - [ ] Screenshot (if visual quirk) 
 - [x] Anything else you may think will be helpful - it may be helpful if somehow gooey can patch the input() function so that it shows a dialogue with a text that can be passed back to the code, but patching inbuilt functions imho is not the preferred way, so providing any function like `gooeyinput()` can be helpful.

Thanks! ^_^
And feeling awesomely happy with `@Gooey`

**Comment by toddatctera** [comment]
I'm not associated with the project but I have started trying it myself and have had the same experience.
However, I think this is Working As Intended. Per the Usage:

> Gooey is attached to your code via a simple decorator on whichever method has your argparse declarations (usually main).

Gooey is meant to help easily create a GUI for a program that's already using the [argparse](https://docs.python.org/3/library/argparse.html) module.

To make your example program work, you would need to do something like this:

```
import argparse
from gooey import Gooey


@Gooey
def main():
    """main function"""
    description = "Description"
    parser = argparse.ArgumentParser(
        description=description, conflict_handler="resolve"
    )
    parser.add_argument(
        "required_arg1",
        help="Required argument 1",
        type=str,
    )
    general = parser.add_argument_group("General")
    general.add_argument(
        "-h", "--help", action="help", help="Shows the help.")
    general.add_argument(
        "-i", "--input", action="store",
        help="Enter some input to be used later."
    )

    args = parser.parse_args()
    print("Required argument:",args.required_arg1)
    print("Optional argument input:",args.input)

if __name__ == "__main__":
    main()

```

So to use Gooey, you would have to write an argument driven program rather than input driven.
I have started slowly doing this myself with my own project and since I prefer the CLI over a GUI, I appreciate that I can still run my now heavily adapted code on the CLI like so:

```
todd@laptodd:example$ python example.py --ignore-gooey test1 -i test2
Required argument: test1
You optionally entered this additional input: test2
```

**Comment by chriskiehl** [comment]
Hey @toddatctera, thanks for the answer. You're right: Gooey's working as intended in this case. Your example is spot on. 👍
