### ISSUE TITLE
Print does not work in exe file

### ISSUE THREAD

**Issue by Podolyan98** [chriskiehl/Gooey#701]
Hello. I made the output for the developer to a file via [loguru](https://github.com/Delgan/loguru#easier-file-logging-with-rotation-retention-compression)(`debug.log`) and for the user to the `Status` window via `print`:

```
from gooey import Gooey, GooeyParser
from loguru import logger
from selenium import webdriver
from time import sleep
from webdriver_manager.chrome import ChromeDriverManager

logger.remove()
logger.add(
    'debug.log',
    encoding='utf8',
    format='{time} {level} {message}',
    level='DEBUG',
    rotation='10 MB',
    compression='zip',
)

@Gooey()
def main():
    parser = GooeyParser(description='Driver')
    parser.parse_args()
    logger.debug('Information for developers')
    print('Information for users')
    driver = webdriver.Chrome(ChromeDriverManager().install())
    while True: 
    	print('Driver started')
    	sleep(5)

if __name__ == '__main__':
    main()
```

The source code works well. But in the exe file made using PyInstaller(`pyinstaller --onedir .\demo.py`), `print` does not work. I only see messages from WebDriver manager:

![image](https://user-images.githubusercontent.com/68119338/120232909-3c0a7f00-c25d-11eb-9afb-b344c42ec568.png)

 Development environment:

- Windows 10 x64;
- Python 3.8.3;
- Gooey 1.0.8;
- PyInstaller 4.3;

**Comment by Shadoward** [comment]
@Podolyan98 you need to use the flush option.
```
print('Driver started', flush=True)
```
