### ISSUE TITLE
[QUESTION] How can we change the "Choose One" text above a `mutually_exclusive_group`?

### ISSUE THREAD

**Issue by chwba** [chriskiehl/Gooey#704]
^

**Comment by chriskiehl** [comment]
You can use the (currently undocumented it seems (TODO)) `title` Gooey option. 

```
parser = GooeyParser(description='An example of polling for updates at runtime')
    g = parser.add_argument_group()
    stuff = g.add_mutually_exclusive_group(
        required=True,
        gooey_options={
            'title': "Howdy"
        }
    )
```

![image](https://user-images.githubusercontent.com/1408720/120581165-2de46c00-c3df-11eb-9ef2-22a5ffbbae65.png)

**Comment by chriskiehl** [comment]
Oh, btw, you could also use `options` which'll let your IDE show what's available. 

```python
from gooey import options

...
    parser = GooeyParser()
    g = parser.add_argument_group()
    stuff = g.add_mutually_exclusive_group(
        required=True,
        gooey_options=options.MutexGroup(title='Hello world!')
    )
```

I'll update the docs shortly.

**Comment by primal100** [comment]
Neither of those options seem to work in v 1.0.8.1

**Comment by chriskiehl** [comment]
Hey @primal100, could you fill out an issue with all the usual details (os, version, python, etc..) and a code sample demoing the problem? 

I'm unable to (not) reproduce in 1.0.8.1.
