### ISSUE TITLE
Add support for "Save" file dialogs

### ISSUE THREAD

**Issue by amorde** [chriskiehl/Gooey#71]
Right now, file dialogs can only open existing files. An example use case for a "save" dialog would be specifying where to save the result of the program, where to save some sort of file output, etc.

[Relevant section of code](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/widgets/choosers.py#L94)

**Comment by chriskiehl** [comment]
Done! 

I added Widget types for all of the `styles` supported by `wx.FileDialog`, so, saving, choosing, choosing multiple, and directories are now in there. 

you can run `widget_demo.py` to check them out. 

![image](https://cloud.githubusercontent.com/assets/1408720/6312792/424373d0-b955-11e4-83a4-970241a12bfa.png)

**Comment by amorde** [comment]
Dude, you are so awesome. Thank so you much!
