### ISSUE TITLE
Gooey displays %% in help strings

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#711]
- [ ] OS

Ubuntu 20.04

 - [ ] Python Version 

3.8.5

 - [ ] Gooey Version 

1.0.8.1

 - [ ] Thorough description of problem 
     - [ ] Expected Behavior 

        If using `%%` notation in argparse help strings, display one percent symbol, not two.

     - [ ] Actual Behavior 

         Two percent symbols are shown in the GUI.

 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 

```
import argparse
from gooey import Gooey

@Gooey
def process_options():
    parser = argparse.ArgumentParser()
    parser.add_argument("--grids", type=str, help='top x%% of data')
    return parser.parse_args()

args = process_options()
```

**Comment by chriskiehl** [comment]
Fixed in 1.2.0
