### ISSUE TITLE
Gooey window freezes when closing the window

### ISSUE THREAD

**Issue by slavinskikt** [chriskiehl/Gooey#712]
Hello!

Below describes the problem I'm facing. I've seen a similar issue listed here (https://github.com/chriskiehl/Gooey/issues/592). However, it was marked as closed, and my problem persists.

 - [Windows] OS
 - [3.8.8] Python Version 
 - [1.0.8] Gooey Version
 
 - **Description**: Gooey window becomes unresponsive upon attempting to exit the window with either "X", "cancel", or "close" (latter case upon program completion). This issue persists until exiting the IDE all together. Attempting to stop the program via the command prompt fails as well while the gooey window is open.
     - **Expected Behavior**: The gooey window to close.
     - **Actual Behavior**: The gooey window becomes unresponsive.
 - **Code Example**:

```
from gooey import Gooey, GooeyParser
@Gooey()
def main():
    parser = GooeyParser()
    parser.add_argument(
        "-i",
        "--input_file", 
        required=True,
        help="File to be converted")
    args = parser.parse_args()
    print(args)

if __name__ == "__main__":
    main()
```

Thank you for any/all help! Please let me know if you need further information
 

**Edit**: This is when running the program via Spyder IDE (v. 4). Gooey window works fine (i.e., does not become unresponsive) when running via the conda prompt. Is there a way to run gooey in the IDE without this issue occurring?

**Comment by victor2alan** [comment]
I also encountered this problem, and finally found that it was a problem with Spyder. 
Using the default method of run, the “close window and freezing screen” appeared. 
But it’s okay to configure run as "execute in an external system terminal"

**Comment by slavinskikt** [comment]
> I also encountered this problem, and finally found that it was a problem with Spyder.
> Using the default method of run, the “close window and freezing screen” appeared.
> But it’s okay to configure run as "execute in an external system terminal"

@victor2alan That worked. I appreciate it!

**Comment by chriskiehl** [comment]
Thanks @victor2alan!
