### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by HollowHeartNet** [chriskiehl/Gooey#713]
Hi,

Please let me know how to cite this library for my research project. 
Thanks.

Best,

**Comment by chriskiehl** [comment]
Howdy, 

I'm not totally sure how to answer your question. My guess is you'd do something [like this](https://guides.libraries.uc.edu/citing/code)? 

is there something specific you're after?

**Comment by HollowHeartNet** [comment]
Howdy Horrido,

Thank you bro. I was just wondering if there is a predefined BibTeX source available for Gooey. Or how do you prefer your tool to be cited? 

Cheers

**Comment by chriskiehl** [comment]
Nope. No predefined BibTex source nor any kind of citation preference. This is the first time the question has come up, so I don't have any opinions ^_^ 

What's your research project (if I may ask)?

**Comment by HollowHeartNet** [comment]
Ok. In this case I will use the following BibTeX source if you don't mind:

@Misc{Gooey2021,
  author       = {Chris Kiel},
  howpublished = {\url{https://github.com/chriskiehl/Gooey}},
  title        = {Gooey},
  year         = {2021},
  journal      = {GitHub repository},
  publisher    = {GitHub},
}

Unfortunately, the information regarding the project is confidential, so I can't tell you about it. 
But it's nothing special, I can tell you that much.  :-D

**Comment by chriskiehl** [comment]
👍
