### ISSUE TITLE
Checkbox value is always True if default is restored from a previous run

### ISSUE THREAD

**Issue by bitcity** [chriskiehl/Gooey#714]
- [x] OS : Ubuntu 16.04
 - [x] Python Version : 3.5
 - [x] Gooey Version  : 1.0.8.1

 - [x] Thorough description of problem : I have a simple example that has a checkbox which can be toggled by the user. I've purposely set the `default` value to be `True` in this checkbox (assuming that this configuration was loaded from a previous run, where the checkbox was `Checked`). Once the GUI comes up, I uncheck this box and click Start. 

     - [x] Expected Behavior : I expect the value of `args.checkme` to be `False` now, since it was unchecked

     - [x] Actual Behavior : The value printed is `True`

 - [x] A minimal code example 

```
import sys
from gooey import Gooey, GooeyParser

@Gooey
def main():
    parser = GooeyParser()
    parser.add_argument('--checkme', dest='checkme', action='store_true', default=True)
    args = parser.parse_args()
    print('Checkbox : ', args.checkme)

if __name__ == '__main__':       
    sys.exit(main())   
```

 - [x] Screenshot (if visual quirk) 

![image](https://user-images.githubusercontent.com/4221404/124109293-9bd68e80-da84-11eb-8796-945d80b5bb2d.png)

 
I suspect that the use of `default` with `store_true` is creating this problem. What's a good way to save the state of a checkbox from a previous run, and still be able to toggle it successfully and save it back for future runs.

**Comment by chriskiehl** [comment]
Yeah, your intuition is correct. default + store_true ends up with argparse interpreting that flag as true regardless of whether or not that checkbox is checked. 

This use case of wanting to specify an initial argument for the GUI independent of the `default` pops up a lot, and is a missing feature in Gooey. 

Next release will introduce a new gooey_option for textboxes, `initial_value`, which will gives the exact functionality you're after.

**Comment by chriskiehl** [comment]
1.2.0 introduces the `initial_value` gooey option to resolve this problem.
