### ISSUE TITLE
gooey.gui.formatters.radioGroup() will crash

### ISSUE THREAD

**Issue by cclauss** [chriskiehl/Gooey#721]
Hello There, Future Issue Creator! 

>README: Are you suddenly seeing errors related to Alignment flags when starting Gooey?

__No.__

Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Found a bug? Just a friendly heads up, _debugging it requires information from you!_ Make sure the template below is filled out in its entirety. 

 - [x] OS __All OSes__
 - [x] Python Version __All versions of Python__
 - [x] Gooey Version __code in this repo__
 - [x] Thorough description of problem __This code will raise NameError__
     - [x] Expected Behavior __Exposed function do not crash__
     - [x] Actual Behavior  __This code will raise NameError__
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) __Irrelevant__
 - [x] Screenshot (if visual quirk)  __Irrelevant__
 - [x] Anything else you may think will be helpful  __Automated testing__
 
 https://github.com/chriskiehl/Gooey/blob/1.0.9-release/gooey/gui/formatters.py#L12_L17 will raise NameError because `self` is an undefined name.

Thanks! ^_^

**Comment by chriskiehl** [comment]
Ah, that's an old vestigial function that's unused. Removed here 074d480! 👍
