### ISSUE TITLE
disable_progress_bar_animation not working

### ISSUE THREAD

**Issue by primal100** [chriskiehl/Gooey#722]
Hi,

I want to use Gooey for a long-running application, namely a TCP server, which the user initially configures and then runs, and can stop whenever they want. In that context a progress bar and the stop message about potential loss of data doesn't make sense. But I try to disable the progress bar but it still exists. Simple example below.

Expected Behaviour: No progress bar
Actual Behaviour: Progress bar visible

 - [x] OS Windows 10
 - [x] Python Version 3.8.10
 - [x] Gooey Version 1.0.8.1
 - [x] Thorough description of problem 
     - [x] Expected Behavior 
     - [x] Actual Behavior 
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [x] Screenshot (if visual quirk) 
 - [x] Anything else you may think will be helpful 
 
Code example:

```python
import argparse
import socketserver
from gooey import Gooey



class EchoHandler(socketserver.BaseRequestHandler):

    def handle(self):
        data = self.request.recv(1024).strip()
        print("{} wrote:".format(self.client_address[0]))
        print(data)
        self.request.sendall(data.upper())


def run_server(host, port):
    print('Starting server on %s:%d' % (host, port))
    with socketserver.TCPServer((host, port), EchoHandler) as server:
        server.serve_forever()


@Gooey(show_stop_warning=False, hide_progress_msg=True,  disable_progress_bar_animation=True)
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--host', type=str, default='0.0.0.0')
    parser.add_argument('-P', '--port', type=int, default=4000)
    args = parser.parse_args()
    run_server(args.host, args.port)


if __name__ == "__main__":
    main()
```
 
![image](https://user-images.githubusercontent.com/6353787/126112571-29880b1a-4553-4995-a0f0-61de94cbbab4.png)

**Comment by chriskiehl** [comment]
Howdy, 

Also, just to clarify a bit, what `hide_progress_msg` does is filter out the _text_ which appears in the console. It's only useful when paired with one of the progress regex args. 

That said, it does totally look like `disable_progress_bar_animation` is in fact busted. I've updated the title of your issue. Will go into 1.0.9 shortly.

**Comment by chriskiehl** [comment]
Fixed on the [release branch](https://github.com/chriskiehl/Gooey/commit/a66f56edd67de4d75e69b8d8877b083ce270c44a)
