### ISSUE TITLE
Question: pyinstaller

### ISSUE THREAD

**Issue by rowlesmr** [chriskiehl/Gooey#726]
How big do executables get when using pyinstaller?

About 64 kb of python has been turned into an 85 Mb executable. All of my imports are base python, apart from Gooey.

**Comment by soliverc** [comment]
Same happens with my gooey apps. I think it's including everything in the environment. Pandas, numpy etc etc. Not just the little .py file.

**Comment by rowlesmr** [comment]
Shouldn't it look at my imports, and just take those?

**Comment by chriskiehl** [comment]
Good question for the [Pyinstaller folks](https://github.com/pyinstaller/pyinstaller/issues)
