### ISSUE TITLE
How to create an app with no arguments? I only want the Start and Cancel button. 

### ISSUE THREAD

**Issue by soliverc** [chriskiehl/Gooey#727]
I want to create an app with no user input, other than clicking "Start". They don't need to select files or locations, it is all contained in the code. 

How do I go about this?

I have tried removing the GooeyParser code altogether:

```python

import pandas as pd
from gooey import Gooey, GooeyParser

@Gooey(program_name="My Cool App",  default_size=(710, 700))

# Gooeyparser is supposed to go here

def python_function():
    # random_pandas_stuff
   # save csv to computer

if __name__ == '__main__':
    
    python_function()
    
 ```

But that doesn't work. The app doesn't appear at all. 

I have "hacked" something together below, which does work. However it doesn't feel right. 

I have used Gooeyparser, but there are no arguments. 

```python

import pandas as pd
from gooey import Gooey, GooeyParser

@Gooey(program_name="My Cool App",  default_size=(710, 700))

def parse_args():

    parser = GooeyParser(description='Merge Name and Address Dataframes')
    
    args = parser.parse_args()
    return args

def python_function():
    # random_pandas_stuff
   # save csv to computer

if __name__ == '__main__':
    
    args = parse_args()
    python_function()
```

As you can see, there are no args to parse. However I now have at least a UI for my script. 

Could I break something by using it this way? 

Is there a better method?

I see there is a "No Config" mode, however it is not clear from the documentation how to do that.

Thank you

**Comment by chriskiehl** [comment]
Hey, what you're after is `auto_start`. Here's a small example. 

```python
from gooey import Gooey, GooeyParser


@Gooey(auto_start=True)
def main():
    parser = GooeyParser(description='Process some integers.')

    parser.parse_args()
    print('Hooray!')


if __name__ == '__main__':
    main()
```

Thanks for letting me know the README wasn't clear. Updated! :+1:
