### ISSUE TITLE
problem importing a module using Gooey within another script using Gooey as well

### ISSUE THREAD

**Issue by Oneiroe** [chriskiehl/Gooey#739]
First of all thanks for this awesome tool!

 - OS: Ubuntu 18.04.5 LTS
 - Python Version: 3.6 
 - Gooey Version: 1.0.8.1

I encountered the following issue: within a script using Gooey, it seems that importing another module using Gooey as well compromises the correct execution of the program.

Here is a simple minimal example.
We have 2 scripts `my_sum.py` and  `main.py`. The `main.py` imports a function `sum_that()` from `my_sum.py`. Because both can be executed independently, a Gooey interface is implemented for each one.

```python
# my_sum.py
from gooey import Gooey
from gooey import GooeyParser


def sum_that(a, b):
    return a + b


@Gooey
def main():
    parser = GooeyParser()
    parser.add_argument('-a', '--aaa', help='number a', type=int,
                        widget='IntegerField', default=1, gooey_options={'min': 0, 'max': 100})
    parser.add_argument('-b', '--bbb', help='number b', type=int,
                        widget='IntegerField', default=1, gooey_options={'min': 0, 'max': 100})
    args = parser.parse_args()

    print(sum_that(args.aaa,args.bbb))


if __name__ == '__main__':
    main()
```

```python
# main.py
from gooey import Gooey
from gooey import GooeyParser

from my_sum import sum_that


@Gooey
def main():
    parser = GooeyParser()
    parser.add_argument('-a', '--aaa', help='number a', type=int,
                        widget='IntegerField', default=1, gooey_options={'min': 0, 'max': 100})
    parser.add_argument('-b', '--bbb', help='number b', type=int,
                        widget='IntegerField', default=1, gooey_options={'min': 0, 'max': 100})
    parser.add_argument('-c', '--ccc', help='number c', type=int,
                        widget='IntegerField', default=1, gooey_options={'min': 0, 'max': 100})
    args = parser.parse_args()

    print(sum_that(args.aaa, args.bbb) * args.ccc)


if __name__ == '__main__':
    main()
```

Executing `main.py` leads to some problems:
- calling `python main.py --ignore-gooey -h` fails to block Gooey and the GUI is launched anyway.
- Launching the GUI via `python main.py` resulted in a circular recalling of the same window: once provided the parameters and clicked start, another window is open to reinsert the parameters, and so on and so forth.
 
The behaviour is altered by just the import of the other module, even without using it.

I would expect that if the script is not called via the main() function, Gooey should not interfere with the other functionalities of the module. 
Indeed a workaround is to split the script separating the functionalities from the GUI interface, in order to remove any Gooey reference from the import chain import.

Nevertheless, is this an expected behaviour or a bug? Thanks!

**Comment by chriskiehl** [comment]
This was a bug. Gooey used to mutate the sys.argv structure to pop off the `--ignore-gooey` argument. Turns out, modifying global mutable state willy-nilly causes problems! 

1.2.0 should fix this problem for you.
