### ISSUE TITLE
Support for docopt

### ISSUE THREAD

**Issue by patkujawa-wf** [chriskiehl/Gooey#74]
http://docopt.org/ (python project at https://github.com/docopt/docopt) is a great tool for commandline scripts. It would be great to have Gooey support it :)

**Comment by piotr-dobrogost** [comment]
I guess you did not try to [search](https://github.com/chriskiehl/Gooey/issues?q=is%3Aissue+docopt+) existing issues for word *docopt*?

**Comment by patkujawa-wf** [comment]
My apologies, I did not. I looked at the open issues, but didn't actually think it would be a popular enough request that someone would already make it and didn't think to search all/closed issues. Sorry.
