### ISSUE TITLE
Textfield misbehaves with Mandatory Dropdown

### ISSUE THREAD

**Issue by impratikjaiswal** [chriskiehl/Gooey#742]
Hello There, 

 - [ ] OS: Windows 10
 - [ ] Python version is 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
 - [ ] Gooey Version is 1.3.8
 - [ ] Thorough description of problem : Need to add few required fields. 1 dropdown, 1 integer & 1 Text Field .
     - [ ] Expected Behavior:  All fields should display according to inputs.
     - [ ] Actual Behavior: Setting Drop down Field as 'required_field' is converting Text & integer fields to dropdown. 
      Please refer two code snippets along with screen shot.
          - [ ] 1st: Dropdown is set as Optional Arguments
          - [ ] 2nd: Dropdown is set as Required Arguments

 - [ ] A minimal code example -- 1st code snippet
 > @Gooey()
> def main():
>   parser = GooeyParser(description='Process some data.')
>   parser.add_argument('required_field', metavar='Some Field 1', type=int, help='Enter some numbers!')
>   parser.add_argument('required_field', metavar='Some Field 2', help='Enter some text!')
>   `parser.add_argument('--test', metavar='Some Option', help='Select a Option', widget='Dropdown', choices=['a', 'b', 'c'])`
>   parser.add_argument('-f', '--foo', metavar='Some Flag', action='store_true', help='I turn things on and off')
>   parser.parse_args()
  - [ ] Screenshot 1
![image](https://user-images.githubusercontent.com/12963893/133246491-5f5d93e5-40fb-43a4-8bc2-b3feaf8eae99.png)

 - [ ] A minimal code example -- 2nd code snippet
> @Gooey()
> def main():
>     parser = GooeyParser(description='Process some data.')
>     parser.add_argument('required_field', metavar='Some Field 1', type=int, help='Enter some numbers!')
>     parser.add_argument('required_field', metavar='Some Field 2', help='Enter some text!')
>     `parser.add_argument('required_field', metavar='Some Option', help='Select a Option', widget='Dropdown', choices=['a', 'b', 'c'])`
>     parser.add_argument('-f', '--foo', metavar='Some Flag', action='store_true', help='I turn things on and off')
>     parser.parse_args()
  - [ ] Screenshot 2
![image](https://user-images.githubusercontent.com/12963893/133247960-eb68c009-056b-4dfb-a570-e69abbe81120.png)

Thanks! ^_^

**Comment by chriskiehl** [comment]
Howdy! 

I'm not sure I understand your issue, so you may need to explain a bit more. Is the confusion why it ends up in the required section in the second example? 

(if so, that's because without the `--test` prefix, you're creating a `positional` argument, which is indeed required)

**Comment by impratikjaiswal** [comment]
> Howdy!
> 
> I'm not sure I understand your issue, so you may need to explain a bit more. Is the confusion why it ends up in the required section in the second example?
> 
> (if so, that's because without the `--test` prefix, you're creating a `positional` argument, which is indeed required)

**Comment by impratikjaiswal** [comment]
Hello,

sorry for the confusion. Let me try to explain more.

Indeed, I need the all 3 `positional` arguments as mentioned in second example.
Problem is not with 3rd argument. Problem is with 1st & 2nd argument.

In my case, as soon as 3rd argument (`Dropdown`) is set as `positional` argument,  my first 2 `positional` arguments are being displayed as `Dropdown`, but they are originally Text fields.

Please refer highlighted box in screen shot.

Hope This clarifies.
![image](https://user-images.githubusercontent.com/12963893/133727514-30000caf-a9aa-45ba-aae9-a9a18b2cf0eb.png)

**Comment by chriskiehl** [comment]
Oh! Yeah, that's... that's odd. 

I'll look into this shortly!

**Comment by chriskiehl** [comment]
Ah, upon closer inspection, I see the issue. You've supplied the same name, `required_field`, for each parameter. 

Gooey internally build a map keyed off of the argument name expecting it to be unique. As such, you end up with `required_field` being tied to `Dropdown`. 

```
@Gooey()
def main():
    parser = GooeyParser(description='Process some data.')
    parser.add_argument('required_field1', metavar='Some Field 1', type=int, help='Enter some numbers!')
    parser.add_argument('required_field2', metavar='Some Field 2', help='Enter some text!')
    parser.add_argument('required_field3', metavar='Some Option', help='Select a Option', widget='Dropdown', choices=['a', 'b', 'c'])
    parser.add_argument('-f', '--foo', metavar='Some Flag', action='store_true', help='I turn things on and off')
    parser.parse_args()
```

Differentiating the values will correct your problem.

**Comment by impratikjaiswal** [comment]
> Ah, upon closer inspection, I see the issue. You've supplied the same name, `required_field`, for each parameter.
> 
> Gooey internally build a map keyed off of the argument name expecting it to be unique. As such, you end up with `required_field` being tied to `Dropdown`.
> 
> ```
> @Gooey()
> def main():
>     parser = GooeyParser(description='Process some data.')
>     parser.add_argument('required_field1', metavar='Some Field 1', type=int, help='Enter some numbers!')
>     parser.add_argument('required_field2', metavar='Some Field 2', help='Enter some text!')
>     parser.add_argument('required_field3', metavar='Some Option', help='Select a Option', widget='Dropdown', choices=['a', 'b', 'c'])
>     parser.add_argument('-f', '--foo', metavar='Some Flag', action='store_true', help='I turn things on and off')
>     parser.parse_args()
> ```
> 
> Differentiating the values will correct your problem.

Thank You @chriskiehl for you help & support.
My issue is solved.

**Comment by chriskiehl** [comment]
Hooray! ^_^
