### ISSUE TITLE
Wrong file picker used for reading existing files on Linux

### ISSUE THREAD

**Issue by makeworld-the-better-one** [chriskiehl/Gooey#743]
- Linux
- XFCE (GTK)
- Python 3.9.7
- Gooey 1.0.8.1

Gooey is using the wrong kind of file opener when the `argparse` `parser.add_argument` function has `type=argparse.FileType("r", encoding="UTF-8")`. The file picker that shows up is a file picker for saving a file, with a filename prompt. If you select an already existing file, it'll warn you that your file is going to be overwritten! But this is not true, as the file is just used for reading.

I suggest that Gooey look at whether the file is going to be for reading or writing, and choose the correct file picker based on that. In this case, the other file picker that's for opening files should have been chosen.

Here is a screenshot of the file picker for saving files, the one that shows up right now.

![image](https://user-images.githubusercontent.com/25111343/133647291-65067a43-7990-43b7-93f6-458ca12255a8.png)

And here is the file picker menu, which doesn't appear for this case but should.

![image](https://user-images.githubusercontent.com/25111343/133647098-248d87c5-2db3-4b11-9eb8-d704e2aa6004.png)

**Comment by chriskiehl** [comment]
This has been fixed on the [release branch](https://github.com/chriskiehl/Gooey/commit/e98c5a496e26c391dc1bf730d9b39ca4e3467c37)

**Comment by makeworld-the-better-one** [comment]
Good to hear, thanks!
