### ISSUE TITLE
Validate types by default

### ISSUE THREAD

**Issue by makeworld-the-better-one** [chriskiehl/Gooey#744]
- Linux
- Python 3.9.7
- Gooey 1.0.8.1
 
Even with `run_validators=True`, Gooey doesn't seem to validate the `type` argument to `argparse`'s `parser.add_argument`. It'd be nice if by default, Gooey would validate that fields that have `type=int` are actually integers before handing them off to the user's code, and do the same for any type.

**Comment by chriskiehl** [comment]
[Background on why it cannot be done by default is here](https://github.com/chriskiehl/Gooey/issues/293). However, 1.2.0 enables functionality that _does_ check the types via a secondary call to your program. You can check it out by passing `use_events=[Events.FORM_VALIDATION]` to the decorator.
