### ISSUE TITLE
Option to reset or clear all parser fields/widgets

### ISSUE THREAD

**Issue by hschokker** [chriskiehl/Gooey#751]
I use Gooey not to start a command line program but to store some entries to a text file. After running the program I would like to have the option to clear or reset all fields if processing went OK. 

Is there currently a possibility to do this or could you make this a feature?

**Comment by chriskiehl** [comment]
Yep, yep! Checkout the `clear_before_run` option in the [global config section of the README](https://github.com/chriskiehl/Gooey#global-configuration). 

You pass it to the decorator to control behavior. 

```python 
@Gooey(clear_before_run=True)
def main(): 
   ... 

```

**Comment by chriskiehl** [comment]
That is some impressive monkey patching @pasbec ! O_o

**Comment by joshhammock** [comment]
@pasbec This was an amazing help. Is there any tweak that could be made to trigger the dynamic update on Start when the variable return_to_config = True ? I'd love to be able to bypass the stdout view and still have the values dynamically update.
