### ISSUE TITLE
SetLabelText() throws an error

### ISSUE THREAD

**Issue by myegorov** [chriskiehl/Gooey#76]
BaseFileChooser class definition in widget_pack.py:
fixed by changing
self.text_box.SetLabelText(result) --> self.text_box.SetValue(result)

**Comment by chriskiehl** [comment]
Context please.

**Comment by myegorov** [comment]
Here's what happens when I browse to a file in widget_demo.py example:

```
max@tp:/usr/local/lib/python2.7/dist-packages/gooey/examples$ python widget_demo.py
...
inside of main(), my_cool_parser = <gooey.python_bindings.gooey_parser.GooeyParser object at 0x256e410>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/widgets/widget_pack.py", line 82, in onButton
    self.text_box.SetLabelText(result)
AttributeError: 'TextCtrl' object has no attribute 'SetLabelText'
```

Thanks

**Comment by chriskiehl** [comment]
This one is a little strange. For one, it doesn't explode on Windows. Stranger still is that `SetLabelText` definitely a method on `TextCtrl`'s parent. So.. kinda quirky. 

Either way. Change has been made.
