### ISSUE TITLE
richtext_controls no working

### ISSUE THREAD

**Issue by kuanghy** [chriskiehl/Gooey#764]
<img width="737" alt="WX20211122-212433@2x" src="https://user-images.githubusercontent.com/8775508/142870200-8ebafa47-944c-4630-9d62-cfa1a5aefa57.png">

OS：macOS 11.5.2
Python:  3.8.5
Gooey: 1.0.8.1

**Comment by gcolombeau** [comment]
I had the same behavior and found out that the colored library is now TTY aware by default since version 1.4.3.
You now need to force enable color via environment variables or disable the TTY awareness:

```Python
colored.set_tty_aware(False)
```

**Comment by wy281704862** [comment]
# 编码修复
if sys.stdout.encoding != 'UTF-8':
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
if sys.stderr.encoding != 'UTF-8':
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

**Comment by kuanghy** [comment]
> ```python
> colored.set_tty_aware(False)
> ```
