### ISSUE TITLE
Min and Max values for IntegerField / DecimalField / Slider widgets are not used

### ISSUE THREAD

**Issue by HunterAP23** [chriskiehl/Gooey#765]
- OS: Windows 10 version 21H2 (19044.1348)
 - Python Version: 3.9.5 (tags/v3.9.5:0a7dcbd)
 - Gooey Version: 1.0.8.1
 - The issue: when assigning a min or a max value to IntegerField, DecimalField, or Slider widgets, the given min and max values are not used.
     - Expected Behavior: the widgets only allow the user to go between the assigned min and max values.
     - Actual Behavior: the widgets range from 0 to 100. The user is able to change the values of the widgets as they see fit, and are not bound by the limits set by the program - they seem to use the default min/max values that Gooey uses globally.

Code Example:
```py
import gooey
from gooey import Gooey

@Gooey
def main():
    parser = gooey.GooeyParser(description='Add two integers together, then subtract a decimal')
    parser.add_argument('--first', type=int, widget="IntegerField", gooey_options={min: 5, max: 20})
    parser.add_argument('--second', type=int, widget="Slider", gooey_options={min: 1, max: 10})
    parser.add_argument('--third', type=int, widget="DecimalField", gooey_options={min: 0, max: 5.0})
    args = parser.parse_args()
    print(args.first + args.second - args.third)

main()
```
Screenshot example of the issue:
![image](https://user-images.githubusercontent.com/14364070/144198659-d130f183-f935-49cd-ac5b-8267a5a6eaa8.png)

**Comment by chriskiehl** [comment]
Oh, this is a bit silly. I made the same mistake in the docs (will fix momentarily). `min` and `max` are python functions, so you when you specify them in the options, you're actually putting a key of something like `<function__builtin_min>`, which causes the lookup elsewhere to fail. 

If you wrap all your keys in quotes, everything works as expected. 

```python


import gooey
from gooey import Gooey

@Gooey
def main():
    parser = gooey.GooeyParser(description='Add two integers together, then subtract a decimal')
    parser.add_argument('--first', type=int, widget="IntegerField", gooey_options={'min': 5, 'max': 20})
    parser.add_argument('--second', type=int, widget="Slider", gooey_options={'min': 1, 'max': 10})
    parser.add_argument('--third', type=int, widget="DecimalField", gooey_options={'min': 0, 'max': 5.0})
    args = parser.parse_args()
    print(args.first + args.second - args.third)

main()
```

**Comment by chriskiehl** [comment]
Docs updated!

**Comment by HunterAP23** [comment]
I would be lying if I said that part of my brain went "oh isn't min/max going to register as a function instead of a keyword?", but I figured that because it was was a key-value pair that it would work. My mistake was programming late at night and not fully paying attention.

Thank you for pointing out the fix and reflecting that on the docs, cheers!
