### ISSUE TITLE
Can you make a gui version?

### ISSUE THREAD

**Issue by upintheairsheep** [chriskiehl/Gooey#768]
Can you make a gui version of gooey?

Hello There, Future Issue Creator! 

>README: Are you suddenly seeing errors related to Alignment flags when starting Gooey? Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Found a bug? Just a friendly heads up, _debugging it requires information from you!_ Make sure the template below is filled out in its entirety. 

 - [ ] OS
 - [ ] Python Version 
 - [ ] Gooey Version 
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior 
     - [ ] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
I do not understand your question

**Comment by upintheairsheep** [comment]
Make a GUI builder for Gooey so you use GUI to turn a command line application to a gui application.
