### ISSUE TITLE
The last version of Gooey that supports Python2.7 is 1.0.4.0

### ISSUE THREAD

**Issue by ddcatgg** [chriskiehl/Gooey#771]
Dear all:

The last version of Gooey that supports Python2.7 is 1.0.4.0, because I use Gooey in a Python2.7 environment, and it cannot be imported successfully when the Gooey version is greater than or equal to 1.0.5, as their codes depend on the features of Python3.

Therefore, please update the Python version dependency information of Gooey from version 1.0.5 and later on PyPi,
Or it will confuses beginners.
Thanks!

 - [ ] OS
 - [x] Python Version: 2.7
 - [x] Gooey Version: 1.0.5+
 - [x] Thorough description of problem : 
     - [x] Expected Behavior : Correct dependency description
     - [x] Actual Behavior : Incorrect dependency description
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [x] Screenshot (if visual quirk) 
 ![image](https://user-images.githubusercontent.com/8475003/147543483-2f6d54c0-fff9-405b-b75b-7bdb1461a031.png)

 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
Good call. 2.7 has been removed!
