### ISSUE TITLE
Love it!  But, getting started.

### ISSUE THREAD

**Issue by series0** [chriskiehl/Gooey#776]
So, new to python.  C coder from the dawn of time.

 - [ Windows 10 Pro] OS
 - [3.9.9 ] Python Version 
 - [4? current? ] Gooey Version 
 - [See below ] Thorough description of problem 
     - [starter.py (gooey included) transfers control properly to the command line python file I already had.] Expected Behavior 
     - [ command line driven python file output: 'list index out of range' (checking for sys.argv values early) and select arguments are not found in the namespace.] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [ ] Screenshot (if visual quirk) 
 - [See Below ] Anything else you may think will be helpful 
 
I read your example or several and, wow, I need this fast interface building thing, so THANKS!

But it isn't working as is.

Detail of issue:

**I have a non-class python source file with the first code being this:**

try:
    usr = str(sys.argv[1])
    psw = str(sys.argv[2])
    locationId = str(sys.argv[3])
    facilityId = str(sys.argv[4])
 ...
 
 **my convert() function in the gooey imported wrapper is this:**

def convert(user, password, locationID, facilityID, folder_address, customer, location, group, format, days, proc, mode):
    (
        rad_MCNA (mode, proc, days, format, group, location, customer, folder_address,facilityID, locationID, password, user).run()
    )

That is after I do all the parameter initialization (for all 11) LIKE this one example:

parser.add_argument(
            "-i",
            "--DOP location ID",
            required=True,
            help="the location id of the location for which you are accessing the web portal",
            widget='Dropdown',
            choices=get_location_locationID(),
        )

**which at this time uses this means of setting defaults (bleh):**

def get_location_locationID():
    return ['15Yow']

Which brings up a question 1:
Is there a add_argument tuple for default values CHOSEN?  I tried to find that in the docs, but no joy.  If there is not a way, dare I say there should be one.  My module has 11 parameters and in general I want to have a default set for testing to avoid 11 combo choices each test run.

So, I cannot get the convert control to transfer properly.  It's probably my python lack of knowledge.  The GUI comes up great!  But after the progress bar I get this screen:

![image](https://user-images.githubusercontent.com/97316990/148614430-b96236f5-1906-4ff3-bf42-1c8c2b322c5d.png)

Hmmm ... I cannot see that image inline, hope it worked.  

Question about that one is ... question 2:
Namespace?  what namespace?  and doesn't include for sure only 1 of the 11 parameters (odd).  

Note:  In examples I saw out there, there was included a requirements.txt file which I ASSUMED (ikr) was only informational and not functional.  Let me know if that is ... wrong.

question 3 is more like, 'Help!'

I would ... again ASSUME it should be doing the gooey wrapper thing FIRST, THEN running through the wrapped non-class file.  But debugging shows otherwise.

**Comment by chriskiehl** [comment]
I can't quite read your examples cause the formatting is all broken. If you wrap them in three backticks (```), they'll maintain your formatting and indentation. 

Like this:

\```
```python 
def hello():
    print('Howdy!')
```
\```

Going from top-to-bottom based on what I understand of your post: 

```
usr = str(sys.argv[1])
psw = str(sys.argv[2])
locationId = str(sys.argv[3])
facilityId = str(sys.argv[4])
```

If you're seeing list index out of range, it may be coming from this spot if it's getting executed before any arguments are supplied. I can't tell from your examples where this is being used. However, generally speaking, the whole idea behind something like Argparse (or any CLI parser) is that you _don't_ have to manually deal with grabbing things out of the input by hand based on list indices. 

** question 1**

I'm not sure what you're trying to accomplish tbh. You're trying to set defaults for ALL of your arguments, or just your dropdown...? 

Either way, all arguments accept a `default` parameter which seed the UI with your specified value. Here's an example of pre-selecting multiple things in a Listbox. 

```
parser.add_argument(
        '--filteroption4', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        widget='Listbox',
        required=True,
        nargs='*',
        metavar='Select Column Name',
        default=['sku', 'foo']
    )
```

**Question 2:**

>Namespace? what namespace? 

Namespace comes from Argparse, not Gooey. When you call `parse_args()`, what you get back is an args Namespace with everything it parsed out of the command line. 

It may be worth trying out a few argparse only programs to make sure you understand how it works before layering on Gooey. The [docs](https://docs.python.org/3/library/argparse.html) are super good. Once you've got a handle on the root technology, adding Gooey should be a little more straight forward, as it's just a pretty skin on top of CLI arguments. 

**Question 3:**

Lifecycle info: 

Decorators, like Gooey, are evaluated at module parse time. So, yeah, the first thing that happens is Gooey wraps your function and monkey patches some argparse internals. 

At execution time, your code is run up until the `parse_args()` call, at which point, the monkey patch kicks in, and Gooey takes over. Note that your code is **NOT** run again from this process. Once Gooey has control, it has control forever. 

So how does your code actually run? 

In the main process, Gooey opens a subprocess calls your program with the cli args _plus_ a special flag called `--ignore-gooey`. Now, when your program launches, the Gooey wrapper sees this special flag, and rather than boostrapping its UI as usual, it hands control back to your program. 

This is why, if you're debugging, you won't ever see your code have control -- because it _doesn't_ get control in the thread you're running your debugger --  it all happens in a different process and communication is done over stdout/err. 

Not sure if that helps or not, but there's some background.

**Comment by series0** [comment]
That was an awesome explanation.  Thank you.  Assuming I have time today I will adjust for all of it.  I could have sworn I tried the default tuple setting and that it didn't work, but great to know to stick with it until I get it right.  

Thanks so much!
