### ISSUE TITLE
Menus Not Appearing

### ISSUE THREAD

**Issue by BrianArbuckle** [chriskiehl/Gooey#779]
Hello There, Future Issue Creator! 

>README: Are you suddenly seeing errors related to Alignment flags when starting Gooey? Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Found a bug? Just a friendly heads up, _debugging it requires information from you!_ Make sure the template below is filled out in its entirety. 

 - [ ] OS, Mac OS 10.15.7
 - [ ] Python Version 3.9.5
 - [ ] Gooey Version 1.0.8.1
 - [ ] Thorough description of problem Menus don't appear and function in the GUI, as described in the readme, even using the ReadMe code, see below. 
     - [ ] Expected Behavior Menu bar rendering. 
     - [ ] Actual Behavior The Gui acts as if there is no code for the menu. 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
```
import math

from gooey import Gooey, GooeyParser

parser = GooeyParser()

@Gooey(program_name='Area of a Circle Program', 
       menu=[{ 'name':'Help', 'items': [{ 'type': 'Link', 'menuTitle':'Visit Our Site', 'url':'https://github.com/chriskiehl/Gooey' }] }] )
def main():
    parser.add_argument('-r','--radius', type=float, help='Radius of a Circle')
    args = parser.parse_args()
    area = circle_area(args.radius)
    print(area)
    
def circle_area(r:float):
    return math.pi * r*r

if __name__ == '__main__':
    main()

``` - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 

New to, and loving, Gooey! 

Thanks! ^_^

**Comment by BrianArbuckle** [comment]
Re-opening this morning, everything is working.

**Comment by chriskiehl** [comment]
Hooray! 👍
