### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by pawamoy** [chriskiehl/Gooey#789]
CONTRIBUTING and PR templates say "make sure all tests pass", but I don't think it's mentioned anywhere how to actually run the tests. No makefile, no tox/nox/pytest/ward/etc., no test lib in requirements, no GitHub Actions / Travis.
I'm a bit experienced with Python so I guessed it could be `python setup.py test`, but I'm still not even sure.

**Comment by chriskiehl** [comment]
Fair point. Gooey uses the builtin [unittest module](https://docs.python.org/3/library/unittest.html). 

Tests are run via; 
```
python -m unittest
```

Although, 99.9% of the time, I run them from PyCharm. 

I've updated the contributing doc with unittest info: https://github.com/chriskiehl/Gooey/blob/1.2.1-release/CONTRIBUTING.md
