### ISSUE TITLE
Could not find matching dataclasses when pip installing in editable mode

### ISSUE THREAD

**Issue by pawamoy** [chriskiehl/Gooey#791]
Currently working on another PR, and I try to install Gooey in a Python 3.9 venv using `pip install -e .`.
I get the following error message from pip:

```
ERROR: Could not find a version that satisfies the requirement dataclasses>=0.8 (from gooey) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses>=0.8
```

I believe a marker should be added to the dataclasses dependency so that it is installed only on Python < 3.7, as it's included in the stdlib since Python 3.7.

```diff
-    'dataclasses>=0.8',
+    'dataclasses>=0.8; python_version < "3.7"',
```

**Comment by chriskiehl** [comment]
Oh, whoa -- TIL about pip's editable mode! I've been manually sym linking like a sucker. 

I've patched setup.py with your suggestin on 1.2.1-release
