### ISSUE TITLE
Trouble installing 1.2.0a0 from pip

### ISSUE THREAD

**Issue by blipk** [chriskiehl/Gooey#809]
Hi.

 - OS - Manjaro
 - Python Version - 3.10.4
 - Gooey Version - 1.2.0a0

I'm not sure if this is a problem with my python setup or with the gooey pip distribution.
I'm trying to install version 1.2.0a0 but get the error below:
```
pip install --no-cache-dir gooey==1.2.0a0                                                                                                                                           2 ✘ 
Defaulting to user installation because normal site-packages is not writeable
Collecting gooey==1.2.0a0
  Downloading Gooey-1.2.0a0-py2.py3-none-any.whl (766 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.9/766.9 KB 6.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement dataclasses>=0.8 (from gooey) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses>=0.8
```

I try to install dataclasses==0.8 but get the following:
```
pip install --no-cache-dir dataclasses==0.8                                                                                                                                         1 ✘ 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.8
```
 
It seems PyPi has the 0.8 version but my pip won't recognize it, however as far as I understand Python>3.7 should have dataclasses included in the install and the pip module is just a backport for previous version, so perhaps this isn't a needed requirement?

Any help would be appreciated - Thanks!
 
 
EDIT: Manually downloading the .whl file from pypi and trying to install yields:
```
pip3 install dataclasses-0.8-py3-none-any.whl                                                                                                                                      Defaulting to user installation because normal site-packages is not writeable
Processing ./dataclasses-0.8-py3-none-any.whl
ERROR: Package 'dataclasses' requires a different Python: 3.10.4 not in '<3.7,>=3.6'
```

As it's included in python>3.7, I believe the gooey pip package should be configured to ignore this dependency when running such a version as I am

**Comment by abrichr** [comment]
It appears a fix was attempted here: https://github.com/chriskiehl/Gooey/pull/818

However I'm also not able to get this working:

```
python3.10 -m pip install gooey==1.2.0a0
Collecting gooey==1.2.0a0
  Using cached Gooey-1.2.0a0-py2.py3-none-any.whl (766 kB)
Requirement already satisfied: wxpython>=4.1.0 in ./env/lib/python3.10/site-packages (from gooey==1.2.0a0) (4.2.0)
Requirement already satisfied: psutil>=5.4.2 in ./env/lib/python3.10/site-packages (from gooey==1.2.0a0) (5.9.2)
Requirement already satisfied: Pillow>=4.3.0 in ./env/lib/python3.10/site-packages (from gooey==1.2.0a0) (9.2.0)
Requirement already satisfied: colored>=1.3.93 in ./env/lib/python3.10/site-packages (from gooey==1.2.0a0) (1.4.3)
Collecting typing-extensions==3.10.0.2
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
ERROR: Ignored the following versions that require a different python version: 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7
ERROR: Could not find a version that satisfies the requirement dataclasses>=0.8 (from gooey) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses>=0.8
```

For more background: https://github.com/chriskiehl/GooeyExamples/issues/36

**Comment by abrichr** [comment]
From https://github.com/chriskiehl/Gooey/pull/818/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R19:

`"dataclasses>=0.8;python_version<'3.7'"`

However:

```
>>> "3.7" < "3.10"
False
```

We need to cast `python_version` from string to float before comparison.

**Comment by abrichr** [comment]
According to https://github.com/heroku/heroku-buildpack-python/issues/1248, this was fixed in https://github.com/heroku/heroku-buildpack-python/pull/1254:

```
Updates:

setuptools from 47.1.1 to:
50.3.2 for Python 3.5
57.5.0 for Python 3.6+
```

Unfortunately, `pip install setuptools==57.5.0` downgrades from `65.3.0` and has no effect.

**Comment by abrichr** [comment]
Got it installed with `pip install git+https://github.com/chriskiehl/Gooey.git@1.2.1-release`, but this resulted in runtime errors (`wx._core.wxAssertionError` when switching between groups, and groups not getting updated.
