### ISSUE TITLE
Asks for required options when not required

### ISSUE THREAD

**Issue by nsaunier** [chriskiehl/Gooey#81]
Hi,

I have a program with 4 options, only one is required. But the GUI keeps asking to fill values for all options, or it makes an error when clicking on start.

usage: tmpj1yUVg.py [-h] -i VIDEOFILENAME [-f FIRSTFRAMENUM] [--fps FRAMERATE] [-r RESCALE] tmpj1yUVg.py: error: argument -f: expected one argument

This is on Ubuntu 14.04 with python 2.7.6 and Gooey 0.1.6 from git checked 5 min ago.

Thanks!

Nicolas

**Comment by chriskiehl** [comment]
Code sample, please.

**Comment by lrq3000** [comment]
I had a similar issue and I tried to fix it in my pull request:

https://github.com/chriskiehl/Gooey/pull/77

Could you try it and report if it fixes the issue?

**Comment by chriskiehl** [comment]
@lrq3000 FYI, I haven't forgotten about that pull :) I'd taken a bit of a hiatus from Gooey to work on other stuff -- like Gooey Builder. I can only work on Desktop apps for so long before needing a break from Wx. At any rate, I'll look over it and pull it in shortly.

**Comment by nsaunier** [comment]
Here is a sample (commenting my application specific stuff relying on OpenCV):

```
#! /usr/bin/env python

import sys, argparse
#import cvutils

from gooey import Gooey

@Gooey
def main():
    parser = argparse.ArgumentParser(description='The program displays the video.')
    parser.add_argument('-i', dest = 'videoFilename', help = 'name of the video file', required = True)
    parser.add_argument('-f', dest = 'firstFrameNum', help = 'number of first frame number to display', default = 0, type = int)
    parser.add_argument('--fps', dest = 'frameRate', help = 'approximate frame rate to replay', type = float)
    parser.add_argument('-r', dest = 'rescale', help = 'rescaling factor for the displayed image', default = 1., type = float)

    args = parser.parse_args()

    firstFrameNum = 0
    if args.firstFrameNum is not None:
        firstFrameNum = args.firstFrameNum

    frameRate = -1
    if args.frameRate is not None:
        frameRate = args.frameRate

    print('{} {} {} {}'.format(args.videoFilename, firstFrameNum, frameRate, rescale = args.rescale))
    #cvutils.playVideo(args.videoFilename, firstFrameNum, frameRate, rescale = args.rescale)

main()
```

**Comment by lrq3000** [comment]
@chriskiehl Thank you for notifying me, no problem and anyway I saw that you were less active lately, which I completely understand, and the project seems to be quite stable apart from a few glitches which are easily fixable, congrats for the great job :)
@nsaunier You can try the version of Gooey on my pull request, because Gooey by default provide empty values for all parameters, including optional ones, which will drive argparse crazy. This is fixed in my pull request.

**Comment by chriskiehl** [comment]
@nsaunier Fixed (thanks to @lrq3000 )! 

Pull a fresh copy of the repo and all should be well.

**Comment by nsaunier** [comment]
Thanks, problem solved!

**Comment by chriskiehl** [comment]
No Problemo!
