### ISSUE TITLE
Pyinstaller Packaged Gooey Application Slow Prints

### ISSUE THREAD

**Issue by ChandlerTayek** [chriskiehl/Gooey#835]
When running a Gooey application bundled with pyinstaller the prints seem to be pretty slow. I have noticed a pretty big difference between print speed running the gooey application from the command line versus running it through the `.exe` file that gets produced. The prints in the `.exe` seem to be getting flushed on a much slower interval causing a lot of prints to happen all at once then a medium delay (10ish sec) before a new batch of prints get flushed. I wasn't sure if anyone else had experienced an issue like this and had a solution.

**Comment by chilleyQSI** [comment]
Hey Chandler,

I am pretty sure I had the same issue and resolved it using the `Unbuffered` class approach at the following link:

https://stackoverflow.com/questions/107705/disable-output-buffering

**Comment by ChandlerTayek** [comment]
Worked like a charm thank you @chilleyQSI
