### ISSUE TITLE
Choices arguments showing up as TextCtrl when required

### ISSUE THREAD

**Issue by ecsellon** [chriskiehl/Gooey#85]
There's a couple issues here. First, here's the test program (run on a Windows machine with Python 2.7.9 and wxPython 3.0.0.0):

```python
from gooey import Gooey
import argparse

@Gooey
def main():
    clParser = argparse.ArgumentParser(description = 'Test program')
    clParser.add_argument('filename', help = 'name of the file to process', choices = ['fred', 'bill'])
    args = clParser.parse_args()
    print args
    
if __name__ == '__main__':
    main()
```

This will crash with the following output:

```
Traceback (most recent call last):
  File "D:\projects2\Gooey-master\test.py", line 12, in <module>
    main()
  File "D:\projects2\Gooey-master\gooey\python_bindings\gooey_decorator.py", lin
e 101, in inner
    application.run(build_spec)
  File "D:\projects2\Gooey-master\gooey\gui\application.py", line 80, in run
    frame = BaseWindow(BodyPanel, build_spec)
  File "D:\projects2\Gooey-master\gooey\gui\windows\base_window.py", line 35, in
 __init__
    self._init_components(BodyPanel)
  File "D:\projects2\Gooey-master\gooey\gui\windows\base_window.py", line 55, in
 _init_components
    self.config_panel = BodyPanel(self)
  File "D:\projects2\Gooey-master\gooey\gui\windows\advanced_config.py", line 41
, in __init__
    self._do_layout()
  File "D:\projects2\Gooey-master\gooey\gui\windows\advanced_config.py", line 72
, in _do_layout
    self.CreateComponentGrid(container, self.components.general_options, cols=se
lf._build_spec['optionals_cols'])
  File "D:\projects2\Gooey-master\gooey\gui\windows\advanced_config.py", line 81
, in CreateComponentGrid
    hsizer.Add(widget.build(self), 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)
  File "D:\projects2\Gooey-master\gooey\gui\widgets\components.py", line 29, in
build
    return self.do_layout(parent)
  File "D:\projects2\Gooey-master\gooey\gui\widgets\components.py", line 37, in
do_layout
    core_widget_set = self.widget_pack.build(self.panel, self.data)
  File "D:\projects2\Gooey-master\gooey\gui\widgets\widget_pack.py", line 133, i
n build
    self.option_string = data['commands'][0]
IndexError: list index out of range
```

This can be fixed as follows:
gooey\gui\widgets\widget_pack.py, change line 133 (in build method of class DropdownPayload) to (makes consistent with line 106 as well):

```python
self.option_string = data['commands'][0] if data['commands'] else ''
```

Next issue:
filename shows up twice in GUI; once in required section as a TextCtrl and again in optional section as a drop down

That can be fixed as follows:
gooey\python_bindings\argparse_to_json.py, change line 95 (in get_optionals_with_choices) to:

```python
  filtered_actions = [(action, widget)
                      for action, widget in actions
                      if action.choices
                      and not action.required]
```

Note: suspect similar change needed for get_flag_style_optionals, get_counter_style_optionals, and get_mutually_exclusive_optionals

Current issue:
The filename parameter is shown as TextCtrl when it has choices.

The culprit is in gooey\python_bindings\argparse_to_json.py function get_required_and_positional_args.

```python
  return [as_json(action, widget=widget or 'TextField')
          for action, widget in filtered_actions]
```

This exposes a bigger issue in that, since this all came from argparser, widget is always None so every required field will be a TextField. It seems like there needs to be a step before get_required_and_positional_args and friends are called where the actions are looked at to make sure widget isn't empty (i.e. assign a logical widget for the action if None is assigned).

Also the behavior is the same if filename was --filename and marked as required (i.e. not a positional argument).

Hope that helps.

**Comment by chriskiehl** [comment]
Issue 1,2 & 3 should now be fixed. Thanks for the detailed notes!
