### ISSUE TITLE
GooeyParser does not launch a GUI

### ISSUE THREAD

**Issue by ecsellon** [chriskiehl/Gooey#86]
Here's the test program:

```python
from gooey import GooeyParser

def main():
    clParser = GooeyParser(description = 'Test program')
    clParser.add_argument('filename', help = 'name of the file to process')
    args = clParser.parse_args()
    print args

if __name__ == '__main__':
    main()
```

No GUI pops up. Output:

```
>gooeyTest.py
usage: gooeyTest.py [-h] filename
gooeyTest.py: error: too few arguments
```

**Comment by chriskiehl** [comment]
You're missing the `Gooey` decorator :) 

Make these changes: 

    from gooey import Gooey, GooeyParser

    @Gooey
    def main():
        clParser = GooeyParser(description = 'Test program')
        clParser.add_argument('filename', help = 'name of the file to process')
        args = clParser.parse_args()
        print args

    if __name__ == '__main__':
        main()

**Comment by krisztianfekete** [comment]
@chriskiehl : sorry to contradict, but @ecsellon made an excellent point with a minimal example: `GooeyParser` is not a general drop-in replacement for `ArgumentParser`: it does not do its promised job in `.parse_args()`.

**`Gooey`'s real value is in the GUI and that it is provided through an already familiar interface: `ArgumentParser`.**

It shows in the amount of stars `Gooey` have: this is a big idea.

I thought until this issue, that it is possible to avoid the python source parsing with `GooeyParser`, as it has all the chance to collect all the relevant information in a non-magical way.  I'd say parsing data from source code the way it does is smelly!

As `GooeyParser` already has the potential, it should be a proper alternative implementation of `ArgumentParser` including its behavior of `.parse_args()`.

I'd like to suggest these to fully implement the idea:

- API change: get rid of the `@Gooey` decorator, let the `GooeyParser` be the only interface. `GooeyParser` must remain compatible with `ArgumentParser`.

- Internals change: forget parsing the source, collect information in the `GooeyParser` instance as `ArgumentParser` does - information is explicitly given at construction and through `.add_argument()` calls.

**Comment by chriskiehl** [comment]
I think allowing `GooeyParser` to run without the decorator is a good idea, but I see no reason to wholly depreciate one in favor of the other. I'd opt to let the user choose between `Argparse` with a `Gooey` decorator *OR* no decorator and a `GooeyParser`.

The idea behind Gooey's entry point being a decorator is that it can come totally as an after thought to any existing `argparse` code without requiring the client to make invasive-ish changes. One Import, one decorator, done. It's just as easy to take away as it is to add. Which I think is valuable. Point being: I think it's nifty, so I won't be phasing it out. 

>I'd say parsing data from source code the way it does is smelly!

I can't really argue that one. Parsing the source is indeed smelly. It's also a source of constant bugs and edge cases. So............ it is no more! I finally used awesome guy @SylvainDe 's suggested method for getting the parser in the decorator. Easy, clean, and no more `ast` nonsense.

**Comment by krisztianfekete** [comment]
I am aware that it is a big decision to get rid of the decorator solution, yet, I still argue it is against the promise of your idea (`ArgumentParser` -> GUI without invasive code change).

So let's see code differences (please view it on github):

Original code

```python
from argparse import ArgumentParser

def main():
  parser = ArgumentParser(...)
  # rest of code
```

Current `@Gooey` decorator solution:

```python
from argparse import ArgumentParser
from gooey import Gooey        # <--- all it takes! :)

@Gooey                         # <--- all it takes! :)
def main():
  parser = ArgumentParser(...)
  # rest of code
```

Proposed solution:

```python
from gooey import GooeyParser as ArgumentParser  # <--- all it takes! :)

def main():
  parser = ArgumentParser(...)
  # rest of code
```

Note, that I have not made this example up, I have used your code from Gooey's [README](https://github.com/chriskiehl/Gooey/blob/94ea45d9ab66c703f6f34170c509c7030cf90690/README.md#usage) with a slight modification: added the missing `ArgumentParser` import and a missing `<--- all it takes! :)` note for `Gooey` import.

---

Should `gooey` provide an alias for `GooeyParser` as `ArgumentParser` we could import `ArgumentParser` from `gooey` directly, making the difference to the original minimal:

```python
from gooey import ArgumentParser  # <--- all it takes! :)

def main():
  parser = ArgumentParser(...)
  # rest of code
```

This would be an ideal, minimal API fully expressing your idea.

**Comment by krisztianfekete** [comment]
Oh, I overlooked, that `@Gooey` can have parameters, that specify how the GUI should behave.
Now I understand your insistence to keep the decorator - you would lose functionality by eliminating decorators for advanced users!

I do think, that basic use should not need a decorator, though.

**Comment by krisztianfekete** [comment]
So `@Gooey` currently is basically used as a context manager:
- set up  (monkey patch `ArgumentParser.parse_args` to display gui)
- call function, `.parse_args()` hijacked
- tear down  (reverse monkey patch, except I do not see it in code!)

Well, monkey patching is ...  modifying the behavior for a class, if we need to use `ArgumentParser` elsewhere afterwards, we could not!  (unlikely as it is, but still!)

**Comment by krisztianfekete** [comment]
Sorry for the many (and long) comments, I still think they are relevant, this one will be the last:

I admit, that having `@Gooey` optional for `GooeyParser` is almost all that is needed, and `@Gooey` decorator is not that bad if used only for parameter passing for code, where `ArgumentParser` is basically a singleton class, but I'd still prefer a solution more respectful to `ArgumentParser`  (no [monkey](https://github.com/chriskiehl/Gooey/blob/5220b4a1396a5d87e1fb011b35e94eb7610c505f/gooey/python_bindings/gooey_decorator.py#L70) [patching](https://github.com/chriskiehl/Gooey/blob/5220b4a1396a5d87e1fb011b35e94eb7610c505f/gooey/python_bindings/gooey_decorator.py#L121)).

What about this API for advanced users?

```python
# user code
import gooey
ArgumentParser = gooey.get_parser_class(
    advanced=Boolean,          # toggle whether to show advanced config or not 
    language=language_string,  # Translations configurable via json
    show_config=True,          # skip config screens all together
    program_name='name',       # Defaults to script name
    program_description,       # Defaults to ArgParse Description
    default_size=(610, 530),   # starting size of the GUI
    required_cols=1,           # number of columns in the "Required" section
    optional_cols=2,           # number of columbs in the "Optional" section
    dump_build_config=False)   # Dump the JSON Gooey uses to configure itself

...

def main():
  parser = ArgumentParser(...)
  # rest of code
```

where `get_parser_class` is much simpler than current `@Gooey`: it creates a subclass in closure with `.parse_args()` overridden.

---

One place, where the decorator syntax could bite, is when writing unit tests for the command line parser (I do it a lot, as it used to have bugs, and I am [not the only](http://stackoverflow.com/questions/18160078/how-do-you-write-tests-for-the-argparse-portion-of-a-python-module) [one](http://programmers.stackexchange.com/questions/220081/how-should-i-go-about-bringing-this-code-under-test)).

In this code:

```python
import gooey
ArgumentParser = gooey.get_parser_class(...)

def do_main(args):
    ...
    
def get_parser(parser_class=ArgumentParser):
    parser = parser_class(...)
    ...
    return parser

def main():
    args = get_parser().parse_args()
    do_main(args)
```

the parser can be tested separately by calling `get_parser(parser_class=argparse.ArgumentParser)` in test code.  (`main` can be made testable similarly, `do_main()` is already testable)

Where would you put `@Gooey`?
