### ISSUE TITLE
Gooey outputs characters after completion "[0m"

### ISSUE THREAD

**Issue by Jordan-Pierce** [chriskiehl/Gooey#884]
Windows 11
Python 3.8
Gooey 1.0.8.1

Thanks for this library, it's fantastic. However, at the end of the program, gooey outputs these characters in the console "[0m"? I don't believe this is my code, as I have log statements that indicate when the program has finished successfully. See attached image. Quite possibly a blunder on my part, but it's not obvious and I haven't see others post about it.
 
 

![Gooey_Issue](https://github.com/chriskiehl/Gooey/assets/115024024/a2563925-723e-4051-b92a-cd34ec98565e)

**Comment by elad-eyal** [comment]
switch to rich console

**Comment by Jordan-Pierce** [comment]
finally! thanks @elad-eyal
