### ISSUE TITLE
Too Few Arguments with Dropdown

### ISSUE THREAD

**Issue by mclaughlin6464** [chriskiehl/Gooey#92]
I have a selection of arguments I'm trying to import with the GUI. The ones that take standard textboxes or the file chooser work fine. However, when I have ones involving "choices" i.e. with a Dropdown, I get an error for "too few arguments." With the exact same argument, just with choices removed as a kwarg, it works fine. Somehow the choice from the Dropdown isn't being passed to the parser.

**Comment by chriskiehl** [comment]
Could you post a code sample that demonstrates the issue and a copy of the traceback?

**Comment by mclaughlin6464** [comment]
Sure, sorry about that. Also, markdown is misbehaving a bit. So the code block is:

`
from gooey import Gooey, GooeyParser

@Gooey( required_cols= 2)
def main():

    desc = '''
    This program models the light profile of a galaxy in a fits image using a Mixture-of-Gaussian model. It can use either MCMC or non-linear least squares.
    '''

    parser = GooeyParser(description = desc)

    parser.add_argument('filename', metavar = 'filename', widget= 'FileChooser', type = str,help = \
                                    'Either a fits filename or a directory of files.\n NOTE: The GUI will not allow you to choose a directory. Choose a file and edit the text.')

    parser.add_argument('centers', metavar = 'centers',widget= 'FileChooser', type = str,help = \
                                    'Either a filename or a comma separate pair of coordinates for x,y.')

    parser.add_argument('output', metavar = 'output',widget= 'DirChooser', type = str, help = \
                                    'Location to store the programs output.')

    parser.add_argument('modeler', metavar = 'modeler', type = str, choices = ['MCMC', 'NLSQ'], help = \
                                    'Modeler used to perform fit. Either MCMC or NLSQ.')

And when run, after entering options I get the following (sorry for jpeg):
![selection_001](https://cloud.githubusercontent.com/assets/6344210/8599045/d02d0ca2-2623-11e5-8ff1-424a28ec974d.jpg)

However if I remove the choices kwarg from the last add_argument the error goes away.

**Comment by chriskiehl** [comment]
Thanks for the extra details! 

Turns out this was a missing `return` statement... Oy.. :\

Anyways, fixed!
