### ISSUE TITLE
Arguments default values in GUI

### ISSUE THREAD

**Issue by francisft** [chriskiehl/Gooey#93]
First of all, great work for Gooey. It is very easy to use and quite powerful!

Is the GUI supposed to initialize widgets with arguments default values?
I'm wondering if I'm doing something wrong, or if it is simply not supported... yet.

Thanks.

**Comment by amorde** [comment]
I ran into the same thing a few months ago, I believe it is not yet supported.

**Comment by chriskiehl** [comment]
Nope. It doesn't initialize any default values in the widgets. It would break how Gooey builds the cli string. If there's a value there, Gooey will read it, which kind of breaks the idea of optional arguments :) 

Now, If you just wanted to *show* a possible argument for a field, WxPython does support placeholder text. However, it would be just that: a placeholder. Something not passed as an argument to your program.

**Comment by chriskiehl** [comment]
Wait, are you guys saying pass the argparse default into the widgets, *or* saying that you want a special field for populating defaults *outside* the machinery of argparse?

**Comment by amorde** [comment]
In argparse you can specify a default. So let's say you have a string input, the default value is "value." The textbox should already contain the string "value" when the user runs the application, and obviously they can change it if they want. Gooey correctly uses the default if the field is blank, so I don't think that's an issue

**Comment by chriskiehl** [comment]
@amorde, Ah, fudge. You're right. Wasn't thinking clearly! Very long work week and other excuses. 

I'll add support.

**Comment by amorde** [comment]
Hey man, it's totally fine! You have already done so much work on this. I actually meant to implement it a long time ago, but I couldn't figure out how to do it :s

**Comment by amorde** [comment]
If you can point me in the right direction I would be more than happy to take a look

**Comment by chriskiehl** [comment]
@francisft Fixed! PyPi will be updated in a few, or you could grab a fresh copy of the repo.

@amorde Thanks, but I got this one (you can take docopt support! ;p)

**Comment by amorde** [comment]
Nice, thank you!
