### ISSUE TITLE
Display screen messes up ASCII tables.

### ISSUE THREAD

**Issue by Datkros** [chriskiehl/Gooey#96]
Hello everyone. First of all, thanks to chris for his great work with Gooey.

I've been using Gooey to create a simple GUI for an script that does statistical calculation.
As an output, I need to show a table and the correspondient results of the rest of the calculations.
However, the display screen messes up the ASCII tables, not allowing them to be properly configured. Showing me this:
![42e3d26cdf](https://cloud.githubusercontent.com/assets/9646595/8894990/bea56146-3393-11e5-899f-85c16a50592c.png)

I've tried using Tabulate & PrettyTable, however, neither work. They do work on the CLI version though.

Is there any way to fix this? Is there any other library that allows me to show a table that works with Gooey?

Thank you for your time.

**Comment by chriskiehl** [comment]
It can be done! 

I just need to add an option to allow different fonts in that box. WxPython's default font uses a proportional typeface rather than a mono-space one (hence it breaking your ascii table formatting).

Should be a quick fix!

**Comment by Datkros** [comment]
That explains it! 
Thanks a lot for the quick response, and help.

I'll be waiting patiently for the fix.

**Comment by chriskiehl** [comment]
Alright! Done! 5 minute hack job before I step out for some lunch. :) 

The decorator now supports an additional boolean arg called `monospace_display`. Set that to true to enable mono-spaced output in the display panel. 

e.g. 

    Gooey(program_name="blah", monospace_display=True)

It should support arbitrary fonts, but.. that'll have to come later..!

**Comment by Datkros** [comment]
It works perfectly! Thanks a lot for your help. You rock!
