### ISSUE TITLE
Date Time Chooser Widget does not seem to work

### ISSUE THREAD

**Issue by chris1610** [chriskiehl/Gooey#98]
I have tried on Windows and Linux to get the DateChooser widget to work.

I can get the dialog box as shown below:
![image](https://cloud.githubusercontent.com/assets/1223892/9701706/08ba9ff2-53fc-11e5-8282-f7214f9fde53.png)

But when I choose a date, nothing gets populated in the field or passed through to the argument.

I don't see any error messages or anything else to indicate things aren't working.

I tried this with my own apps as well as the example.py script.

I am using the Anaconda python distro with Python 2.7.8 and wxPython 3.0

Let me know if there's anything else I can do to help out.

**Comment by chriskiehl** [comment]
Fixed! 

I misunderstood how `wxDialog`s return their value. Turns out the `wx.id_ok` had to be on the button itself, rather than returned in the event handler. 

You can pull down the fix from the repo or upgrade via pip. 

Thanks for the report!

**Comment by chris1610** [comment]
Thanks for the quick response. It is working better but it seems like the value that is being returned is only the day - "Tue" for example.

Shouldn't it be a full timestamp of some sort:

![selection_040](https://cloud.githubusercontent.com/assets/1223892/9702327/2deacb64-541d-11e5-9458-dc1f46196fd8.png)

**Comment by chriskiehl** [comment]
We'll _that's_ peculiar.. Do you see this on Windows and Linux?

**Comment by chris1610** [comment]
Linux at the moment.

**Comment by chris1610** [comment]
Ok. Looks better on Windows - I get a string like "09/05/15"


Same program on Ubuntu returns the day as a string.

**Comment by chriskiehl** [comment]
Grr. Alright.. I'm spinning up a linux box now. I'll get to the bottom of it. WxPython's shoddy cross platform behavior strikes again! 

Thanks for checking for me.

**Comment by chriskiehl** [comment]
Fixed (on both Windows and Linux this time)!

The behavior of the `WxDialogs` is extremely annoying and not nearly documented enough. On Windows, `Dialog.Close` returns the ID of the event source, on Linux... it does not. Oy..

**Comment by chris1610** [comment]
Confirming that it works. Thanks for the quick fix!
